### ISSUE TITLE
"Invalid Player Data" when trying to enter world

### ISSUE THREAD

**Issue by luffypirat** [petrolpark/Destroy#10]
Your mod directly makes a request to Patreon to check paid members and issue rewards, however, in countries where it is blocked, due to an unsuccessful connection attempt, you are simply not allowed into the world with the error "Invalid player data"
After enabling VPN everything worked. It would be more reasonable if you used your own server for queries, this will solve the problem

**Comment by petrolpark** [comment]
It is a separate server (not Patreon), but still may be blocked. Even so, it should just fail quietly if it can't connect. Can you send me your latest.log?

**Comment by luffypirat** [comment]
https://pastebin.com/ijk5wcx4

First came in under VPN, then from Russia

**Comment by petrolpark** [comment]
Try in [0.3](https://modrinth.com/mod/destroy). This is quite a hard one for me to test.

**Comment by luffypirat** [comment]
Fixed

**Comment by petrolpark** [comment]
Great!
