### ISSUE TITLE
Bug(Maybe): Wrong Molecular Model of Cubane-1,4-dicarboxylic Acid

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#100]
![image](https://github.com/petrolpark/Destroy/assets/45122555/c0bdcfc0-3982-4a58-ac86-d81983ad3643)
![image](https://github.com/petrolpark/Destroy/assets/45122555/f431b395-83d3-49f0-905b-a144bf739c50)
I got the second image on [pubchem](https://pubchem.ncbi.nlm.nih.gov/compound/1_4-Cubanedicarboxylic-acid). It seems that the two carboxyl should be on the body diagonal of the cubane. However they're shown on the same edge of the cubane in the model in game. I'm not sure if these structures are equivalent or just mistakenly to be different.

**Comment by petrolpark** [comment]
You're right. However, this won't be addressed until the full Cubane synthesis is implemented, if it is.

**Comment by petrolpark** [comment]
Fixed in 0.4 anyway.
