### ISSUE TITLE
[Suggestion] Compat With Pollution Of The Realms/AdvancedChimneys Filters

### ISSUE THREAD

**Issue by Evolut-ion** [petrolpark/Destroy#101]
The pollution system isnt yet very well explained from my experience with the ponder windows, but I like the idea and would love for some compatibility with other mods that both already utilize a pollution mechanic, plus an immersive way to manage and deal with pollution? Forge 1.20.1 v 0.2

**Comment by Nexusuxen** [comment]
Didn't know PotR was updated to past 1.12, nevermind to 1.20! I'd love to see integration with it too, if it's not impractical to implement. At the very least, it'd be good to avoid conflicts, bugs, and general frustrations (namely having two pollution mechanics stacking with one another).

Though, PotR is more localized, whereas Destroy's pollution appears to be partially or entirely global. Not sure how this could be best handled; perhaps a config to pick between local & global effects? If I'm playing with just a friend or two and we're basing together, I'd prefer global pollution. Buuuuut, on larger servers, I'd imagine global pollution would get real problematic real fast.

**Comment by petrolpark** [comment]
Pollution will be better explained in the full release, starting with the addition of Ponders. The pollution systems in these mods is very different to Destroy's, and generally simplifies handling pollution to 'put the emissions in this box and they magically get cleaned'. As Destroy takes the route of actual chemical solutions to the problem of pollution, compatibility with these things would be very invasive and so will probably not get added.
