### ISSUE TITLE
Dedicated server still unable to load in 0.3

### ISSUE THREAD

**Issue by koiboi-dev** [petrolpark/Destroy#102]
Uploaded the new Destroy version to the server, its still unable to launch

[2024-01-09-2.log.gz](https://github.com/petrolpark/Destroy/files/13876297/2024-01-09-2.log.gz)
[modlist (2).txt](https://github.com/petrolpark/Destroy/files/13876306/modlist.2.txt)

**Comment by MineKingTop** [comment]
Just pulled up just to report the bug again.
here's my log if of course it helps
[2CTlUhC.txt](https://github.com/petrolpark/Destroy/files/13877955/2CTlUhC.txt)

**Comment by petrolpark** [comment]
At least its failing for a different reason. This should be fixed in 0.4.

**Comment by UnknownVariables-here** [comment]
bruh where is 0.4
