### ISSUE TITLE
Performance issues / crashes when trying to make phenol

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#104]
Proccess:
1) Make vat
2) Add some of: Water, Benzene, Propene, AIBN, Sulfuric Acid
3) Enjoy as Destroy creates 0.0000 moles of every single organic compound imaginable (mostly AIBN with a bunch of substitutions). Your computer certainly won't.

I'm not really good at chemistry but I assume that the one gazillion byproducts are realistic, and definitely very impressive. However, it would be nice for the mod to not explode my computer. Maybe make it so chemicals under a certain amount/concentration in a vat don't react at all?

Bonus: https://pastebin.com/nZCaejds

(Btw, I failed to produce any phenol. But I'm sure that has more to do with my own incompetence)

**Comment by petrolpark** [comment]
Are you sure that's all you have in there? When I mix them I do get about 40 different Molecules, but no perpetual polymerization which is what the crash seems to imply.

**Comment by TheRedCrafter344** [comment]
There was also air (O2 and N2) in the vat. No perpetual polymerization occured when I tried it either, the largest molecule I saw had 17 carbon atoms. I had 4GB of RAM allocated btw, no mods installed other than create and destroy.

**Comment by TheRedCrafter344** [comment]
To clarify: It doesn't happen instantly, it requires about 1-2 minutes for the crash to happen with 4 GB of ram.

(also i want to ask but im not sure if this warrants a new issue post: when you put sulfuric acid (or any other acid) into water isn't it supposed to ionize?)

**Comment by petrolpark** [comment]
I'll test some more. Sulfuric acid does dissociate, though I think its products may have been lost among the organic side-products.

**Comment by petrolpark** [comment]
Fixed in 0.7.
