### ISSUE TITLE
Suggestion: Better vat UI, especially when there's a lot of chemicals

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#105]
Vat UI becomes very cluttered when there are a lot of chemicals inside. My suggestions are to 
a) Add a search bar 
and b) Split the chemicals up depending on whether or not they are in liquid or gas form.

**Comment by Auseawesome** [comment]
The splitting between liquid and gas is vital, especially when knowing what is going to get removed by pumps depending on whether they are submerged or not

**Comment by petrolpark** [comment]
This has been implemented in 0.6. If you are interested in the Suggestion Badge, DM me on Discord (`petrolpark`).
