### ISSUE TITLE
Pumpjacks not producing oil based on shaft rotation direction

### ISSUE THREAD

**Issue by Nexusuxen** [petrolpark/Destroy#108]
### Summary
Pumpjacks do not produce oil when their shaft is turning clockwise (to an observer facing North or West). They still produce oil if the shaft is turning counter-clockwise, however.

### Expected behavior
Pumpjacks should not care about which direction a shaft is rotating in order to actually produce oil.

### Steps to reproduce
0. Put a pumpjack in a chunk with oil
1. Power the pumpjack using a shaft rotating clockwise (when viewed facing either North or West)
2. See that it does not produce any oil

### Images
Here, the motors are turning clockwise. I am facing North in both images. In neither image do these pumps produce oil. Were I to place the motors on the other side, they would. This indicates that the direction of shaft rotation causing this bug is independent from the orientation of the pumpjack itself.
![image](https://github.com/petrolpark/Destroy/assets/28785926/edcb6382-abca-4fb2-b1ae-21571ca1309e)
![image](https://github.com/petrolpark/Destroy/assets/28785926/bcb1ad1e-08c3-4142-8dba-6b4e7d308022)

**Comment by petrolpark** [comment]
Fixed in 0.4.
