### ISSUE TITLE
Crash when placing a pipe next to a bubble column

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#11]
Forge version 47.2.19, Create 0.5.1.f, Destroy 0.1

Other loaded mods are JEI and Mousetweaks

How to recreate: place a pipe down next to a bubble column

[crash-2024-01-05_07.01.36-client.txt](https://github.com/petrolpark/Destroy/files/13842041/crash-2024-01-05_07.01.36-client.txt)

**Comment by petrolpark** [comment]
Fixed in 0.2.
