### ISSUE TITLE
Mod not allowing server to startup.

### ISSUE THREAD

**Issue by hippity-cs** [petrolpark/Destroy#111]
10.01 03:38:50 [Server] INFO Suppressed: net.minecraftforge.fml.ModLoadingException: Destroy (destroy) encountered an error during the common_setup event phase
10.01 03:38:50 [Server] INFO java.lang.ExceptionInInitializerError: null

Unsure if this means anything but I am unable to boot the server when Destroy mod is enabled.

Edit: Should add this is with Destroy 0.3 on a Forge 1.20.1_47.2.19 server.
https://paste.shockbyte.com/ojocosisodiyamerexuq

**Comment by petrolpark** [comment]
Duplicate of #102. Fixed in 0.4.
