### ISSUE TITLE
Nearly impossible to move a uniform solution from a vat into a basin

### ISSUE THREAD

**Issue by haus-jackl** [petrolpark/Destroy#114]
While realistic, it is not practical for example the ore processing. When pumping fluid out from a vat, it seems impossible to pump out a solution with the same concentrations into a basin which becomes an issue as basins can only hold two "unique: fluids.

**Comment by petrolpark** [comment]
It's not particularly realistic! 'Realistic' would be that they mix together when added to the same Basin. Which they now do. Fixed in 0.4.

**Comment by petrolpark** [comment]
This has been reverted in 0.6. You can just use a Mechanical Mixer to combine the different fluids.
