### ISSUE TITLE
Breaking and replacing a block on a vat makes item input impossible

### ISSUE THREAD

**Issue by haus-jackl** [petrolpark/Destroy#115]
see title

**Comment by petrolpark** [comment]
Are you sure you're reforming the Vat multiblock after you replace the block? If you hover over the Vat Controller, there shouldn't be an error message.

**Comment by haus-jackl** [comment]
I am sure as I am still able to insert chemicals into the vat. Its just that items will not input and output.

**Comment by FlamingKetchup** [comment]
Did you try relogging? I had a similar issue once, but I was unable to attribute the fix to anything in particular since I did a lot of things in between in not working and working (exiting, updating the version, and putting in the chemicals required for the reaction first).

**Comment by petrolpark** [comment]
Fixed in 0.4. Vats also now drop their Items when broken.
