### ISSUE TITLE
Ore electrolysation does not work

### ISSUE THREAD

**Issue by haus-jackl** [petrolpark/Destroy#117]
I have been struggling to electrolyze iron for a good couple days now. I am just entirely at a loss as to what is going on.
![2024-01-10_22 08 56](https://github.com/petrolpark/Destroy/assets/54426783/e929926c-2a3e-4325-b500-a805d1eb72b2)

**Comment by haus-jackl** [comment]
(i realize now that is iron (II) and not iron (III)

**Comment by haus-jackl** [comment]
![2024-01-10_22 19 58](https://github.com/petrolpark/Destroy/assets/54426783/8e4b7694-2906-445f-a459-14af6434d037)
though it also does not work with iron (III)

**Comment by BytinYarota** [comment]
![image](https://github.com/petrolpark/Destroy/assets/45122555/566cc25c-cc52-43be-ad10-ba917e8f6cab)
It works as expected here.
I guess you should check if the concentration of iron(III) in the solution you used is approximately 4.0M, while that of what I've used is 4.1M.
![image](https://github.com/petrolpark/Destroy/assets/45122555/db147f3d-f842-4222-a8b2-90bf7256534b)
(this is the solution I used)

**Comment by petrolpark** [comment]
I'm unsure what the problem is. The recipe calls for 4M Iron (III) (with leeway of 0.1M), which seems to work.

**Comment by haus-jackl** [comment]
I probably had the concentration off is it. I didn’t realize it was so exact
