### ISSUE TITLE
Suggestion: Separate the translation keys for 'chloride' and 'generic_chloride'

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#120]
Currently, both 'chloride' (Cl-) and 'generic_chloride' (R3CCl) use the same translation key, 'destroy.chemical.chloride', causing both to be displayed as 'Chloride' in the game. However, unlike in English, in Korean, each of them should be represented with different names: '염화 이온' and '염화물,' which respectively mean 'Chloride ion' and 'Chloride compound' in English.

I suggest giving them their own translation keys. They will still both appear as 'Chloride' in English, but translators can edit them to better suit their language.

**Comment by gisellevonbingen** [comment]
![image](https://github.com/petrolpark/Destroy/assets/44163945/e94b56a0-cf1c-4d7a-b302-73a2aa717ea9)
This is ion, so should called be "염화 이온" in ko_kr (chloride-ion)

![image](https://github.com/petrolpark/Destroy/assets/44163945/59811d80-c60e-4eac-ac78-00bf0be6517b)
And, this is compound, should name be "염화물" in ko_kr (chloride)

I agree their translation keys need to separate.

**Comment by petrolpark** [comment]
Fixed in 0.4. The ion will remain as `chloride` and the generic Molecule will be named with the key `destroy.chemical.organic_chloride`.
