### ISSUE TITLE
Bug: Blocks being extruded on the cart contraption are rendered weirdly

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#124]
https://github.com/petrolpark/Destroy/assets/106015638/ab8ac416-2cee-4cd8-81ff-82ab434d8f65

Forge: 47.1.3

Installed Mods:
- Create (0.5.1.f)
- Destroy (0.3)
- JEI (15.2.0.27)

**Comment by AsseyGithub** [comment]
On train:

https://github.com/petrolpark/Destroy/assets/106015638/c027ccad-046f-4032-bb3f-654f992daf7c

On double cart contraption:

https://github.com/petrolpark/Destroy/assets/106015638/17efa806-b684-40fe-a79c-bb22748208ae

**Comment by petrolpark** [comment]
Fixed in 0.4.
