### ISSUE TITLE
Random Crash when playing in world

### ISSUE THREAD

**Issue by Explode007** [petrolpark/Destroy#128]
I am playing with various mods but I'm on destroy 0.3 and forge 47.2.19

Here is crash report:
[crash-2024-01-06_12.42.53-client.txt](https://github.com/petrolpark/Destroy/files/13922062/crash-2024-01-06_12.42.53-client.txt)

**Comment by petrolpark** [comment]
This doesn't appear to be due to Destroy. I'm going to close this, but resubmit it if it occurs with just Create and Destroy.
