### ISSUE TITLE
Display link does not work with pollutometer

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#13]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

A display link hooked up to a pollutometer shows what looks like dotted symbols, this happens on every setting for the pollutometer.

![2024-01-05_08 38 27](https://github.com/petrolpark/Destroy/assets/75921990/94a3bb89-a385-4a98-a42e-e3db6b4f1fb6)

**Comment by petrolpark** [comment]
This is intentional; it's a progress bar, like the ones you can get from linking a Display Link to a boiler. As the pollution of the selected type increases, the bar will fill up (try the command `/pollution`).
