### ISSUE TITLE
Suggestion: Extended Fluid Tank/Mixture Functionality

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#130]
To make working with mixtures in fluid tanks less annoying:
- Display link setting for fluid tanks that displays mixture contents 
- Filling test tubes from fluid tanks

**Comment by petrolpark** [comment]
Fluid Tanks can't be interacted with with any Fluid-containing item in base Create unless you are in creative mode. This decision will be preserved with the Test Tube. Fluid Tanks are more compatible with Mixtures in 0.4. I'll probably add a Mixture-specific Display Source to them too.

**Comment by petrolpark** [comment]
This has been changed in 0.6 - you can now fill Test Tubes from Fluid Tanks.
