### ISSUE TITLE
Bug: Only 1 bottle of urine remains after using multiple glass bottles on urine cauldron

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#134]
https://github.com/petrolpark/Destroy/assets/106015638/8f851327-4e86-44cb-b8e0-025a80bf7db1

Forge: 47.1.3

Installed Mods:
- Create (0.5.1.f)
- Destroy (0.3)
- JEI (15.2.0.27)

**Comment by petrolpark** [comment]
Fixed in 0.4.
