### ISSUE TITLE
Getting rid of fluids in reboiler?

### ISSUE THREAD

**Issue by MineKingTop** [petrolpark/Destroy#135]
I don't know if its a bug, or if im doing something wrong, im trying to distillate ammonia solution, and I don't actually know how to get rid of the water. The only method I tried tht works its breaking the bubble cap. Any help? Thank you
![2024-01-14_13 20 35](https://github.com/petrolpark/Destroy/assets/97742326/30f53d4e-3431-4234-8e97-ca4ffe503fa3)

**Comment by petrolpark** [comment]
It can be pumped out, the same way it was pumped in.
