### ISSUE TITLE
Bug: Pumpjack Suffocates Player

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#136]
<img width="316" alt="image" src="https://github.com/petrolpark/Destroy/assets/45122555/f276b949-43d5-45ea-a447-6bd07c9dd4f0">

Approaching the green edges bouces off the player, the red edges suffocates the player.

**Comment by petrolpark** [comment]
The bounciness is a vanilla problem, but I'll look into the suffocation.

**Comment by petrolpark** [comment]
Fixed in 0.4.

**Comment by petrolpark** [comment]
Fixed in 0.4.
