### ISSUE TITLE
Several Vat Bugs

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#138]
1. **Printed Vats Invalid**
To recreate:
Build any valid vat, save it in a schematic then print it.
The printed controller will show the invalid message, and right-clicking it helps nothing.
The printed vat side blocks are recognized as destroy:vat_side, and only replacing all of them will the vat be formed.
It seems that the controller doesn't treat vat_side as a vat material.
If printing it using the schematicannon, vat_side blocks will not be printed at all.
2. **Vat Side Blocks Drops Nothing**
When breaking a vat block with proper tools in survival mode, it drops nothing.
However, once a vat block is broken, the vat structure is destroyed, the remaining parts will become their origin blocks and can be broken normally.
By the way, I suggest that vat blocks and controllers can be dismantled by wrenching as other machines.
3. **Vat Temperature Changes Discontinuously**
When heating or cooling a vat, its temperature floats in a range and jumps from the maximum to the minimun. This makes it extremely hard to control the temperature precisely.
4. **Controllers cannot Rotate**
Controllers have the facing data but can't be rotated by wrenching. And when printing a controller in a schematic, it always faces the origin direction even if you have rotated the schematic.

**Comment by petrolpark** [comment]
1, 2 and 4 have been fixed in 0.4. For 3, what do you have in your Vat? @helloworld069

**Comment by petrolpark** [comment]
Closing due to lack of a response. Open a new report if the issue persists.
