### ISSUE TITLE
Unable to set filter on brass funnel

### ISSUE THREAD

**Issue by sigmastar00** [petrolpark/Destroy#139]
Mod Versions:
    - Minecraft 1.20.1
    - NeoForge 47.1.86
    - Create 0.5.1.f
    - Destroy 0.3

Right clicking a brass funnel's filter slot with an item does not set the filter to that item, it instead sets the filter's stack size to 1. Filter slots on other blocks seem to function as expected, only the brass funnel is affected. This problem only occurs when Destroy is installed alongside Create.

**Comment by petrolpark** [comment]
Fixed in 0.4.
