### ISSUE TITLE
Suggestion: Monitoring Vats with Threshold Switches and Smart Observers

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#140]
Currently the vat isn't recognized as a fluid container by threshold switches and smart observers. I suppose it will be of great use for automation if the vat could be monitored by them.
In detail I have three ideas:
1.Attaching detectors monitors the solution amount in the vat.
2.If a test tube is placed in their filter, the amount of the main substance in the test tube will be detected in the vat.
3.If the detector is attached to a vat side block displaying the temperature/pressure, it will detect that value instead.

**Comment by petrolpark** [comment]
Something like this is planned. It may end up being a separate block though.

**Comment by petrolpark** [comment]
Implemented in 0.1.0.
