### ISSUE TITLE
Unable to see recipe of R3CCl

### ISSUE THREAD

**Issue by luluthepogcat** [petrolpark/Destroy#145]
![Screenshot (55)](https://github.com/petrolpark/Destroy/assets/154001303/670876c8-cb86-445b-bf57-88b953c73673)
with JEI installed, im still unable to see R3CCl's recipe

**Comment by Gfortes985** [comment]
Maybe the crafting for it hasn't been done yet

**Comment by petrolpark** [comment]
That's because there is no way to make organochlorides generically. Certain organochlorides (e.g. methyl chloride and chloroform) have specific recipes, but there is no general way. Generic syntheses of organochlorides may come to future updates.

**Comment by luluthepogcat** [comment]
How am i suppose to know that methyl chloride and chloroform is organochloride without chemistry knowledge?

**Comment by Gfortes985** [comment]
Learn Chemistry

**Comment by luluthepogcat** [comment]
![FAF92E3E-F03E-4242-AF77-2E1279FBD460](https://github.com/petrolpark/Destroy/assets/154001303/854e0840-a4f1-4aaa-9048-339b1e61a180)
Then thats just false advertisement

**Comment by Gfortes985** [comment]
The mod is still in beta, so a book of knowledge may be added in the future
