### ISSUE TITLE
bug: multiplayer server crash when ever destroy is present Caused

### ISSUE THREAD

**Issue by Traumatic-apricot** [petrolpark/Destroy#148]
i am trying to get a server running with destroy and a few other mods but when the destroy mod is active it never launches with this in the log ( Caused by: java.lang.NullPointerException: Registry entry not present: destroy:card_stock )  when i remove the mod it launches no issue. here is the full log: 
[latest.log](https://github.com/petrolpark/Destroy/files/13962585/latest.log)

**Comment by petrolpark** [comment]
Duplicate of #102 fixed in 0.4.
