### ISSUE TITLE
Bug: Problems with the upcoming salts name overriding

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#149]
While playing the source code build to test the upcoming salts name overriding, I encountered some issues. Thank you for granting me permission to report these.

***

### 1. Some monatomic cations cannot use a generic key:
> Calcium, Nickel, Potassium, and Zinc

Currently, these four cations cannot use their generic keys even though they are part of a salt. I will refer to them as the invalid elements.

![image](https://github.com/AsseyGithub/Cloud/assets/106015638/07b12eea-133e-43b0-912c-993882472e52)
It should be shown as "Potassium Chloride", but it isn't. (The reason 'Chloride' is displayed as 'Chloride Ion' will be explained next.)

All ions except for the four cations are valid elements, which can use their generic keys well.
> Acetate, Ammonium, Chloride, Chloroaurate, Copper (I), Copper (II), Cyanide, Cyclopentadienide, Fluoride, Hydrogensulfate, Hydroxide, Hypochlorite, Iodide, Iron (II), Iron (III), Nitrate, Nitronium, Oxide, Proton, Sodium, Sulfate, and Sulfide

***

### 2. Valid element keys under an invalid element key become invalid:
An invalid key makes all valid keys placed below it invalid.
```
{
    "destroy:acetate": {
        "generic": "destroy.chemical.acetate.salt"
    },
    "destroy:calcium": {
        "generic": "destroy.chemical.calcium.salt"
    },
    "destroy:chloride": {
        "generic": "destroy.chemical.chloride.salt"
    },
    
    ...
    
    "destroy:oxide": {
        "generic": "destroy.chemical.oxide.salt"
    }
}
```
In this case, "destroy:calcium" is an invalid key.

![image](https://github.com/AsseyGithub/Cloud/assets/106015638/be464b8f-aaa3-48e7-9a71-5c25b90fe4ff)
Acetate is displayed normally because its key is not under the calcium key.

![image](https://github.com/AsseyGithub/Cloud/assets/106015638/a0c54a6c-8955-48fc-b632-8de795e86323)
Calcium isn't. And Chloride isn't either because, although it is a valid element key, it is located below "destroy:calcium."

![image](https://github.com/AsseyGithub/Cloud/assets/106015638/6c79ce63-e2ce-441a-8299-faa50dd4264d)
Oxide isn't either.

***

You can replicate these issues with the resouce packs below. All of them are written in English. Use only one at a time.
| | Download |
|---|---|
| All Valid keys | [Only Valid.zip](https://github.com/petrolpark/Destroy/files/13964695/Only.Valid.zip) |
| All Invalid keys | [Only Invalid.zip](https://github.com/petrolpark/Destroy/files/13964697/Only.Invalid.zip) |
| All keys | [All.zip](https://github.com/petrolpark/Destroy/files/13964699/All.zip) |

* 'Only Valid.zip' includes only the valid element keys, and 'Only Invalid.zip' does the opposite. You will notice the latter doesn't work.
* 'All.zip' include the keys of all ions, displaying only acetate and ammonium corretly because all the other keys are below the invalid calcium key.

I can't wait to see this awesome feature in 0.4. Cheers!

**Comment by petrolpark** [comment]
The salt names are defined by the Molecule's ID, not their translation key. `destroy:calcium` breaks because there is no such Molecule as `destroy:calcium` - while its translation key is `destroy.chemical.calcium` its ID is `destroy:calcium_ion`. The same is true for all four broken examples you've given. You can check the IDs of Molecules [here](https://github.com/petrolpark/Destroy/blob/1.20.1/src/main/java/com/petrolpark/destroy/chemistry/index/DestroyMolecules.java). I'll probably change the translation key of these four ions - the only reason they are `calcium`, for example, and not `calcium_ion`, is because there doesn't currently exist any neutral calcium species.

**Comment by AsseyGithub** [comment]
Oh, I got it. They are based on the ID, not the keys...😅
