### ISSUE TITLE
Crash when viewing a vat that depletes a chemical inside of it

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#15]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

To recreate: Open the vat gui while you have a high RPM mechanical pipe extracting the oxygen and nitrogen from the freshly made vat, when either of them hit 0, the game will immediately crash

[crash-2024-01-05_09.10.22-client.txt](https://github.com/petrolpark/Destroy/files/13843039/crash-2024-01-05_09.10.22-client.txt)

**Comment by petrolpark** [comment]
Fixed in 0.3. I respect your commitment for finding that bug though; that took ages to drain.

If you'd like, message me on discord (`petrolpark`) and I'll give you the **Beta Tester** Badge.
