### ISSUE TITLE
a way to find oil chunk with command

### ISSUE THREAD

**Issue by luluthepogcat** [petrolpark/Destroy#151]
at the moment, finding oil chunk (based on my research) with command is undoable.

**Comment by petrolpark** [comment]
Is `/crudeoil ~ ~ ~` not working?

**Comment by luluthepogcat** [comment]
it works now but i encounter a new problem: LPG crash when put on centifuge

Vào Th 7, 20 thg 1, 2024 vào lúc 03:06 petrolpark <
***@***.***> đã viết:

**Comment by petrolpark** [comment]
Open a new report. This was a bug in 0.2, so make sure you're using the right version.
