### ISSUE TITLE
Bug: Proton Hydroxide Solution

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#152]
![image](https://github.com/petrolpark/Destroy/assets/106015638/2edc9c0c-5af2-4a20-bf86-afe4c70d3a88)
![image](https://github.com/petrolpark/Destroy/assets/106015638/e302a242-68d2-4a56-acf5-7b804bfd1aa7)

I think it should be displayed as Water.

**Comment by petrolpark** [comment]
Fixed in 0.5. Or 1.0. Whichever it will be.
