### ISSUE TITLE
My friends can't join my LAN server

### ISSUE THREAD

**Issue by Xuezhi-Yang** [petrolpark/Destroy#154]
forge47.2.16   Destory version 0.4
these are two Error reports.
![{73E54271-81FC-3975-BD23-CF04968B203D}](https://github.com/petrolpark/Destroy/assets/130138985/e77dd868-22ff-463e-a46b-3a4c892a6e8f)
![{7A474F36-89D7-6577-7B6B-19B7F4D1D525}](https://github.com/petrolpark/Destroy/assets/130138985/36d18d4c-5a9a-49ea-840b-e459edce4dd6)
But they can join after Destroy is deleted.
my logs.
[debug-4.log.gz](https://github.com/petrolpark/Destroy/files/13996695/debug-4.log.gz)
[2024-01-20-4.log.gz](https://github.com/petrolpark/Destroy/files/13996696/2024-01-20-4.log.gz)

**Comment by ErrorNotF0und** [comment]
I've got very simmilar errors, only using create and destroy.

**Comment by petrolpark** [comment]
Fixed in 0.5.
