### ISSUE TITLE
[Custom Modpack, Server, Crash] [Bug] Minimal server modpack startup crash, client loads fine

### ISSUE THREAD

**Issue by ThePixelist** [petrolpark/Destroy#155]
# Summary
My small (9-10 mods) custom modpack, hosted on Exaroton, crashes on startup. Destroy 0.4 is installed.
Relevant issues: #125 (same server and similar crash in question), #102 (the original issue for the bug in #125)
### [**Crash log**](https://mclo.gs/J1pMCRH)
![image](https://github.com/petrolpark/Destroy/assets/51265804/bb4bfb32-3fac-4cb4-bfbf-6ee7db3c0217)

# Information
Server runs **GraalVM 17**. Client is on PrismMC, with **JDK 17.0.2**. 1.20.1, Forge **47.2.20**.

# Modlist
Both server & client updated to latest mods as of today [2024 Jan 20 Sat].

## Server
- Cloth Config `11.1.118`
- Create `0.5.1.f`
- Destroy `0.4`
- FallingTree `4.3.4`
- **FerriteCore `6.0.1`**
	**The crash happens even if FerriteCore is uninstalled.**
- JEI `15.2.0.27`
- Moonlight `2.8.84`
- Multiplayer Server Pause `1.1.0`
- Supplementaries `2.7.27`
- Simple Voice Chat `2.4.32`

Simple Voice Chat is not configured to run, as the world has not been generated.
For the same reason, the DynamicLights datapack is not installed.
3GB of RAM and 1.5 Shared CPU Cores are allocated.

## Client

- Cloth Config v10 API `11.1.118`
- Controlling `12.0.2`
- Create `0.5.1.f`
- Destroy `0.4`
- Embeddium `0.2.18`
- EntityCulling `1.6.2`
- FallingTree `4.3.4`
- Ferrite Core `6.0.1`
- JEI `15.2.0.27`
- Moonlight Library `2.8.84`
- Mouse Tweaks `2.25`
- Multiplayer Server Pause `1.1.0`
- Notes `1.3.0`
- OpenLoader `19.0.3`
- The DynamicLights datapack is installed, meaning any singleplayer worlds will include it.
- Searchables `1.0.2`
- Simple Voice Chat `2.4.32`
- Supplementaries `2.7.27`

**Comment by 3kasper225** [comment]
Issue in Destroy's Salt Overrides function (it contains local function that detect language from client, but server core doesn't have one of that) or something like that. Wait patiently until petrol fix this in new version.

**Comment by petrolpark** [comment]
Fixed in 0.5.
