### ISSUE TITLE
Bug: IUPAC Name Display Issue for JEI chemicals

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#159]
With IUPAC name Disabled:
![image](https://github.com/petrolpark/Destroy/assets/106015638/8d6fe59f-696b-475a-9e89-8e18155d56db)

With IUPAC name Enabled:
![image](https://github.com/petrolpark/Destroy/assets/106015638/40a2005b-7dac-4dd0-a809-ac5ee2ba4e0d)
It should be displayed as 'Ethanoate'.

![image](https://github.com/petrolpark/Destroy/assets/106015638/c75d7edf-811f-4bc9-838d-946e59e80884)
![image](https://github.com/petrolpark/Destroy/assets/106015638/e725d7d9-99ab-44bc-b46d-112b92c40924)
In other cases, it is shown properly.

Installed Mods:
- Create (0.5.1.f)
- Destroy (0.4)
- JEI (15.2.0.27)

**Comment by petrolpark** [comment]
Does it change after you reload? This is one of the things a reload is needed for.

**Comment by AsseyGithub** [comment]
Ah, it changed after restarting the game. This seems to be solved.

**Comment by petrolpark** [comment]
I've changed it to not require a reload anyway.
