### ISSUE TITLE
Suggestion: Pipes connect to fluid handling blocks when next to them like they do for other fluid containers

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#16]
Pipes automatically connect to most fluid blocks like tanks, spouts, and so on. Ideally the pipes would automatically connect to bubble columns, vat multiblocks, and so on

Pictured below is the normal create interaction versus the bubble column

![2024-01-05_09 19 42](https://github.com/petrolpark/Destroy/assets/75921990/f38514fd-60df-49a9-a0f4-ec096c3e7668)

**Comment by petrolpark** [comment]
Bubble Caps have sided input. Wrench them to connect the glass outlet (which in this image is facing towards the camera). That being said though, they should automatically try to connect if a pipe next to them is placed, so it will be investigated. The directionality may be removed entirely.

What is the unexpected behaviour for Vats? Make sure you're not trying to connect to an edge as these are not part of the Vat.

**Comment by MindFaer** [comment]
The vat has the same interaction with pipes, no matter where it is placed

![2024-01-05_09 32 28](https://github.com/petrolpark/Destroy/assets/75921990/342774e9-fb01-4095-9d79-f7c9bd407c5b)

**Comment by petrolpark** [comment]
Blocks comprising the sides of Vats can only be connected by pipes on the exterior face (so see if that works?). That functionality won't change, but considering you expected it to connect that way I might add a note to the Ponder.

**Comment by MindFaer** [comment]
Sounds good, thank you!
