### ISSUE TITLE
[Suggestion]: Centrifuge splits types of potions into possible constituent types

### ISSUE THREAD

**Issue by soup587** [petrolpark/Destroy#160]
the title's probably a mess i apologise but think of it like, being able to centrifuge splash potion of fire resistance into splash water potion and fire resistant potion, lingering potion to lingering water
long potions could maybe be split into mundane and strong could be split into thick but i'm not entirely sure on how useful that could be (or how it may cause problems?)

to go with it potentially you'd be able to mix those potion types back together to make the 'upgraded' potions again (so say, a bartering farm could split into a tank of fire resistance and a tank of splash water instead of the two types of fire resistance and later mixed together when needed)

**Comment by petrolpark** [comment]
@soup587 Neat idea. I was thinking of something like this, and one person was enough to convince me to add it. This will be in 1.0. If you want the suggestion Badge, DM me on Discord (`petrolpark`).
