### ISSUE TITLE
Basin mixture changes seem to bug multifluid electrolysis 

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#163]
I tried to use the updated Castner-Kellner process but it seems to just not happen. I'm guessing this is because the recipe requires two different fluids: brine and mercury, but the update to allow basins to hold changing mixtures makes adding the two fluids create Mercury and Brine Solution.

**Comment by petrolpark** [comment]
That change has been reverted in 0.6, as different Mixtures can just be combined with a Mechanical Mixer.
