### ISSUE TITLE
Pure water makes electrolysis go 'slightly' mad

### ISSUE THREAD

**Issue by ammieeee** [petrolpark/Destroy#166]
May have something to do with #163, which I also experienced while testing
Feeding water (either distilled water or water obtained through JEI) to an electrolysis setup causes it to cycle through every electrolysis recipe in the mod, continuing until the recipe products fill up, in which case it then moves to the next recipe. 
Screenshot attached is the aftermath of allowing this to run to completion: 
![2024-01-20_20 09 25](https://github.com/petrolpark/Destroy/assets/122175572/c75f6399-ce13-46ed-8738-3546d21de580)
The mixtures in there appear to be mixtures of the products of the castner-kellner process, with slightly differing proportions of sodium amalgam and chlorine solution.
![image](https://github.com/petrolpark/Destroy/assets/122175572/fb75e16d-4ba4-49e6-851e-fab3ec12fc82)
![image](https://github.com/petrolpark/Destroy/assets/122175572/cd1fa730-482f-4527-ba00-edb018814234)

**Comment by petrolpark** [comment]
![image](https://github.com/petrolpark/Destroy/assets/72658778/786b4cc7-f54b-4496-88a7-ece254cde51b)

Nothing wrong here, nope. Fixed in 0.6.
