### ISSUE TITLE
(0.5) Iron Electrolysis Episode 3 (its not doing)

### ISSUE THREAD

**Issue by haus-jackl** [petrolpark/Destroy#168]
I'm pretty sure this is just that electrolysis is completely broken in 0.5 but I must report that I still have not managed to get iron electrolysis to function in this new version.
![2024-01-20_17 08 08](https://github.com/petrolpark/Destroy/assets/54426783/8dd16e33-4f8b-46d4-a5b0-cd65eb99961b)
![image](https://github.com/petrolpark/Destroy/assets/54426783/97779b0b-94a6-48e9-88bb-12a6e2cc27ff)

**Comment by petrolpark** [comment]
It got broken completely in 0.5 (see #166). Maybe third time will be the charm with fixing this.  If you'd like the **Beta Tester** Badge in return for the distress I'm sure this is causing you, DM me on Discord (`petrolpark`).
