### ISSUE TITLE
Early Bird badge's bold text messes up with usernames containing underscores

### ISSUE THREAD

**Issue by ThePixelist** [petrolpark/Destroy#17]
**Modpack:**
Forge 47.2.19 on 1.20.1
- JEI
- Destroy
- Create

Actual username:  `Mituna_Captor`
![image](https://github.com/petrolpark/Destroy/assets/51265804/6ffb15bf-16e4-4026-acdc-c27f76b95d62)!

**Comment by petrolpark** [comment]
Fixed in 0.3.
