### ISSUE TITLE
[0.5]Bug:failed to launch with MaFgLib

### ISSUE THREAD

**Issue by Xuezhi-Yang** [petrolpark/Destroy#171]
It will happen only when a mod called MaFgLib is updated to 0.1.5
forge 47.2.16
[crash-2024-01-21_11.20.45-client.txt](https://github.com/petrolpark/Destroy/files/13999893/crash-2024-01-21_11.20.45-client.txt)
[crash-2024-01-21_11.20.21-client.txt](https://github.com/petrolpark/Destroy/files/13999894/crash-2024-01-21_11.20.21-client.txt)

**Comment by petrolpark** [comment]
Closing unless re-reported for 0.0.8 (or 0.1.0, when it releases).
