### ISSUE TITLE
also reduce the temperature when pressure is lowered

### ISSUE THREAD

**Issue by Fyrstikkeske** [petrolpark/Destroy#175]
when increasing the pressure in a vat, the temperature gets higher. But not the other. 
to make thermodynamics in this mod even weirder, the temperature rose when lowering the pressure.
after some more testing it seems the temperature can go to a maximum of 26.7celsius

**Comment by petrolpark** [comment]
This all depends on how you alter the pressure. If you add liquid to decrease the volume, then the temperature of that liquid affects the temperature of the whole Vat (as the liquid and gas are always in thermodynamic equilibrium). Adding and removing anything affects the Vat's heat capacity, which will then cause temperature to reach a different equilibrium.
