### ISSUE TITLE
Suggestion: All vanilla and Create glass is useable for the vat multiblock

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#18]
Quick suggestion, currently only stock standard glass and tinted glass can be used for the vat multiblock, it would give more options for tank looks to allow stained, framed, and tiled glass be part of the multiblock.

(Only the middle one is a valid multiblock)

![2024-01-05_09 39 43](https://github.com/petrolpark/Destroy/assets/75921990/5067c861-7edb-4c56-87d1-016fed87cead)

**Comment by petrolpark** [comment]
Implemented in 0.1.0.
