### ISSUE TITLE
Suggestion: Multiple Mixtures/Phases in a vat

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#180]
Basically a single gas mixture, and as many liquid mixtures as needed. When a new chemical is added to a vat, it will attempt to insert itself into its mixtures based on some miscibility condition (i dont really know chemistry so i cant elaborate on this). If it cannot do that, a new mixture inside the vat will be created. Each tick, each mixture should react on its own, and then heterogeneous reactions between them should also occur (i dont really know chemistry so i cant elaborate on this either). Vat controllers should clearly display the seperate mixtures.

This would have practical considerations alongside aesthetic ones, as not every reaction can happen in every solvent.

**Comment by TheRedCrafter344** [comment]
This would also fix the problem with AIBN hydrolysing in water and causing my minecraft to crash, since AIBN (or other large esters) and water do not really mix.

**Comment by petrolpark** [comment]
This won't come to Vats, but potentially in the future another separating-funnel-like block. Obviously this is an old report, but for anybody reading this the AIBN-associated problems also got resolved.
