### ISSUE TITLE
Allow more concentrated refrigerants to cool more

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#181]
Currently it seems impossible, if not requiring an absurdly sized vat, to cool materials below around -8 degrees.

This makes liquifying certain components almost impossible, making collecting them out of a vat that was not fully emptied impossible

**Comment by Auseawesome** [comment]
(I was using completely pure ammonia as a refrigerant)

**Comment by Auseawesome** [comment]
Unless you have an incredibly low amount of gas inside the vat, but then it starts bugging and jumping all the way to 5000 degrees in some cases, causing all of the displays to rapidly flasj

**Comment by petrolpark** [comment]
What were you trying to cool?

**Comment by Auseawesome** [comment]
Less than 7 mols of ammonia (the same as I was using for coolant). I couldn't reduce it much more before it started to bug and the temperature would start bugging and the amount present would jump between 4/5 moles and 8000+.

**Comment by Auseawesome** [comment]
My vat was 1 block high and about 8x8 blocks wide, all of the bottom called by refrigerstrayters, which got slightly cooler than a 1x1x1 vat with slightly less ammonia in (it didn't seem to bug as easily with a smaller vat)

**Comment by BytinYarota** [comment]
I managed to cool a 3x3x3 vat to below -100 degrees. Maybe you could try using glass to construct the vat, since it has low conductivity.

**Comment by petrolpark** [comment]
This sounds like a fix. Later versions will include more possible Vat construction blocks so you will not be limited to requiring lots of weak glass if you want to reach significant temperatures, and the effects of conductance will be explained more clearly in tutorials.

**Comment by Auseawesome** [comment]
> I managed to cool a 3x3x3 vat to below -100 degrees. Maybe you could try using glass to construct the vat, since it has low conductivity.

Oh the conductivity actually matters, didn't realise that was a mechanic. Thanks for that.
