### ISSUE TITLE
Pulling a full vacuum on a vat is incredibly difficult.

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#182]
This makes handling gases within vats incredibly difficult without creating mixtures.

**Comment by Auseawesome** [comment]
For reference, I pulled about 800,000mb of nitrogen and oxygen out of a decently small vat before a full vacuum was pulled

**Comment by petrolpark** [comment]
Full vacuums are indeed very difficult to create in a real lab. There isn't any real need for a full vacuum, so this won't be changed.

**Comment by AsseyGithub** [comment]
Try using Mekanism. It will make vacuuming a Vat much easier.

**Comment by Auseawesome** [comment]
Let me also state that this was because when getting to very low pressures, it would randomly consider it to have more in than it did and jump between 0.001 moles and well over 1000+ and would sometimes make it impossible without breaking the vat and attempting to do it again

**Comment by Auseawesome** [comment]
just realised I forgot to say this

**Comment by Auseawesome** [comment]
This is the same issue as #184 was having, I just forgot to state this was the reason for having to pull so much gas out.
