### ISSUE TITLE
Uncraftable chemicals

### ISSUE THREAD

**Issue by Andromeda-Galaxy29** [petrolpark/Destroy#186]
Some chemicals don't appear to be craftable. Chlorine, iodine and some others don't have a recipe in jei. Only their ions seem to be craftable. And maybe that's just my awful chemistry knowledge, but I have no idea how to turn these ions into molecules.

**Comment by Auseawesome** [comment]
Chlorine is craftable through electrolysis of brine. Not sure about the rest. A lot of it is trial and error as proper JEI integration to make it fully stable is yet to happen.

**Comment by petrolpark** [comment]
Looks like a recipe for Iodine got missed, but chlorine is indeed made primarily through brine electrolysis. There is a bug where it sometimes doesn't show up because the recipe shown in JEI is the opposite direction of the reversible reaction.

**Comment by petrolpark** [comment]
Fixed in 0.6.
