### ISSUE TITLE
JEI Integration: Left clicking mixtures

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#188]
Left/Right clicking mixtures to bring up all of the components when looking through reactions in JEI would help make it a lot easier to see what I can use where, because currently you can't see where a specific mixtures came from or what it can be used in as it will just show you any mixture.

**Comment by petrolpark** [comment]
Fixed in 0.6.

**Comment by Auseawesome** [comment]
Such a prompt fix, thanks so much, this'll really help
