### ISSUE TITLE
Common Chemicals Available in the creative inventory/JEI

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#189]
Trying to experiment with crude oil is incredibly difficult in creative as to get large amounts you first have to find crude oil, add it to a container then copy that container a bunch. I think if common chemicals such as crude oil, brine and a refrigerant was available it would be a lot nicer to test certain systems

**Comment by petrolpark** [comment]
Good idea. For now though, if you have JEI you can hold CTRL and click the spanner button to enter cheat mode, which will allow you to grab test tubes of any chemical.

**Comment by Auseawesome** [comment]
Test tubes in creative, at least on normal liquid tanks from create don't seem to fill or change item and just delete fluid, they don't pull at all in survival. (Might want to create seperate issue)

**Comment by petrolpark** [comment]
These are both features of all fluid-handling items in base Create. However, the Test Tube has now been updated to allow it to be filled from Fluid Tanks (and any other Fluid-handling block) if in Creative mode, to make experimentation easier.
