### ISSUE TITLE
Agar Blocks have two unpacking recipes, preventing crafting them back into agar

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#19]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

Agar blocks are the storage block of both agar and fluorite, meaning that it can only be crafted into fluorite.

![2024-01-05_09 50 12](https://github.com/petrolpark/Destroy/assets/75921990/f0a71a2a-5d0b-4b45-97b8-64931dd7e1fa)

**Comment by petrolpark** [comment]
Fixed in 0.3.
