### ISSUE TITLE
Removing chemicals from a vat with a create pump is slower than moving

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#190]
If you make a vat and attempt to pump the air (or anything) into the air to drain it, it is drastically slower than pumping it into a container using the same pump, this makes automatic removal of waste products a large hassle.

**Comment by petrolpark** [comment]
This is a feature of base Create, and will likely not change.

**Comment by Auseawesome** [comment]
#193 As a sort of fix to make voiding liquids easier
