### ISSUE TITLE
Water not being treated as water

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#191]
When purifying an aqueous solution by evaporating this water. Or obtaining water from reactions in any other method. This 'water' is unable to be used in place of minecraft water for other mods, meaning that when you could normally use that water for some other product that needs minecraft water (EG a create recipe) you can't and instead have to pump water from somewhere else.

This is exacerbated by #190 as getting rid of this waste water can be slow, especially when gaseous.

**Comment by petrolpark** [comment]
This will not be changed. Mixtures contain lots of NBT and cannot be simply tagged as water.
