### ISSUE TITLE
Other recipes are ignored because of the mod

### ISSUE THREAD

**Issue by Fixer33** [petrolpark/Destroy#192]
Hey.
After installing version 0.5 I've noticed that some recipes are being blocked
For example: Experience farms on quartz no longer work because crushing wheels do not produce it anymore. But JEI still says it can be done:
![image](https://github.com/petrolpark/Destroy/assets/44867167/b56081b3-69df-4f35-9eaf-e84b345c2856)

**Comment by Fixer33** [comment]
BTW: Recipe for experience is added by _Create: Stuff and Additions_

And probably other recipes can be influenced as well

**Comment by petrolpark** [comment]
Create: Stuff & Additions is a closed-source MCreator mod, so this issue is almost definitely caused by that.

**Comment by Auseawesome** [comment]
This appears to be a simple recipe conflict not something specific to an mcreator mod

If you use kubeJS or make a datapack you could override both the recipes to produce both of the products.
