### ISSUE TITLE
Version of vent for the bottom of a vat

### ISSUE THREAD

**Issue by Auseawesome** [petrolpark/Destroy#193]
Because the pumping of chemicals to void them cannot be done quickly, a vent on the bottom of the vat that can be toggled like the normal one on the top to train liquids would be very useful when dealing with liquid byproducts

**Comment by petrolpark** [comment]
Likely won't make it in. The throttling of Mixture removal only occurs when Mixtures are yet to equilibriate. A better way to stop reactions suddenly might be to quench them with some other reagent.
