### ISSUE TITLE
Game Crash When breaking a storage tank containing liquefied petroleum gas

### ISSUE THREAD

**Issue by Hikari16665** [petrolpark/Destroy#194]
Destroy version:0.5

Crash Report: -> https://mclo.gs/aXVoGeC
Game Log: -> https://mclo.gs/PNlHYdr

Java version:17.0.3
Forge version:47.2.19

**Comment by Auseawesome** [comment]
Can you recreate this without all the mods? I just looked through your crash report and you have a ton of mods on

**Comment by petrolpark** [comment]
Was this on a server?

**Comment by Hikari16665** [comment]
yes, and I will try to recreate this with just one mod.

**Comment by Hikari16665** [comment]
and it also happens when i am trying to pump out the liquid to the world with mechanical pump

**Comment by Hikari16665** [comment]
Can it be fixed?

**Comment by petrolpark** [comment]
Fixed in 0.6.
