### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by coolbot100s** [petrolpark/Destroy#2]
I'm experiencing the same crash every time i attempt to load my instance with this mod.  
This crash has occurred with the latest version of create `0.5.1.f` and version `0.5.1.e`, along with both the latest and recommended forge versions, and the latest neoforge version.  

Screenshot of the issue and crash report file attached below. 

![image](https://github.com/petrolpark/Destroy/assets/76798835/7e6f5104-8eb5-4c12-8c51-9db03e16c0a6)
[crash-2024-01-04_16.34.08-fml.txt](https://github.com/petrolpark/Destroy/files/13836725/crash-2024-01-04_16.34.08-fml.txt)

**Comment by Junnaturefox** [comment]
I get the same issue
[https://mclo.gs/aKadSCb](url)

**Comment by petrolpark** [comment]
Hopefully patched in 0.1, which should release imminently.
