### ISSUE TITLE
Crash when starting server

### ISSUE THREAD

**Issue by MineKingTop** [petrolpark/Destroy#20]
When trying to load a server, with just create and destroy its crashing,
Tried with just create and it loads fine.
im using destroy 0.2 and create  0.5.1f
Here's the crashlog
[crash-2024-01-05_14.42.26-fml.txt](https://github.com/petrolpark/Destroy/files/13843422/crash-2024-01-05_14.42.26-fml.txt)

**Comment by petrolpark** [comment]
Looks like some client-only classes were being loaded on the server side. Once 0.3 releases, have a go in that.

**Comment by blockher88** [comment]
Having the same issue.
Attaching the crash report hoping it helps.
[crash-2024-01-05_21.25.50-fml.txt](https://github.com/petrolpark/Destroy/files/13844897/crash-2024-01-05_21.25.50-fml.txt)

**Comment by Adrian-Jansen** [comment]
I'll include my crashfile as well in case it helps further.

[crash-2024-01-06_20.28.55-fml.txt](https://github.com/petrolpark/Destroy/files/13848706/crash-2024-01-06_20.28.55-fml.txt)

**Comment by windth001** [comment]
I'll also include my crash file similar issue, but different mods loaded. Server runs without Destroy but crashes with it.  Also using Destroy 0.2 and create 0.5.1.f I'm pretty sure I don't have any client-side only mods just server and server/client, but it's always possible I've missed one.

[crash-2024-01-06_10.19.42-fml.txt](https://github.com/petrolpark/Destroy/files/13849202/crash-2024-01-06_10.19.42-fml.txt)

**Comment by petrolpark** [comment]
Fixed in 0.3.
