### ISSUE TITLE
Acid-catalyzed dehydration of ethanol

### ISSUE THREAD

**Issue by jgcodes2020** [petrolpark/Destroy#204]
A well known way to obtain ethylene (IUPAC: ethene) is by [dehydrating ethanol](https://chem.libretexts.org/Bookshelves/Organic_Chemistry/Supplemental_Modules_(Organic_Chemistry)/Reactions/Elimination_Reactions/Elimination_Reactions/E._The_Dehydration_of_Ethanol#:~:text=Ethanol%20can%20be%20dehydrated%20to,at%20about%20170%C2%B0C.) with concentrated H2SO4.

This would give a "green" route to ethylene.

**Comment by petrolpark** [comment]
Added in 1.0, for any generic alcohol (not just ethanol).
