### ISSUE TITLE
Using "There is NO crude oil in this chunk." instad of "There are about 0 bucket of Crude Oil in this chunk"

### ISSUE THREAD

**Issue by Hikari16665** [petrolpark/Destroy#206]
Using "There is NO crude oil in this chunk." instad of "There are about 0 bucket of Crude Oil in this chunk"

**Comment by Hikari16665** [comment]
By the way, when will version 0.6 be released? My server is currently being affected by issues that will be fixed in version 0.6.

**Comment by petrolpark** [comment]
Implemented in 1.0.
