### ISSUE TITLE
Unable to craft Ammonium Nitrate

### ISSUE THREAD

**Issue by mcclellanja** [petrolpark/Destroy#208]
Attempting to craft Hyperaccumulating Fertilizer and unable to craft ammonium nitrate, not sure if I'm doing it wrong or not but I can't even locate it in the JEI menu, and there is no recipe for the pellets or use for them.

**Comment by petrolpark** [comment]
The prills have been deprecated, you have to use a mixture.

**Comment by mcclellanja** [comment]
Thanks! I saw the note below the prills so that makes sense. I might just be doing it wrong and I'm sorry for the stupid question but there isn't an ammonium nitrate molecule or mixture in the JEI menu, when I try and look up the recipe for the fertilizer it shows a mixture containing Ammonium nitrate but there isn't a recipe for ammonium nitrate. Googled it and tried with ammonia and nitric acid and that didn't do anything, among a few other things. I'm sure I'm doing it wrong but not able to find the recipe in JEI so I'm a little at a loss. Sorry again for the stupid question, I Love this mod a lot and it is put together super well. I'm glad to see the frequent updates too! Thanks for it!
