### ISSUE TITLE
Easier ways to obtain H₂

### ISSUE THREAD

**Issue by Andromeda-Galaxy29** [petrolpark/Destroy#209]
It is used in many reactions but cannot be easily obtained. I suggest adding electrolyzing water into oxygen and hydrogen, for an easier way to obtain it.

**Comment by petrolpark** [comment]
The main source of hydrogen is through steam reformation, from methane and carbon monoxide. As Basins cannot support gases, the electrolysis of pure water will not be coming soon, if ever (its an extremely rare practice to electrolyze water industrially).
