### ISSUE TITLE
Higher levels of inebriation lead to insane gains of velocity

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#21]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

Drinking double refined moonshine, or triple, will cause you to be accelerated in any direction you move in

This does not happen for the level 1 inebriation effect

https://github.com/petrolpark/Destroy/assets/75921990/a40f7119-e763-4eb1-89f9-088a50438370

https://github.com/petrolpark/Destroy/assets/75921990/0a1e2c1b-f405-448a-9722-f68e9a93d3e9

**Comment by petrolpark** [comment]
Fixed in 0.3.
