### ISSUE TITLE
Command for crudeoil creation

### ISSUE THREAD

**Issue by Kcraft059** [petrolpark/Destroy#210]
Allow op players to add crudeoil in chunks via a command like /crudeoil <x y z> add <Number of milibuckets> and for singleplayer world accessible via activating cheat option at world creation.

**Comment by petrolpark** [comment]
Crude Oil and its detection will probably be reworked almost entirely, as currently finding it is a total chore.

**Comment by walksanatora** [comment]
currently on a server I am in. we added pneumaticcraft just so we can use it's oil in refinement

**Comment by petrolpark** [comment]
Implemented in snapshot 11.
