### ISSUE TITLE
Schematicannon Fuel

### ISSUE THREAD

**Issue by TheBlckbird** [petrolpark/Destroy#211]
I find it quite annoying that you can’t use Gunpowder in Schematicannons when using Destroy. Would you consider readding it as fuel? I think Schematicannons shouldn’t be that hard to use. And also the `SchematicannonInventoryMixin` even has a comment saying

This allows any Destroy explosive (not **just** gunpowder)

**Comment by petrolpark** [comment]
Fixed in 0.6.

**Comment by TheBlckbird** [comment]
When is it coming out and is there a workaround for now?
