### ISSUE TITLE
[Suggestion] A simpler way to obtain pure oxygen

### ISSUE THREAD

**Issue by Hikari16665** [petrolpark/Destroy#214]
There is currently no easy way to obtain oxygen other than from the air.
Suggestion:Electrolysis, Cryogenic Distillation, etc.

We also need a simple method to separate mixed gases. such as Adsorption.

If it does exist, please specify it in the JEI. Thank you!

**Comment by BytinYarota** [comment]
Maybe cryogenic distillation was already a available method? Cooling a vat filled with air till oxygen liquefies, you can simply pump out pure oxygen as a liquid.

**Comment by Hikari16665** [comment]
okay closed
