### ISSUE TITLE
Bug: The names of Vat filters for solution and gas are swapped in 0.6

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#217]
![image](https://github.com/petrolpark/Destroy/assets/106015638/e782d9e0-bca2-4a78-90b9-cbfa528c5660)
![image](https://github.com/petrolpark/Destroy/assets/106015638/af69a64e-8d06-4e29-84ec-ee29ba1ca425)

Other than that, it works fine.

**Comment by petrolpark** [comment]
Fixed in 0.7.
