### ISSUE TITLE
Bug: The lower the conductivity, the faster the vat temperature changes.

### ISSUE THREAD

**Issue by AsseyGithub** [petrolpark/Destroy#219]
https://github.com/petrolpark/Destroy/assets/106015638/b6294dec-576d-4ebe-bbc2-3b3e51d4d0ac

https://github.com/petrolpark/Destroy/assets/106015638/0cbc56cc-e9ba-4e50-a0e6-08db22bf3311

https://github.com/petrolpark/Destroy/assets/106015638/4d799024-23a3-4c33-8c5d-d55e985304c8

<table>
<tr>
 <td> Material
 <td> Conductivity
<tr>
 <td> Glass
 <td> 15W/mK
<tr>
 <td> Iron Block
 <td> 50W/mK
<tr>
 <td> Copper Casing
 <td> 400W/mK
</table>

I think it should be reversed.

**Comment by petrolpark** [comment]
Conductance only affects heat/loss gain to the air; transfer from burners and Refrigerstrayters are unaffected. This is why glass reaches a higher equilibrium temperature - it's less conductive so the heat supplied from the Burners is loss less quickly.
