### ISSUE TITLE
Milks removes the Cancer Awareness status effect

### ISSUE THREAD

**Issue by MindFaer** [petrolpark/Destroy#22]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

I assume with the message in game this is not intended, as it says it should only be removed with Cisplatin.

Thank you from the bottom of my heart for adding this message btw instead of trying to recreate cancer effects like some other mods have

**Comment by petrolpark** [comment]
Fixed in 0.3. And thank you, glad I made the right call.
