### ISSUE TITLE
Bug when inserting gaseous mixture to cold vat

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#220]
When a mixture of propylene and butadiene (obtained by centrifuging LPG) is inserted into a vat that is cooled to a temperature of about -7 degreess Celsius (below the butadiene's boiling point), no new moles of butadiene are added to the pre-existing few moles of butadiene in it (that existed as gas before the vat was cooled, and liquefied afterwards). Propylene is added normally.

**Comment by petrolpark** [comment]
Fixed in 0.7.
