### ISSUE TITLE
Server crashes while looking at control vat

### ISSUE THREAD

**Issue by GeneralLeon** [petrolpark/Destroy#226]
Server crashes whenever a user tries to look at a control vat ingame

Crash report is shown below:
https://mcpaste.io/223bb39b5ac819bb

Please let me know what I would need to do in order to fix this problem asap.

**Comment by Faolon12** [comment]
@GeneralLeon its been fixed, update your destroy version to 0.6

**Comment by GeneralLeon** [comment]
Okay thanks I'll check it out
