### ISSUE TITLE
Suggestion, destroy and create new age compatability

### ISSUE THREAD

**Issue by Faolon12** [petrolpark/Destroy#227]
trying to use the new age heater on the distilation tower, tower says its 127 degrees (same as with blaze)
but it doesnt distill

**Comment by petrolpark** [comment]
What are you trying to distill? Send a picture of the setup.

**Comment by petrolpark** [comment]
Destroy uses Create's Heat Level API, so as long as Create: New Age does too there shouldn't be a problem. As CNA is closed source I am unable to see if this is the case, so due to that and lack of a response this will be closed.
