### ISSUE TITLE
Bug: Bubble caps can't have multiple pipe connected to the same block

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#229]
![2024-01-27_13 39 58](https://github.com/petrolpark/Destroy/assets/43097488/9b96bd56-452f-4177-83a7-c543c5313dfd)

**Comment by FlamingKetchup** [comment]
It might not be a reboiler issue? I put a bubble cap under the reboiler to make it not a reboiler and I still can't pump out of it

**Comment by FlamingKetchup** [comment]
Ok, I think it's that bubble cap blocks can't have multiple pipes connected to one block

**Comment by FlamingKetchup** [comment]
Breaking the existing pipe connection will make the second unconnected pipe connect without having to replace it

**Comment by petrolpark** [comment]
Not a bug. Directionality will probably be removed in future though.
