### ISSUE TITLE
Extrusion Die Pick-Block Functionality Error

### ISSUE THREAD

**Issue by OnioTheSeal** [petrolpark/Destroy#23]
Forge 47.2.17
Create 0.5.1.f
Destroy 0.2

When attempting to use Pick Block on a placed Extrusion Die, it does not register as the same one existing in a player's inventory, causing it to not be selected in Survival Mode and creating a duplicate in the hotbar in Creative Mode.

**Comment by petrolpark** [comment]
I'm unable to replicate this. Do you have any other mods installed? If you run `/data get entity @s` when you have both 'different' Extrusion Dies in your inventory what do you get?

**Comment by OnioTheSeal** [comment]
![javaw_QSwaCxMQ1l](https://github.com/petrolpark/Destroy/assets/66274602/9618af05-c3bc-465d-81c4-1a2cebe38ad8)
Here, I have attached a gif.
The only other mod in this instance is Just Enough Items
Nothing in /data indicates a difference in the items in my inventory

**Comment by petrolpark** [comment]
That is really weird. I'm still unable to replicate this, so I'll wait and see if anybody else experiences it. I have no clue what could be causing it because the Extrusion Die doesn't do anything weird with its item.

**Comment by soup587** [comment]
can confirm as well, but the pickblocked items _are_ indeed the same, i can stack them up

**Comment by petrolpark** [comment]
Fixed in 1.0.
