### ISSUE TITLE
Suggestion: Large Distillation Structures

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#230]
Allow bubble caps to assemble into 2x2 or 3x3 wide structures, like fluid tanks can. I know generic distillation can be scaled up with vats, but I don't think fixed distillation recipes like Crude Oil distillation can.

**Comment by petrolpark** [comment]
This isn't too likely, especially as as you say the Vats are the step up from Distillation Towers for lots of uses. Potential cross compatibility with TFMG's distilleries might help this.
