### ISSUE TITLE
Bug: Can't reuse mercury in electrolysis

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#231]
Basin has 996 mB of recycled Mercury and 1000 mB of Brine, but doesn't electrolyze. Electrolysis worked with fresh mercury from distilling cinnabar, but not from mercury distilled and centrifuged from Mixture. Basin data is below
> {EvaporatedFluid: {FluidName: "minecraft:empty", Amount: 0}, FilterAmount: 64, InputTanks: [{Level: {Speed: 0.25f, Target: 0.996f, Value: 0.996f}, TankContent: {FluidName: "destroy:mixture", Amount: 996, Tag: {Mixture: {Temperature: 297.8871f, Contents: [{Molecule: "destroy:mercury", Concentration: 67.04707f}], AtEquilibrium: 0b}}}}, {Level: {Speed: 0.25f, Target: 1.0f, Value: 1.0f}, TankContent: {FluidName: "destroy:mixture", Amount: 1000, Tag: {Mixture: {Contents: [{Molecule: "destroy:water", Concentration: 55.555556d}, {Molecule: "destroy:sodium_ion", Concentration: 1.0d}, {Molecule: "destroy:chloride", Concentration: 1.0d}], TranslationKey: "fluid.destroy.brine"}}}}], OutputTanks: [{Level: {Speed: 0.25f, Target: 0.0f, Value: 0.0f}, TankContent: {FluidName: "minecraft:empty", Amount: 0, Tag: {Mixture: {Contents: [{Molecule: "destroy:mercury", Concentration: 66.825d}, {Molecule: "destroy:sodium_metal", Concentration: 1.0d}], TranslationKey: "fluid.destroy.sodium_amalgam"}}}}, {Level: {Speed: 0.25f, Target: 0.0f, Value: 0.0f}, TankContent: {FluidName: "minecraft:empty", Amount: 0, Tag: {Mixture: {Contents: [{Molecule: "destroy:hydrochloric_acid", Concentration: 1.0d}, {Molecule: "destroy:hypochlorous_acid", Concentration: 1.0d}, {Molecule: "destroy:water", Concentration: 55.5d}], TranslationKey: "fluid.destroy.chlorine_solution"}}}}], Overflow: [], OutputItems: {Size: 9, Items: []}, InputItems: {Size: 9, Items: []}, Filter: {id: "minecraft:air", Count: 1b, tag: {Charged: 0b}}, Results: [], DisabledSpoutput: [], x: -28, y: 67, z: -66, id: "create:basin", TooFullToReact: 0b, UpTo: 1b, FluidOverflow: []}

**Comment by petrolpark** [comment]
The mercury is at the wrong concentration.
