### ISSUE TITLE
Suggestion for config ?

### ISSUE THREAD

**Issue by Raptotorusrex** [petrolpark/Destroy#232]
Soooo i would like to know if its possible to have the old TNT recipe ? one of my friends aren't really happy with it but he said he would learn how to make TNT if he doesn't have the choice

**Comment by petrolpark** [comment]
You can add an alternate recipe for TNT with a datapack. A future version will probably contain a block which is crafted with Gunpowder (like vanilla TNT), but isn't erroneously called 'TNT'.
