### ISSUE TITLE
Suggestion: Advanced Heat blocks/Insulation

### ISSUE THREAD

**Issue by SunShine214** [petrolpark/Destroy#238]
Maybe an insulation block that can be put around a vat to lower its conductivity? Additionally, heatsinks/heat pipes and heat exchangers to transfer heat, or possibly even heat pumps. (Though having to make your own heat pumps using refrigeration would probably make more sense)

**Comment by petrolpark** [comment]
There will not be any separate blocks to affect conductance, as that's the point of having to choose what to make the Vat out of. In the future, there will be more Vat blocks, including some more advanced ones that mean you're not forced to choose between conductivity and strength.

As for heat transfer, all I can say at the moment is that there are more ways planned to heat Vats.
