### ISSUE TITLE
Adding Destroy mod Recipe Types to my Mod

### ISSUE THREAD

**Issue by Ryno1278** [petrolpark/Destroy#247]
I am not sure if this is the right place to ask this, But I am looking to add new recipes to your mod for private use via my own mod. I was looking through the code and I found The Recipe types such as  "Aging" , "Distilling" etc, but in the mixing recipe type I could not find a "cooled" heat requirement for the basin mixing with the "refrigerstraytor". Anyways I wasn't sure if it was available in recipes with json format. I really want to add recipes with the refrigerstraytor but I can't find any related code or anything. Help would be much appreciated! 

(PS: sorry if my java/modding terminology is terrible, I am Fairly new to modding.)

![screenshotheat](https://github.com/petrolpark/Destroy/assets/158834551/4ae7a430-c72d-4917-9802-f08a864f9226)

**Comment by petrolpark** [comment]
Yes, you can just replace `heated` with `cooled` in any recipe type that allows Blaze Burner heating - even ones not added by Destroy. There are some compacting recipes that require `cooled`.
