### ISSUE TITLE
Pollution does not work

### ISSUE THREAD

**Issue by trueblue222** [petrolpark/Destroy#249]
When I try to put a ton of ethanol into the air through mechanical pumps, the pollution level for smog doesn't rise, there are no visual effects, the pollutometer+display link doesnt show any, and the pollution query command shows theres no pollution for smog. I can't seem to get other kinds of pollution to do anything either, even in massive quantities. In the config pollution is enabled as well.
![image](https://github.com/petrolpark/Destroy/assets/55673470/303c61e2-286e-4f37-8931-74b92d23700f)

**Comment by petrolpark** [comment]
Fixed in 0.7.
