### ISSUE TITLE
Tnt Chain reaction

### ISSUE THREAD

**Issue by ghost** [petrolpark/Destroy#25]
When a TNT (from the mod or vanilla) ignites a TNT from the mod, that TNT becomes vanilla.

Before Moded-Moded:  ![Before 1](https://github.com/petrolpark/Destroy/assets/130255931/66c48533-208e-4b0b-a596-1b6c7d4a6e21)
After Moded-Moded:  ![After 1](https://github.com/petrolpark/Destroy/assets/130255931/d737d64f-0d28-4306-9c3a-057a2a203e69)
Before Vanilla-Moded:  ![Before 2](https://github.com/petrolpark/Destroy/assets/130255931/e2173d48-10b1-4675-a344-e42157d19be7)
After Vanilla-Moded:  ![After 2](https://github.com/petrolpark/Destroy/assets/130255931/2f2c7d24-cde4-4a01-9562-76dc9c42649b)

**Comment by petrolpark** [comment]
Fixed in 0.3. Thanks for the feedback :)
