### ISSUE TITLE
Problems generating sodium hydroxide and recovering mercury

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#251]
When i transport 1000 mB of sodium amalgam with 1000mB of distilled water to the vat, the volume goes up by 15mB, giving a total of 2015mB. When trying to separate the resulting sodium hydroxide and mercury solution by centrifuge, the only resulting products are mercury and mercury solution. When turning the resulting mercury solution to mercury and water via distilation and combining it with the previous mercury from the centrifuge, it amounts for a bigger volume than que starting mercury, and if added to a vat, the volume qctually gets smaller than the initial 1000mB. Also it can no longer be used to make electrolisis, even showing it being only mercury in the vat, basin and fluid tank.

**Comment by petrolpark** [comment]
Fixed in 0.7.
