### ISSUE TITLE
Unwanted Diels alder reaction at -50⁰C without any catalist

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#252]
I cannot obtain butadiene from LPG by cooling it at -50⁰C for two reasons: It either just gets deleted from the vat or, if the temperature is elevated at almost room temperature, ir reacts with ethylene to make hexene, and just 2 mB of hexene, never being able to obtain more. Had the same problem of being deleted from the vat with propene.

**Comment by petrolpark** [comment]
Diels-Alder reactions are not catalysed. The problem with mixtures disappearing when put in cold vats is known, so I'm going to close this as a duplicate of #220.
