### ISSUE TITLE
Cannot remove mercury and sodium hydroxide solution if not using a specific volume

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#253]
I tried to add half a basin of water (500mB) to 1000mB of sodium amalgam in a vat to generate a less diluir solution (more hydrogen generation with less volume to recycle). The reaction took place, but i can't extract it with a pump unless the volume is brought to 2000mB (wich it corrects to 2015 mB for some reason).

Also, on more of a realistic note, mercury doesn't dissolve on water that easily to form a solution, so a mercury solution would only be possível with mercury II or I, not in the metalic form. It would be great to be able to separate phases of a mixture without having to rely on centrifuge!

**Comment by petrolpark** [comment]
@Phosgenick Are you sure the pipe you are extracting with isn't above the fluid level?

Destroy currently doesn't process anything to do with phases, and assumes everything is miscible (so this isn't just a thing with mercury). In the future there may be a block to address this (some sort of separating funnel), but for Mixtures in Basins and Vats this probably won't change.

**Comment by Phosgenick** [comment]
Yeah, it was at the bottom of the vat, don't know why it had difficulty to recognize the different volume, but it's easy to overpass just by adding more water, then the pump recognize it. The main issue is really the bug with the hydroxide  addressed yesterday.

**Comment by petrolpark** [comment]
This was likely due to #303, which was fixed in 1.0.
