### ISSUE TITLE
problems with vat pressure/vacuum

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#254]
while trying to remove all gases (in this case air) from a vat using a pump, there is a temperature drop but increate in pressure to about 101.0k, causing the air to liquify. when removing the liquid air with a pipe on the bottom, it´s possible to have no molecules on the vat, making it start to have problems while receiving liquids or gases, like LPG. The LPG gases just either don´t enter or dissapair, making it impossible to have a air free vat for more eficiency. 

something to add: ammonia isn´t soluble in water in the vat, not making it possible to extract a solution from it. when the gaseous mixture is added to a refrigestraytor, it will indefinidelly run without the need to add more refrigerant. consuming something like 0.001 moles only to start working.

**Comment by petrolpark** [comment]
Duplicates of #239 (fixed in 0.7) and #220.
