### ISSUE TITLE
Can't mix cream with skinned milk in a storage tank

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#256]
I was trying to make butter, and to mix the ingredients in the right order (400 mB cream with 100 mB skinned milk), i linked a 8000 mB storage tank filled with skinned milk and a 32000 mB storage tank with cream to a 40000 mB storage tank and mix them in the right ratios there. The first thing i noticed is that the skinned milk texture glitches on the pipe and becomes a Black color while flowing. After, there was no mixing in the tank, seeing that only one liquid was allowed to entre at a time.

**Comment by petrolpark** [comment]
Mixing of non-Mixture fluids can't be done in a tank - as you can see, it is a Mixing recipe, requiring a Basin, Mechanical Mixer and Refrigerstraytor.

**Comment by Phosgenick** [comment]
Sorry! I uploaded the same comment because i though i hadn't sent or
something similar. You can delete that one too!

Also, amazed by the mod, addicted to it by now!
