### ISSUE TITLE
Error when urinating in cauldron

### ISSUE THREAD

**Issue by DrSouthbound** [petrolpark/Destroy#257]
I am receiving this error within my Minecraft server whenever any player tries to urinate in a cauldron. https://pastebin.com/raw/xBCibFE0 our current mod list:
SecurityCraft
Athena-Forge
CrayfishGunMod-Unofficial
Chipped-Forge
Create
Create Big Cannons
Cupboard
Destroy
Framework-forge
JEI
Kotlin for Forge
NoChatReports
resourcefulconfig-forge
resourcefullib-forge
simpoleplanes
Create Steam and Rails
vtaw_mw-forge

**Comment by petrolpark** [comment]
Fixed in 0.7.
