### ISSUE TITLE
Problems with texture and liquid mixing in fluid tank

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#258]
I was trying to make butter, and in order to mix the right ratios of cream to skinned milk (4 : 1), i linked a 8000 mB tank full of skinned milk and another of 32000 mB of cream to a 40000 mB tank, in order to create the 4:1 mixture before aplying to the basin. The first problem i encountered was that the texture of skinned milk glitched while in the pipe, giving it a black color. Then, there was no mixing of liquids in the tank, because it only acepted one of them at a time. It would be really usefull if the mixture was made previously before adding to the basin, seeing that it would consume less space and be easier to control.

**Comment by petrolpark** [comment]
Mixing of fluids in fluid tanks is a (badly balanced) suggestion for Create, not Destroy. The texture bug will be looked into.

**Comment by petrolpark** [comment]
Texture bug has been fixed in 0.7.
