### ISSUE TITLE
[Suggestion] Compatibility between TFMG and Destroy's crude oil

### ISSUE THREAD

**Issue by ErnstVonAusterlitz** [petrolpark/Destroy#261]
Ability to use TFMG's Crude Oil in Destroy, ability to use Destroy's Crude oil in TFMG. I wanna have both of these mods but i wish you wouldn't need to make 2 separate oil rigs for each mod. Although this suggestion possibly might be achieved by writing a 3rd party compat mod.

**Comment by petrolpark** [comment]
Destroy already tags its Crude Oil as `forge:crude_oil`. TFMG does not.
