### ISSUE TITLE
[Bug] Crash when rendering tooltips in large modpack; consider using RegisterClientTooltipComponentFactoriesEvent?

### ISSUE THREAD

**Issue by unilock** [petrolpark/Destroy#262]
I'm running into a strange crash when rendering tooltips in a very large modpack: [crash-2024-02-08_08.25.51-client.txt](https://gist.github.com/unilock/4d4485c5a689738e3960bc8386f01bf7)

I think it might be related to the `@Overwrite` of `ClientTooltipComponent#create` here: https://github.com/petrolpark/Destroy/blob/8fcec92cefd2b0c65d0f86c9ef62b0647c30116f/src/main/java/com/petrolpark/destroy/mixin/ClientComponentTooltipMixin.java

As you probably already know, overwriting methods using Mixin (or anything else, really) can easily lead to incompatibilities with other mods, hence why I think it's part of the issue I'm having.

Have you considered using Forge's `RegisterClientTooltipComponentFactoriesEvent`? Likely as such:
```java
public static void registerClientTooltipComponent(final RegisterClientTooltipComponentFactoriesEvent event) {
    event.register(DestroyTooltipComponent.class, DestroyTooltipComponent::getClientTooltipComponent);
}
```
(I'm not great with Forge, so the syntax may need adjusting there, but my IDE thinks it's OK...)

That should work much better than a full `@Overwrite`.

**Comment by petrolpark** [comment]
I hadn't noticed that event. Destroy now uses it.

**Comment by tehfrecklez** [comment]
> I hadn't noticed that event. Destroy now uses it.

Is there anywhere I can get a version with that fix at the moment?
