### ISSUE TITLE
Visual errors with the vat

### ISSUE THREAD

**Issue by TheBabinator** [petrolpark/Destroy#263]
The vent model on the top of vats has some z-fighting going on when the roof isn't made of glass. Also, the vent (and gauges) on the vat will disappear when any part of the multiblock including the one with the vent but not the controller is destroyed and rebuilt. This occurs even though there are vent particles still visible coming out of where the vent used to be and the effect on the contents of the vat is still present.

I'm playing with NeoForge 47.1.98 and Destroy 0.7 with (very likely not important to this issue) other mods like JEI and Create Deco.

![image](https://github.com/petrolpark/Destroy/assets/39492647/b93fd49a-c606-4c0c-a812-c75d5b0d0210)

![image](https://github.com/petrolpark/Destroy/assets/39492647/88734a8d-1050-4e3c-8415-325c133a0750)

**Comment by petrolpark** [comment]
Both now fixed.
