### ISSUE TITLE
Deepslate nickel ore have fluorite ore tag.

### ISSUE THREAD

**Issue by materusPL** [petrolpark/Destroy#264]
As in title `destroy:deepslate_nickel_ore` have tag `forge:ores/fluorite` instead of `forge:ores/nickel`. This breaks recipes.

**Comment by petrolpark** [comment]
Fixed.

**Comment by Grath** [comment]
This is still not fixed as of 0.8, and looking at https://github.com/petrolpark/Destroy/blob/1.20.1/src/main/java/com/petrolpark/destroy/block/DestroyBlocks.java#L467 it doesn't appear to have been changed when this was marked as fixed.
