### ISSUE TITLE
[BUG] Crash with Test Tube

### ISSUE THREAD

**Issue by MrHimera** [petrolpark/Destroy#265]
Minecraft 1.20.1
Forge 47.2.20
Destroy: 0.7

The game crashes when using an empty Test Tube on a liquid in the world (water, lava, etc.)

**Comment by petrolpark** [comment]
@MrHimera I'm unable to replicate this. Are you running any other mods? By 'in world' I assume you mean the fluid blocks? Does it occur with both lava and water, or any other modded fluid?

**Comment by MrHimera** [comment]
> @MrHimera I'm unable to replicate this. Are you running any other mods? By 'in world' I assume you mean the fluid blocks? Does it occur with both lava and water, or any other modded fluid?

There was only Create + Destroy. I took a bucket of water and poured it out to create a water source. Then I pressed RMB while holding an empty Test Tube on a water source in the world and a crash occurred.

**Comment by petrolpark** [comment]
@MrHimera Could you send your debug.log when you get the crash

**Comment by MrHimera** [comment]
> @MrHimera Could you send your debug.log when you get the crash

[debug.log](https://github.com/petrolpark/Destroy/files/14303429/debug.log)
[latest.log](https://github.com/petrolpark/Destroy/files/14303430/latest.log)

**Comment by YukarinnAM** [comment]
I had a similar crash when trying to use a test tube to get liquid oxygen nitrogen mixture on a vat

**Comment by petrolpark** [comment]
Fixed in 1.0.
