### ISSUE TITLE
Suggestion:Add more guidance in Jei or elsewhere

### ISSUE THREAD

**Issue by Catchmons** [petrolpark/Destroy#266]
Some production steps are difficult to settle,such as using Centrifuge to separate fuild。You can add some automatic recipes in jei,which show the output and the requirement clearly.And the treatment methods for some substances are also unclear。
Sorry, my English is not good, there may be some expression problems :(.

**Comment by petrolpark** [comment]
I'm going to mark this as a duplicate #60, as this is one of the things that will get covered in the eventual tutorial.
