### ISSUE TITLE
Bug: Test Tubes make item frames partially transparent (and Rubidium incompatibility)

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#269]
Test Tubes that are empty or have transparent contents will make normal and glow item frames partially transparent.
![2024-02-11_18 52 34](https://github.com/petrolpark/Destroy/assets/159703972/9c03299f-f18f-422b-92f6-620b61ae9639)

**Comment by petrolpark** [comment]
The hack to make the colours of Test Tubes able to be transparent is extremely, well, hacky, and also breaks whenever Rubidium is used. It'll be reworked.

**Comment by petrolpark** [comment]
Fixed in 1.0.
