### ISSUE TITLE
Bug: Top entry in JEI's Reaction Recipes doesn't display text

### ISSUE THREAD

**Issue by FlamingKetchup** [petrolpark/Destroy#271]
When there are two entries on a JEI reaction page (with the right GUI scale and resolution), the top one of the pair falls to render text.
![image](https://github.com/petrolpark/Destroy/assets/43097488/d9091492-1b46-423d-b1e6-aa4d6a744b2b)
Tested on 0.7 with all mods except for Create, Destroy, and JEI disabled. This has been a thing for a while now (since as long as I can remember), just didn't get around to reporting it earlier.

**Comment by petrolpark** [comment]
Fixed in 1.0.
