### ISSUE TITLE
Bugs: Aging Barrel

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#283]
- The lines drawn around the edges of a block when looking at it make the edges see through
- Transparent liquids make the inside of an Aging Barrel see through
- (Issue #23 / #285 )
![2024-02-15_17 58 37](https://github.com/petrolpark/Destroy/assets/159703972/201db2b7-bf1d-482b-a313-259fac48bd5d)

**Comment by petrolpark** [comment]
Fixed in 1.0.
