### ISSUE TITLE
Bug: Pick Block Feature being buggy

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#285]
I don't know if this is a duplicate of Issue #23, but the pick block feature is buggy;
- The block picking feature does work in any way with ANFO Block, Cordite, Nitrocellulose Block and Picric Acid Block (but it works with Dynamite for some reason).
- If you are in creative, picking any Destroy Mod block when having the block already in your inventory (not in the hotbar) will create a new item instead of moving the block from the inventory to the hotbar. The block picking feature does not work in survival if the block is in your inventory (not in the hotbar).
- Issue #23 occurs to all block where block picking works, if you moved the block inside your inventory/hotbar and then tryed to pick a block (This could also the the cause of the bug above)
- Issue #23 occurs to some blocks even if you just opened and closed your inventory and tryed to pick a block (Couldn't find any consistency with this happening)

**Comment by petrolpark** [comment]
Fixed in 1.0.
