### ISSUE TITLE
Bug: Picric Acid Tablet recipe

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#287]
Recipe ID: destroy:filling/picric_acid
Pretty sure this recipe should use a Picric Acid Mixture and not a Sodium Ion Mixture.
![2024-02-16_15 51 35](https://github.com/petrolpark/Destroy/assets/159703972/590ced3c-5410-4c7f-81fb-7d78339ec926)
![2024-02-16_15 51 48](https://github.com/petrolpark/Destroy/assets/159703972/14ed1698-54f4-44c0-accc-a6443344f01b)

**Comment by petrolpark** [comment]
Fixed in 1.0.
