### ISSUE TITLE
Centrifuge Voiding Problem

### ISSUE THREAD

**Issue by YukarinnAM** [petrolpark/Destroy#290]
I noticed a problem when using the centrifuge with uneven mixtures
As i was testing the oil processes and i decided to take the next steps
Distill LPG since all compounds had different boiling points, although this didn't work, it did gave a concentrated mixture of the gases at a way lower volume (1000mb LPG to 1mb concentrated mixture), i noticed that when this was passed through the centrifuge, it pretty much got voided, as it did centrifuge it, but didn't gave anything on the outputs
I believe this might be a problem product of the fluid being handled in integers, but i understand this is for simplicity or perhaps it might as well just be a minecraft thing
Another problem with the centrifuge comes from the same thing, an uneven amount of fluid centrifuged voids a unit 
So i thought about suggesting that the centrifuge (since it centrifuge mixtures in a 2 units of mixture to 1 unit of heavy mixture and 1 unit of lighter mixture) does not begin to centrifuge until the mixture is at least 2mb and if it is uneven, that it leaves that single mb untouched

I'm quite honestly impressed by how the mod handles processes, allowing for a lot of freedom when deciding what to do or how to
Thanks for your hard work!

**Comment by petrolpark** [comment]
Yes, Minecraft stores fluids as integers, and Destroy probably won't change that. The occasional 1mB loss can be chalked up to something like residual losses or evaporation. Distillation works weirdly with gases, and is getting reworked in 1.0. That will also fix #268, so I'm going to reject this issue and close that one once the distillation changes are implemented.
