### ISSUE TITLE
Hydrogen Cyanide by Andrussow process too slow

### ISSUE THREAD

**Issue by YukarinnAM** [petrolpark/Destroy#291]
I wanted to report about the HCN synthesis from Methane Ammonia Andrussow's Oxidation not yielding any amount of it
I'm unsure if this is a problem that comes from my lack of understanding of the mod's mechanics yet but i followed the next steps
i made a glass vat to have reach the high temperature required for Andrussow's Process (2NH3 + 2CH4 + 3O2 -> 2HCN + 6H2O) which is around 1200°C (~1473K), after trying to keep the pressure close to 0 from air and adding initially a single unit of platinum powder as it is used as the catalyzer for the reaction
This resulted in Hydrogen Cyanide and Water appearing in the vat's GUI, but at 0moles
i tried having a reasonably accurate stechiometry and  adding a lot more of the catalyzer but results where futile
I have yet to try an increased pressure, as a quick check on the process in real life, there was no mention about pressure, but there were mentions about competing reaction for 700°C to 1200°C with Nitrogen, although this isn't implemented either, i would still need to try different pressures tho

And thanks again for your time, i'm truly looking forward to this mod's development, it has a great potencial

**Comment by petrolpark** [comment]
I'll bump the rate in 1.0.

**Comment by petrolpark** [comment]
Fixed in 1.0. With the current rate it would have taken something like heating the mixture to the temperature of an active supernova for millions of years to produce a single molecule of hydrogen cyanide.
