### ISSUE TITLE
Easier alcohol production

### ISSUE THREAD

**Issue by DanielSDT** [petrolpark/Destroy#293]
Currently, if you're trying to play the game in survival, it is impossible to get to crude oil, unless you get lucky. This is because you need to have made plastic to make the aging barrel for ethanol. To make plastics you need to find an oil field, to find an oil field you need an explosive, usually touch powder. For every explosive except touch powder you already need plastics, though you can find TNT as loot or in temples. So out of the options touch powder requires the least luck. The only problem is that you need ethanol to extract the iodine necessary for its synthesis.

I think there should be easier methods of obtaining ethanol. You can of course hydrate ethylene, but you would already need crude oil to obtain that. The solutions I have in mind is to either alter the recipe to not require plastic, or to create another barrel that has a chance of failing to produce ethanol, instead producing vinegar.

**Comment by petrolpark** [comment]
Yep, the plastic requirement for Aging Barrels will be removed. For now you can find Aging Barrels in Inns in Villages.

**Comment by Phosgenick** [comment]
I have found crude oil in survival by using creepers, but yeah, that took a really long time.

**Comment by petrolpark** [comment]
The oil prospecting is also being made easier, and less sloggy.

**Comment by petrolpark** [comment]
1.0 now has an easier way to make Aging Barrels.
