### ISSUE TITLE
Fatal failure when trying to make isopropyl alcohol from propylene

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#294]
To make acetone to progress in the game, it can be done either with the cumene process ( which already uses acetone to make AIBN, so no) or by oxidizing isopropyl alcohol with the magic oxidizer. When mixing pure propylene with water and sulfuric acid to catalyze the reaction, the game crashes, making create contraptions freeze or work really slowly, player has difficulty regenerating health or eating even in peaceful mode, blocks can´t be broken by hand, blaze burners can´t work because they freeze too and the reaction doesn´t happen at all. The game can come back to normal by removing the vat contents, but still no reaction happens.

Although i have had sucess with other reactions, maybe the issue is worse for potato PC´s, like mine, but still. 

I have no clue on how to progress without the acetone to make AINB for plastic synthesis and cumene process ( for more acetone).

And just for an additional note, i gave the vat more than 400 kW of heat, more that double the activation energy, and performed the reaction on all sizes and types of vat. None worked.

**Comment by petrolpark** [comment]
I've fixed that in the Dev build. As it's quite a critical bug it'll probably come in another patch before 1.0.
