### ISSUE TITLE
Suggestion: Creative Blaze Cake like item for Refrigerstraytors

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#298]
Item to make the cooling of a Refrigerstraytor infinite.

**Comment by Catchmons** [comment]
you can use Creative Blaze Cake on blaze burner

**Comment by Catchmons** [comment]
the third mode is cooling（which blaze's head is blue and its hands are still yellow）

**Comment by ToastbrotExe** [comment]
Oh, thx

**Comment by petrolpark** [comment]
The feature with the Blaze Burners is not intended, and will be fixed. Instead you'll be able to use the Creative Blaze Cake on Refrigerstrayters.
