### ISSUE TITLE
Incompatible Create Enchantment Industry

### ISSUE THREAD

**Issue by zChenX1** [petrolpark/Destroy#3]
mod list：
destroy-1.20.1-0.1.jar
create-1.20.1-0.5.1.f.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7.h.jar

Crash Report：
[Error Report-2024-1-5_18.24.28.zip](https://github.com/petrolpark/Destroy/files/13840859/Error.Report-2024-1-5_18.24.28.zip)

**Comment by petrolpark** [comment]
Should be fixed in 0.2.
