### ISSUE TITLE
Cant run on a dedicated server

### ISSUE THREAD

**Issue by koiboi-dev** [petrolpark/Destroy#30]
Crash occurs when trying to load it on a dedicated server for the first time.

It does this when creating a new world, I don't know if it works with a pre-generated world

[crash-2024-01-05_18.59.10-fml.txt](https://github.com/petrolpark/Destroy/files/13845617/crash-2024-01-05_18.59.10-fml.txt)

**Comment by petrolpark** [comment]
Duplicate of #20, will be fixed in 0.3.
