### ISSUE TITLE
Suggestions for use of redstone

### ISSUE THREAD

**Issue by YukarinnAM** [petrolpark/Destroy#301]
Usually when doing some reaction on vat, we can check temperature and Pressure gauge, and it would be great to have a way to get a rough value of them, perhaps making it so that the pressure and temperature gauges also gives a red stone signal from 0 to 16 based on how much can the vat resist (for iron at 0 being -100kpa relative to air and 16 being 100kpa relative to air)
For temperature i think it might be a little more complex as it's a way more variable value, and probably being able to configure a top and bottom value and linearly interpolate (lerp) from 0 to 16 from that would be a little too much complexity to do ingame already, but i still believe that redstone is an important aspect that has potencial for stuff like this
Another great use of redstone is in being able to have a rough value of how full a tank is

Thanks again for your time and effort!

**Comment by petrolpark** [comment]
Something like this is planned.

**Comment by petrolpark** [comment]
Implemented in 1.0.
