### ISSUE TITLE
Still problems with mercury and brine electrolysis

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#303]
The main issue about the electrolysis of  sodium hydroxide and mercury solution seems to be solved, as sodium hydroxide now can be centrifuged, but there are still some related issues, such as the mercury getting glitched after passing by the centrifuge. The glitch makes the mercury unusable for a new electrolysis, since the game assumes a volume of 1000 mB of mercury after centrifuging, but not the vat nor the basin. the only way of getting the real volume is by passing the mercury through another vat.

Also, arent we generating more chlorine than possible in the electrolysis? because we get 0,9 mols of Na with mercury and 1,8 mols of total chlorine, after makinh the sum of HCl and HClO.
(Not that i'm complaining, love some free chlorine, but also love the ozone).

**Comment by Phosgenick** [comment]
The ammount of missing mercury somehow ends up with the NaOH solution in the centrifuge. I am always getting 895 mB of mercury and 1105 mB of sodium hydroxide and mercury solution.

When separating the mercury from water in the solution, only 84 mB of mercury remains, making it a total of 979 mB, losing 21 in the process.

**Comment by petrolpark** [comment]
> The glitch makes the mercury unusable for a new electrolysis, since the game assumes a volume of 1000 mB of mercury after centrifuging, but not the vat nor the basin. the only way of getting the real volume is by passing the mercury through another vat.

What do you mean by this? Is the concentration of Mercury produced by the Centrifuge wrong?

**Comment by Phosgenick** [comment]
The thing is, the centrifuge always tries to split volumes in  half, but there is a bug with mercury that makes the mercury not only be the lighter liquid, but also "increases" the volume. The way it happens is after you do the reaction of 1000 mB of brine with 1000 mB of mercury, isolate the chlorine water and react the sodium amalgam with additional 1000 mB of water, you get 2000 mB of a mercury and sodium hydroxide solution. When this solution is centrifuged, the lighter liquid is 1000 mB of mercury ( the game understands it's plain mercury, not a solution), and the heavier fluid is a sodium hydroxide and mercury solution, essentially getting more mercury back. When the 1000 mB is used for electrolisis again, the game understands that it's not 1000mB, and nothing happens. When adding the 1000 mB of mercury to a vat, the volume decreses (without any reaction or external losses) to 895 mB, and when the sodium hydroxide is added, the 1000 mB become 1105 mB. Thats the first bug, the centrifuge not separating equal portions, but, if you isolate the mercury from the sodium hydroxide solution and sum its volume with the 895 mB from before, the value doesn't reach 1000 mB, making consume mercury in the process. It seems to me that the problem comes from the centrifuge not separating equal 1000 mB portions, and for some reason, deleting around 21 mB of mercury.

If needed, i can do the electrolysis again and take photos to show the values.

**Comment by petrolpark** [comment]
Having done a bit of testing it looks like centrifugation produces Mixtures which are nonsense for air pressure. Distillation is also getting an internal rejig so centrifugation will be looked at as well.

**Comment by petrolpark** [comment]
Fixed in 1.0.

**Comment by Phosgenick** [comment]
Awesome! Not to rush or anything, just out of curiosity really, what is the release date of destroy 1.0?

**Comment by petrolpark** [comment]
@Phosgenick It is difficult to say. 1.0 will not be the 'full' release (in fact it will probably still be a beta), as there's stuff planned that won't come in it, and stuff to be thought up too. It's still being decided what will end up in 1.0, so it could be a few months to the end of the year. Development is also slow at the moment, as I'm in full-time education.

**Comment by Phosgenick** [comment]
ohh boy, i will be waiting for even the 1.0 beta, since i'm looking forward for the bug correction and other patches since 0.8! Have already built all the "automated" chemical farms, just waiting for the main electrolysis patches.
