### ISSUE TITLE
Vats voiding rather than exploding, redstone reading of pressure and temperature, liquid -> mixture conversion

### ISSUE THREAD

**Issue by HenryRenYz** [petrolpark/Destroy#308]
I'm now making a modpack with Destroy and find it not so easy to play with it, especially for those in survival mode. Here I have some suggestions that could enhance our survival experience with Destroy.

1. Better vat stability
    
    This is extraordinarily important. Currently, those new to Destroy will find that whatever they do to vats they explode, without any explicit visual/vocal signal except a number in the pressure meter.

    A solution to this is adding a new block: pressure relief valve. This can be made into a special form of fluid pipe, which opens only when vat pressure goes above a customizable value.

    Another simpler solution is, when there's a gas funnel on the vat, instead of exploding, the funnel is forced to make open.

    BTW, if disabled explosion in config, the vat seems just to reset itself and eat all contents when it reaches explosion limit, without further visual/vocal signal. This can be confusing, so adding an explosion animation would be great.

2. Better vat controllability

    Ways to read temperature/pressure variable is needed for large-scale automation. Either by reading using redstone comparator, or by using interface in ComputerCraft.

3. Easier liquid conversion

    If I need air pumped in, I have to use a separate vat with funnel open to generate air. If water is needed, I need to distill it. The vat seems to accept only destroy:mixture as fluid input, this makes an automation system cumbersome and causes confusion to players.

    Things can be a lot easier if an auto conversion is made when liquid pumps into the vat. For example, when minecraft:water is pumped in, it turns into aquatic solution with 0.5M NaCl, when mekanism:sulfuric_acid(or a forge fluid tag) is pumped in, it turns into 18.7M sulfuric acid. For the reverse process, it's similar, pouring mixture into mod liquid we try to make conversion.

4. Better distillation

    Distillation to salt liquid should get solvent as distillate and salt as remaining. As the distillation goes, the concentration in remaining liquid should goes higher and higher, and eventually at the time that concentration goes above a line, and the volumn of the liquid stays above a line, the salt precipitates out and we get an item.

That's all :)

**Comment by petrolpark** [comment]
1. This will be made possible by 2, so a new block may not be necessary (though it would make things slightly easier, so will be considered).
2. This is planned.
3.  A few people have suggested the former, and this may make its way in. It will not be made possible by default to convert Destroy's mixtures back into other mods', as they rarely obey the conservation of mass. This *can* be achieved with recipes, but if one is using both Destroy's mixtures and single-chemical fluids, one is making things unnecessarily messy.
4. Distillation will not be required to be repeated, as the in the model of chemistry Destroy uses substances all boil at a single boiling point, and do not form azeotropes or have other more complicated phase interactions. That probably won't change. And Destroy doesn't currently deal with solids, but this is being considered for a future release.

I may come across harsh, but this is very useful feedback and it is very much appreciated!

**Comment by HenryRenYz** [comment]
Thanks for replying!

As for point 3, it did that most conversion don't *strictly* obey the conservation of mass. Take an example, currently in my modpack, I use create:compacting to convert mixture with proton and hydrogensulfate of concentration 9.8~10.2M to mek sulfuric acid, and use create:mixing to convert mek one back to mixture with concentration 10M. It do that we can duplicate acid by always converting 9.8M acid to get 10M back. But pratically it's inefficient. for other conversion, we can make them inefficient or unpractical for duping. If a new recipe type, for instance, "vat conversion" is available it would be a lot easier for modpack makers to glue Destroy with other mods. What it do is just simply run the above process when fluid enters the vat, without having to do an extra mixing or compacting(not elegant).

**Comment by petrolpark** [comment]
All implemented/fixed in 1.0. If you're interested in the suggestion [Badge](https://patreon.com/petrolpark/about), DM me on Discord (`petrolpark`).
