### ISSUE TITLE
Everything produced being impure

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#310]
This is something which i thought wasn't even a bug, but everything made in a vat is displayed as "impure", even distiled water. Sulfuric acid, for exemple, when made by the oxidation of sulfur dioxide and then it's reaction with water, but the game insists in calling the solution impure, even after all water is removed, Salts also suffer from this, like ammonium nitrate. i guess the game understands that dissosiation or ionization products are impurities? or something like that.

I dont know if it's because of this specifically, but test tube contents, even being the same, cannot be mixed into a basin without a mixer, and will just be displayed as two different substances.

**Comment by petrolpark** [comment]
Yes, dissociation products are marked as impurities. However, the name of a mixture has absolutely no effect on it, and this probably won't be changed. The non-mixing of Mixtures without a Mechanical Mixer is intentional (for the time being) to allow for electrolysis.

**Comment by Phosgenick** [comment]
Ohhhh, ok then! just some additional thing, i meant like not the mixing of
different substances, such as chlorine water and sodium amalgam, but equal
substances, such as getting mercury from an external vat or basin to the
electrolysis basin via test tubes, but it makes sense if they aren't the
same substances.
