### ISSUE TITLE
[Visual Bug] Wrong units for the preexponential constant, and kinetic constants of reverse reactions dont show up

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#318]
Currently JEI displays the units of the preexponential constant as mol * B^-1 * s^-1, regardless of the orders of the reactants. Also kinetic constants for reverse reactions don't appear. Also also, pressing [R] or [U] on a chemical that is part of a reversible reaction should make the reaction show up regardless of whether or not the chemical is on the left or right side.

**Comment by petrolpark** [comment]
@TheRedCrafter344 Which chemicals in reverse reactions do not show up for [R] and [U]? I observed this problem with chlorine, for example, but fixed that. (Also, would you mind giving me a hand in #284).

**Comment by petrolpark** [comment]
All fixed in 1.0.
