### ISSUE TITLE
[Bug] Weirdness with Oleum, and perhaps other reversible reactions

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#319]
When inserting sulfur trioxide and sulfuric acid in a sealed vat with no water, no oleum is formed no matter how much SO3 and H2SO4 i put in. Even after heating the vat to 1000K in case the reaction was just too slow, nothing happened. Inserting oleum into that vat however instantly fully converted it to SO3 and H2SO4. Note that the sulfur trioxide has to be inserted first. Inserting just sulfuric acid will cause part of it to seperate into SO3 and H2O, the trace amounts of H2O will then immediately ionize all the sulfuric acid (I'll make a different issue for this problem) Trying with a different heated and sealed vat, I first inserted oleum, and in this case it did not get instantly converted even though the conditions were the same. It did create a tiny amount of water though.

**Comment by petrolpark** [comment]
@TheRedCrafter344 I get oleum from 1 test tube of sulfuric acid and 1 test tube of sulfur trioxide in an unheated 1x1 glass Vat. Some other changes to how Vats work might have fixed this too, so if that exact setup doesn't give you any oleum I'll know it got fixed. I don't want to insult your intelligence, but make sure you weren't using sulfur *di*oxide, too.

**Comment by TheRedCrafter344** [comment]
It was probably fixed then since I just tested that exact setup and it didn't really give me any oleum. I did get 0.00000 moles of oleum when I inserted the sulfuric acid before the sulfur trioxide, and absolutely nothing happened when I inserted the acid after the trioxide.

**Comment by petrolpark** [comment]
That is working as intended then. Sulfuric acid can dissociate into sulfur trioxide and water, which can then react reversibly to form a small amount of oleum. Thank you for the help anyway!
