### ISSUE TITLE
Can't get the zip zap achievment

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#321]
I have already charged about five black lights trying to get it, but nothing that i did gave me the achievment.

**Comment by Phosgenick** [comment]
Also maybe the Jacked to get pumping one, tho i don't know if i have to do something else than just remove oil from the ground with a pumpjack

**Comment by petrolpark** [comment]
Were the blocks placed by hand?

**Comment by Phosgenick** [comment]
Yep, also made by myself

**Comment by petrolpark** [comment]
Fixed in 1.0.
