### ISSUE TITLE
asking if I would be allowed to start a fabric port then PR it back (or if making a architectury port would be better)

### ISSUE THREAD

**Issue by walksanatora** [petrolpark/Destroy#323]

**Comment by walksanatora** [comment]
as since this project is ARR I find myself asking permission (other licences may still require me to ask it would be a bit easier to ask)

**Comment by petrolpark** [comment]
@walksanatora Do you have Discord? If so, talk to me there, `petrolpark`.

**Comment by walksanatora** [comment]
done (I hope I got the right one. It was the only petrolpark I could find on discord)

**Comment by mrsterner** [comment]
I too would like to participate in a fabric port or arch port
@petrolpark

**Comment by walksanatora** [comment]
the tl;dr of porting to fabric/arch was "wait for 1.0 release"
