### ISSUE TITLE
The suns isn't sunning ( UV going through the glass)

### ISSUE THREAD

**Issue by Phosgenick** [petrolpark/Destroy#325]
Having chlorine solution in a 3x3x2 vat  with a glass ceailing should make chlorine, and neither day or night, no reaction was observed. Also black lights didn't generate UV too, with four of them on a glass wall didn't making any difference despite messing with HCl solubility aparently.

**Comment by petrolpark** [comment]
UV is dodgy. I'm going to close this as a duplicate, add these details to #295 and close that once fixed.
