### ISSUE TITLE
Mekanism compatibility

### ISSUE THREAD

**Issue by andrea-feather** [petrolpark/Destroy#327]
The popular Forge tech mod Mekanism has a lot of chemistry in it, and there's a lot of overlap with Destroy. Sulfur oxides and acids, chlorine products, alcohols, etc. At the moment, there's no way to, for example, use Destroy ethylene instead of Mekanism ethylene, or pump Mekanism's Liquid Oxygen into a Destroy vat and have it act as an oxidizer.

While a full one-to-one compatibility patch would likely introduce balance issues (as the chemistry in Mekanism is a lot more lax than in Destroy), compatibility between the two is still possible and interesting in my opinion. The way I'd do it is disable all Mekanism recipes that have a direct parallel in Destroy (creation of sulfuric acid via oxidation of sulfur, fermentation and distillation of ethanol), and allow the use of Destroy chemicals in Mekanism recipes. That way, the creation of chemicals is done through the more interesting Destroy methods, and then used for Mekanism's ore processing, promoting mod interoperability. Since chemicals can only be made in one way, there's no risk of synthesis-desynthesis loops causing infinite chemicals due to balance issues.

For example, to create slurries in Mekanism, you would create sulfuric acid via Destroy's pathways. Then, you could pipe it into Mekanism processors, where it could be used. Mekanism's version of sulfuric acid would be inaccessible, its recipe removed.

I was thinking about making a Kube.js script to do this myself, but because Destroy uses NBT data for everything, I couldn't figure it out.

**Comment by petrolpark** [comment]
Kube.js scripts will be easier once PR #299 is merged. I think there is at least one person currently making a Kube.js script for it, but it probably won't be a native feature. I agree that disabling most of Mekanism's processing is probably the way it would be done, which is a bit too invasive IMO.
