### ISSUE TITLE
Suggestion for Oil Deposit, Portable Fluid Deposits and Rails Addon Suggestion

### ISSUE THREAD

**Issue by YukarinnAM** [petrolpark/Destroy#328]
Oil is literally the base of most of the Destroy's mod point, as many explosives and plastic derive from oil products (Tetra Nitro Toluene for example)
So it being this difficult to find, although is it understood as realistic in some degree, it also implies having to move from place to place finding different oil deposits after the small amount run out, on the long run it would be great if oil generated instead of in a single chunk, it had a central deposit chunk and smaller deposits on the adjacent chunks, with a random varying size for the deposit
This giving more incentive for exploration and not having to either move the whole system or making long chains of pipes

This can also be fixed by having a any sort of Portable Fluid Storage, as tank lose their contents when picked up, and test tube are insignificant in volume they can have compared with the huge amounts of Fluids we have to transport

For this also comes the last Suggestion, adding some sort of compatibility with the Rails Addon so that we can also get a fluid container to be moved by train, allowing for automation and transport from far deposits of oil to a zone for it,
_And who knows maybe committing some good ol' monopoly_ on a server with the mods

**Comment by petrolpark** [comment]
@YukarinnAM 

Oil does already generate in clusters of chunks, and the way it is found is being made easier in an upcoming update.

> For this also comes the last Suggestion, adding some sort of compatibility with the Rails Addon so that we can also get a fluid container to be moved by train, allowing for automation and transport from far deposits of oil to a zone for it,
And who knows maybe committing some good ol' monopoly on a server with the mods

I'm not sure what is meant by this, as Fluid Tanks already work on trains, and can be interacted with via Fluid Interfaces.

**Comment by FoxyFox909** [comment]
> This can also be fixed by having a any sort of Portable Fluid Storage, as tank lose their contents when picked up, and test tube are insignificant in volume they can have compared with the huge amounts of Fluids we have to transport

Create: Diesel Generators adds Canisters that have this exact behavior and can be even configured and enchanted, if you are still looking for this sort of functionality in your modpack or something.

**Comment by leglegab** [comment]
I think this is intentional so that you have to use contraptions/trains to move around large amounts of fluids

**Comment by FoxyFox909** [comment]
Yep I respect Destroy/Create's decisions and it makes sense. Just providing a potentially balance-able alternative in case it was useful for what OP wanted :)
