### ISSUE TITLE
Suggestions: Better electrolyse, battery packs and pressurized gas bottles

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#329]
**Description**

- **More accurate electrolyse**: Instead of voiding anions when electrolysing a Metal Anion Solution, formation of the element form of the anions would be nice to see. For example a Ferric Chloride Solution would turn into Iron Powder (like it does already) and Chlorine (and maybe left over water).

- **Electrolyse of water**: By the addition of a little acid, water can be electrolysed into Hydrogen and Oxygen for easier creation of Hydrogen.

- **Battery packs**: Battery packs can be craft/build with diffrent components and chemicals found during a create playthrough, maybe diffrent kinds of battery packs with diffrent capacities could also be possible, depending on the materials and chemicals used craft/build a battery pack. They would either be a block which can be picked up (with a wrench) or a multiblock structure movable by putting it on a contraption. Placing a **converter block** next to a battery pack allows for dis-/charging the battery pack by turning kenectic energie into electric engerie and the other way around. Charge speed would depend on the stress (should be capped) and speed put in. Discharge would only depend on the stress consumed by a network (to not create any issues with changing the speed output via cogs, speed controllers or other means). This would be useful for getting kenetic energie to remote areas for a not permanent amount of time, for example if you found oil or if you want to set up a temporary base without having to set up an entire energie creating facility.

- **Pressurized gas bottles/barrels**: One block structure to store a small a mount (e. g. <8 Buckets or depending on the pressure) of fluids/chemicals. Pairing this feature with a block to control specific amounts of fluids/chemical transfered (#324) would allow for easier handling of chemicals in small quantities. Overfilling a pressurized gas bottle would make it explode.

**Problems [this would solve]** (on a side note: wierd name for the category)

- **More accurate electrolyse**: Easier creation of elementary halogens and other chemicals
- **Electrolyse of water**: Easier creation of Hydrogen (and pure Oxygen)
- **Battery packs**: Movable storage of kenetic energie
- **Pressurized gas bottles**: Easier handling of chemicals

User name is Toastbrot_exe btw

**Comment by petrolpark** [comment]
- Better electrolysis may come with the ongoing rewrite of the chemistry API, and as there are a few suggestions that also say this I will mark this as a duplicate.
- I have always been reluctant to add water electrolysis, as it is never done industrially in real life! I know it's just a game but I feel like its a common misconception that water is in any way a viable source of hydrogen and oxygen gases, and I don't like common misconceptions.
- Battery packs are not super relevant to what Destroy currently has. I probably won't tread too far into electricity beyond electrolysis. It's something an add-on could definitely do.
- Isn't this just a fluid tank? The Graduated Cylinder and Siphon address the other couple of features though.

Thank you for the suggestions, they are always useful to see what people want! (In future, please make separate posts for each suggestion. I don't mind if you make a hundred at once if you have multiple ideas!)
