### ISSUE TITLE
Bug/Meta: Updated issue templates for github deleted any issue if one did not store it

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#330]
**Description**

The updated issue templates for github deleted any issue you were writting, since the menu where it is stored is no longer accessable.

**Reproduce**

No longer reproducable (,I think)

**Expected Behavior**

To _not_ delete issues anyone was writting.

**System Information**

Github web page

**Additional context**

I just wrote this bug report because I was mad for github deleting my suggestion I spent one hour writting, when I left the page to look up another suggestion I was refrencing >:[ . Additionally, I wanted to test the new template for reporting bugs.

**Comment by petrolpark** [comment]
Whoops, sorry about that one.
