### ISSUE TITLE
Pumpjack problems with contraptions and schematics

### ISSUE THREAD

**Issue by ToastbrotExe** [petrolpark/Destroy#332]
**Descriptions**

1. A Pumpjack on a create contraption will remember its rotation when assembling set contraption. Turning and disassembling set contraption, the Pumpjack will always face the same direction it was assembled in.
2. If the location where the game is trying to place the Pumpjack (via a schematic or disassembling a contraption) is occupied, the Pumpjack will break and get voided.
3. Pumpjacks placed on a contraption/shown by a schematic will not render correctly.
4. Pumpjacks placed by Schematic Cannon will remember thier original orientation, even if the schematic is turned before placing it.
5. Using a schematic and Quill, not including the core block of the Pumpjack will cause wierd behaviour when placing set schematic.

**To Reproduce**

- Scan atleast the core block of a Pumpjack with a Schematic and Quill and place the schematic (Pic.1: Bug 3 appears). Turning the schematic and then printing the schematic will cause Bug 2 and 4 (Pic.2).
- Scan anything but the core block of a Pumpjack with a Schematic and Quill and place the schematic (Bug 3 appears for a couple of frames). (Turning the schematic and then) Printing the schematic will cause Bugs 2, 4 and 5 (Pic.3). Furthermore, the block(s) created by this setup are ghost block(s) (Pic.3). You can walk on the invisible block(s) and updating the ghost block(s) (e.g. by placing a block next to it) will delete the ghost block(s).
- Build a contraption with a Pumpjack attached (e.g. a minecart contraption)(Pic.4). Assemble the contraption (Pic.5). Rotate the contraption by either picking it up or moving it (Pic.6). Disassemble the contraption (Pic.7). Bugs caused: 1, 2 and 3.

**Expected Behavior**

- Rotating a Contraption/Schematic horizontally should also turn attached Pumpjacks accordingly and not void the Pumjack(s)
- Correct rendering of the Pumpjack when shown on a contraption/schematic (optional)

**Screenshots**

Pic.1: The block above the Lime Concrete was scaned by a Schematic and Quill and set schematic was centered and rotated 180°/mirrored on the Red Concrete
![2024-03-05_20 04 24](https://github.com/petrolpark/Destroy/assets/159703972/f1437d36-5bd4-4ced-8514-438d1b294fef)

Pic.2: Back: Schematic Template; Front: A Pumpjack turned 180°/mirrored and then printed by a schematic
![2024-03-05_20 04 32](https://github.com/petrolpark/Destroy/assets/159703972/104d9052-376d-4b12-a6cf-e7393cd434c4)

Pic.3: The block above the Lime Concrete was used as the template for the schematic printed on the Red Concrete. A ghost block was create
![2024-03-05_20 05 11](https://github.com/petrolpark/Destroy/assets/159703972/b5754531-7773-46fc-bf30-b4b3c9d8bc22)

Pic.4: Minecart Contraption before assembling it
![2024-03-05_20 23 14](https://github.com/petrolpark/Destroy/assets/159703972/a576941c-5e25-49aa-83a3-fec267ad07da)

Pic.5: Minecart Contraption after assembling it
![2024-03-05_20 24 31](https://github.com/petrolpark/Destroy/assets/159703972/d7550255-325a-49c2-a6b0-8efe9e361d4d)

Pic.6: Rotate Minecart Contraption before disassembling it
![2024-03-05_20 28 24](https://github.com/petrolpark/Destroy/assets/159703972/1b66bec2-6207-47ad-895c-0159632b2dd2)

Pic.7: Rotate Minecart Contraption after disassembling it
![2024-03-05_20 29 12](https://github.com/petrolpark/Destroy/assets/159703972/5ec328a9-9b95-4822-9825-19a509ae3fbf)

**System Information**

 - (Destroy version [0.8]) (Latest)
 - Create version [0.5.1.f] (Latest)
 - JEI version [15.3.0.4] (Latest)

**Additional context**

I tried to build a Minecart Contraption with Pumpjacks and power generation (Windmill) to have a portable oil rig, but if I accidentally place the contraption the wrong, I either have to pick it up again and turn it 180° (for the Pumpjacks to face the right way) or my Pumpjacks will be gone. Atfer that failure I did some digging and found the other bugs related to the Pumpjack.

This took way to long to document

**Comment by petrolpark** [comment]
The effort of documentation is very much appreciated! I'll look into these.

**Comment by petrolpark** [comment]
Fixed in 1.0. Note that if you use the Schematic and Quill in creative in the way that you've described, you'll still get a ghost block, but that is a bug with base Create (for example, try it with the non-central block of a large water wheel). If using a Schematicannon, it just won't place.
