### ISSUE TITLE
Harmful chemicals should produce an Area Of Effect when pushed out of pipe endings

### ISSUE THREAD

**Issue by egginabox0** [petrolpark/Destroy#333]
**Description**

Currently (as far as I know) pumping harmful chemicals (those with `carcinogenic`, `acutely toxic`, or `bleach` properties) out of pipes and exposing mobs and/or players to the chemicals doesn't inflict them with the chemical's respective effect or inflict damage. The central idea is that when any chemical is pushed out of a open pipe:
- If the chemical's boiling point is higher than the environment temperature (say 25*C for sake of example), the chemical may turn into a vapor, and the chemical's harmful properties are applied to any entity within `x` blocks: 
- - > x = (chemicalBoilingPoint - environmentTemp) * multiplier

- If the chemical's boiling point is below the environment temp it may remain in its liquid form; touching the liquid will give the entity its effect.
- If the chemical's freezing point is above the environment's temperature, then the chemical may freeze. Touching the frozen chemical cannot inflict its effect on the entity.

If a player is wearing the hazmat suit while in the AOE of a spilled chemical, they cannot inflict themselves with the effect.

**Problem This Addresses**

- Makes harmful chemical handling riskier -> encourages player innovation to develop safe(r) handling practices/enables players to ruin everything
- Creates new mob farm opportunities
- Enables new PvP opportunities
- Allows for a form of localized pollution, in which the players action are significantly more visible to them 

**Minecraft Username**

_No response_

**Comment by petrolpark** [comment]
That should have been a feature, but it looks like I just forgot. Implemented in 1.0, though not exactly to your specification (it assumes everything vaporises, exactly the same as if you break a tank containing Mixtures). Thanks for the feedback!
