### ISSUE TITLE
Cancer’s effect

### ISSUE THREAD

**Issue by luluthepogcat** [petrolpark/Destroy#334]
Note: all of these should be able to be disabled in config so that players that just want cancet to be a massage can enjoy the mod
Cancer will have four stages (I, II, III, IV) like normal potion effect
When an entity is cancered, the cancer will start at stage one (Cancer I), your health bar will now only have 9.5 hearts,
After a few minecraft days, if not cured, cancer will advance to stage 2, the intervral between damage will reduce, entities will gain a low level mining fatigue at night since they have less energy, drinking moonshine will pop up a message: “You don’t want to consume alcohol due to your current health state”, you will have 9 hearts in your health bar
After a few minecraft days(less than the amount of times it take to get to stage two), cancer will advance to stage 3, you will also gain weakness on top of mining fatigue, mining fatigue will be in effect during the day too, the effects’ level is higher now, you will need to take two shots of cisplatin to cure your cancer
After all that you will reach stage four, now after each minecraft day, your health bar will lose half a heart and its unhealable, mining fatigue and weakness occur at all time, at this point cisplatin wont save you, only totem of undying does, at 1 hearts, you start to feel nausea and blindness, and the next day you will die.

**Comment by petrolpark** [comment]
Even if its optional, I'm of the opinion that it would a bit insensitive to attempt to replicate the disease. It will remain harmless.
