### ISSUE TITLE
Chemlib integration

### ISSUE THREAD

**Issue by AlexBeez** [petrolpark/Destroy#336]
**Description**

Chemlib integration.

**Problem This Addresses**

Might help bridge the gap in production of certain chemicals, and would generally be a pretty fun interaction, especially since it could leverage an existing library - and thus skip some work in implementing certain elements/chemicals. 

**Minecraft Username**

Vakare_4014

**Comment by petrolpark** [comment]
Destroy already uses Forge's tag system for the elements it has (which is all a Chemlib integration would consist of). There won't be native integration with its compounds (e.g. salt) as that isn't guaranteed to be stoichiometrically consistent.
