### ISSUE TITLE
Add thermal blizz cooler variant

### ISSUE THREAD

**Issue by medsal15** [petrolpark/Destroy#34]
Thermal foundation adds a blizz, which is a cold variant of the blaze. It only makes sense that it could be used as a more efficient cooling device than a refrigerstraytor.

**Comment by petrolpark** [comment]
I'm going to close this. It's a lot of effort (checking Thermal is loaded, including (and potentially licensing) a Blizz model, redoing the Refrigerstrayer to allow multiple different mobs (or adding new blocks)), for not much more depth of the experiences of Destroy or Thermal.
