### ISSUE TITLE
Pollution doesn't do anything

### ISSUE THREAD

**Issue by GitHubBadui** [petrolpark/Destroy#341]
**Describe the bug**

I have been trying to pollute a world for hours by releasing R-11 and Chlorine into the air with mechanical pumps and breaking fluid tanks filled with R-11, yet nothing is happening even though I see with the poluttometer that I am polluting. 

**To Reproduce**

1 Build a fluid tank or vat
2. fill it with R-11
3. Use mechanical pumps \ break the tank
4. Nothing changes

**Expected Behavior**

water and vegetation getting browner, outdoor temperature rises, visible smog etc.

**System Information**

Destroy - 1.20.1,  0.8
Create - 1.120.1, 0.5.1.f
JEI - 1.20.1, 15.3.0.4

Forge

**Comment by petrolpark** [comment]
You have to relog. I’ll probably add a notice to the command that says this, as in normal gameplay pollution is hopefully gradual enough that you don’t notice between reloads.

**Comment by GitHubBadui** [comment]
Thank you!
