### ISSUE TITLE
TNT recipe not found. (Return it?)

### ISSUE THREAD

**Issue by HappyTea1** [petrolpark/Destroy#347]
**Description**

Return minecraft's recipe for TNT

**Problem This Addresses**

I add this mod to try it on survival and it's pretty difficult just as it is so [please] return the TNT recipe.
At least do that you can turn on and off the recipe on the mod options tab.

**Minecraft Username**

happyTea140905

**Comment by FlamingKetchup** [comment]
Something like this is already planned (see #232) , although it might not be vanilla TNT, but a replacement. I suggest that vanilla TNT just be renamed to something like "Crude Explosive", instead of messing up the balance and progression of other mods.

**Comment by HappyTea1** [comment]
Yeah that would be a better alternative.
Thanks for the effort you are putting into the mod. ♥

**Comment by petrolpark** [comment]
Implemented in 1.0.
