### ISSUE TITLE
Custom Vat Materials

### ISSUE THREAD

**Issue by SCsupercraft** [petrolpark/Destroy#348]
**There are two ways this could be done**

1. Allow mod developers to tag custom blocks as vat materials
2. Allow modpack developers to mark blocks as vat materials in config files

**Problem This Addresses**

This allows both mod and modpack developers to make vat materials, for mod developers this could be used to make custom types of glass that can be used as a vat material or to make their own type of casing, for modpack developers this would allow them to mark blocks as vat materials that are not already vat materials instead of waiting for the mod developer to do it themselves or for making vat materials using kubeJS.

**Minecraft Username**

SCsupercraft

**Comment by petrolpark** [comment]
This is possible (edit: already) with a tiny bit of Java. There will probably be datapack support for it coming soon.

**Comment by SCsupercraft** [comment]
> This is possible with a tiny bit of Java. There will probably be datapack support for it coming soon.

Glad to hear, can't wait for the update!

**Comment by petrolpark** [comment]
This can now be done with datapacks.

**Comment by SCsupercraft** [comment]
> This can now be done with datapacks.

Great! @petrolpark I have not seen an update on either modrinth or curseforge, when can I expect the update to be published?
