### ISSUE TITLE
JEI distilliation receipes broken.

### ISSUE THREAD

**Issue by GAMINGCHATS** [petrolpark/Destroy#356]
**Describe the bug**

When I try to ponder a ponderable item from the Create mod it says: "This text is defined in a language file."

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Ponder a ponderable item from specifically the Destroy mod.
2. See wrong text.

**Expected Behavior**

Instructions/notes on how `x` item works.

**Screenshots**

![2024-05-05_02 43 33](https://github.com/petrolpark/Destroy/assets/90594728/7b44f92a-601c-45f8-b29c-cbacef65186d)

**System Information**

You should only report issues on the latest version of Destroy. No others are supported. Include the following information:

 - Create version: 0.5.1f
- Destroy: 0.8
- Minecraft: 1.20.1
- Forge: 47.2.30

**Comment by GAMINGCHATS** [comment]
A re-launch fixed it. 
![2024-05-05_13 46 59](https://github.com/petrolpark/Destroy/assets/90594728/63a13a2e-36f5-40a0-b440-3299f4d647c5)

**Comment by GAMINGCHATS** [comment]
I'm gonna reopen this 'cause JEI is now broken? It says Mixture on everything in the following images, but isn't supposed to.
![1](https://github.com/petrolpark/Destroy/assets/90594728/d7976354-740a-4123-babd-fc0cc3f4ef6b)
![2](https://github.com/petrolpark/Destroy/assets/90594728/1aa521c2-efe0-45d1-ba84-f89dbc4cc7fa)
![3](https://github.com/petrolpark/Destroy/assets/90594728/eeb38aec-1fe2-43d6-a5d5-cc97283a2d79)
![4](https://github.com/petrolpark/Destroy/assets/90594728/97b214cb-0935-445d-8924-e93fcff832cc)
![5](https://github.com/petrolpark/Destroy/assets/90594728/166230db-cd97-4e3f-85f7-7c876f74e7fc)

**Comment by petrolpark** [comment]
The Ponder text issue is because you're in debug mode, and is intentional. The text in JEI is fixed in 1.0.

**Comment by GAMINGCHATS** [comment]
Ahh, thanks.

**Comment by GAMINGCHATS** [comment]
@petrolpark May I ask if there's an ETA on 1.0?
