### ISSUE TITLE
Cannot properly save and quit the game when a vat with an open vent is built in the world

### ISSUE THREAD

**Issue by Ainsley4Ever** [petrolpark/Destroy#362]
**Describe the bug**

When I build a vat with an open vent in a world and I try to save and quit, Minecraft gets stuck on the "Saving world" screen indefinitely. It happens both in singleplayer and on servers. It only seems to happen when the vent is open, when I close it everything works fine.

**To Reproduce**

1. Build a vat and add an open vent at the top;
2. Open the Esc menu and press "Save and Quit to Title";
3. See Minecraft get stuck trying desperately to save the game.

**Screenshots**

![2024-05-23_09 34 17](https://github.com/petrolpark/Destroy/assets/48531562/3a681e99-92e9-4ed7-b6ca-de3e22d23b10)
![2024-05-23_09 34 20](https://github.com/petrolpark/Destroy/assets/48531562/4aa1b34d-19d8-4dae-8c82-59014335b3ad)

**System Information**

I'm only using Create and Destroy, nothing else:
 - Create version 0.5.1f
 - Destroy version 0.8
 - Forge version 47.2.32

**Comment by petrolpark** [comment]
This might have been fixed by proxy with numerous internal changes to Vats in 1.0.

**Comment by petrolpark** [comment]
Fixed in 1.0. If you're interested in the beta tester Badge, DM me on Discord `petrolpark`.

**Comment by Ainsley4Ever** [comment]
Oh, thanks, but I'm fine. Can't wait to try version 1.0 when you release it :)
