### ISSUE TITLE
Way to use other mods' items and fluids in chemical reactions.

### ISSUE THREAD

**Issue by Amronos** [petrolpark/Destroy#363]
**Description**
I saw that reactions will be data driven in 1.0 and so wanted to suggest this. I have thought of two ways to do this:
1. Recipes could include a way to add items/fluids as input (alongside specifying what molecules go with it???) instead of just molecules (which I think is how it's getting done right now), and maybe the output could be done like this also.
2. There could be a way to add molecules to items/fluids in datapacks. Maybe make tags for every molecule and items could be registered into those?

**Problem This Addresses**
Would make it easier for modpack developers to add compat between different mods.

**Minecraft Username**
Amronos

**Comment by petrolpark** [comment]
Items are already possible; fluids will be possible in 1.0 with automatic fluid -> Mixture of molecule conversions whenever you pump fluids into a Vat or mix them in a Basin.
