### ISSUE TITLE
Thermal Expansion compat

### ISSUE THREAD

**Issue by Paperguide152** [petrolpark/Destroy#364]
Compatability with Thermal Expansion

Compatibility with Thermal expansion would be great because Cinnabar is way too common for the few amount of uses it has, a compatability addition could allow players to turn Cinnabar into its chemical components (Mercury Sulfide) and provide a useful fucntion for this mostly useless ore, as well as im sure there could be any number of other of good opportunities for integration

**Comment by petrolpark** [comment]
This probably won't be native to Destroy but is easy with a datapack.
