### ISSUE TITLE
Make Nitrate possible to make

### ISSUE THREAD

**Issue by AlexKimWasTaken** [petrolpark/Destroy#367]
Nitrate is currently (seemingly) impossible to obtain. JEI has no recipe for it, and there doesn't seem to be any obvious way to obtain Nitrate in nature.

The Reason this is a problem is because you need Nitrate to create "Hyperaccumulating Fertilizer", which seems to be pretty important because it appears to be the only way to obtain Platinum and Palladium.

This might already be a planned feature (making Nitrate obtainable), or I might just be stupid and Nitrate is already obtainable.

Rustcarton90290

**Comment by TheRedCrafter344** [comment]
Nitric acid in water should give nitrate. Acid dissociations don't show up in JEI for some reason. Although I think some acids just dont dissociate at all right now because some values are kind of scuffed.
