### ISSUE TITLE
Wheres the Discord?

### ISSUE THREAD

**Issue by walksanatora** [petrolpark/Destroy#369]
**Description**
we need a discord to be able to discuess the recipes (alot of them are mising from jei/emi so we cannot make a clear path)
eg: baby blue just kinda... tells you to make a solution... with people like I who lack chem knowledge... have no clue how to make

**Problem This Addresses**
lack of information and community resources

**Minecraft Username**
`walksanator`

**Comment by walksanatora** [comment]
and even if you do have chem knowledge. you have no clue what machines to use or how to connect them

**Comment by petrolpark** [comment]
https://discord.gg/6EBJ3AzbHu
