### ISSUE TITLE
Swiss army knife has trouble breaking blocks

### ISSUE THREAD

**Issue by Phanastrae** [petrolpark/Destroy#37]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

https://github.com/petrolpark/Destroy/assets/111198528/db380198-df92-4397-bbb9-e09a8d23f8fe

When attempting to mine blocks with the Swiss army knife, the mining animation flickers for around a second before working correctly.
Waiting a moment before mining prevents this issue from occuring.
The flickering also appears to increase the time taken to mine a block.

**Comment by petrolpark** [comment]
This is actually largely on account of a Forge bug (described [here](https://github.com/neoforged/NeoForge/issues/143)). Until Destroy updates to 1.20.1 or moves to NeoForge, I've included a temporary patch in 0.3.
