### ISSUE TITLE
Pollution meter bug 1.20.1

### ISSUE THREAD

**Issue by ThatOneChef** [petrolpark/Destroy#370]
Whenever I join a world and attempt to use the display bord to check pollution, it will just go to the max that fits on the bord for all 5 types of pollution.

1. Join a new world
2. Place your display board
3. Place the pollution meter
4. Link the display links to the display board
5. Power the bord and there you go

When you expand a linked display board, the amount of pollution shown goes up, even if you just spawned in.
Forge version 1.20.1 -47.2.32

Proof [https://www.youtube.com/watch?v=M-muRCHtUbQ](url) 
I have a lot of mods so this could be an incompatibility

Modpack:
Security craft 1.9.9
Blam 7.2.2
Botarium  2.3.3
cooking for blockheads 16.0.4
Create interactive 1.0.2 beta 2
Create recipes 1.2.0
Create trimmed 1.0 
Create 0.5.1.f
Create deco 2.0.2
Create new age 1.1.2
Create ore excavation 1.4.0
Destroy 0.8
Entity culling 1.6.5
Ferrite core 6.0.1
Framed block 9.2.2
Geckolib 4.4.4
Immediately fast 1.2.17
Jade 11.9.2
JEI 15.3.4
kotlin 4.10.0
marbled api 1.0.7
marbled arsenal  2.1.1
Pam hc2 crops 1.0.3
Pam hc2 food core 1.0.0
Pam hc2 food extended 1.0.3
Pam hc2 trees 1.2.0
starlight 1.1.2
Steam n rails 1.6.4
Timeless and classics zero 1.0.0 hotfix 3
Tectonic 2.3.4
Terralith 2.4.11
tfmg 0.8.0b
travelers backpack 9.1.12
Vulcarian skys 2.3.0 beta 5
voicechat2.5.15
Xaeros minimap 24.1.1
Xaeros worldmap 1.38.4

MC user: ThatOneChef

**Comment by petrolpark** [comment]
That is showing empty. The "background" is checker pattern squares and the "bar" is filled-in squares (use `/pollution` to set the pollution levels and you'll see what I mean). This is the same style for progress bar create uses elsewhere but you're not the first person this has led astray so it might get changed.

**Comment by ThatOneChef** [comment]
mb lol
