### ISSUE TITLE
Destroy crashes even if it and create are the only mods enabled

### ISSUE THREAD

**Issue by Ielaypogi** [petrolpark/Destroy#372]
**Describe the bug**

Destroy crashes my game even if only it and create are enabled

**Expected Behavior**

Minecraft opens

**System Information**

Create 1.20.1-0.5.1f
No other mods

**Additional context**

Crash report: https://paste.gg/p/anonymous/7a61c281cd6e48cf87b143f23782b81c
Debug log: https://paste.gg/p/anonymous/823b28515a02400f98e41a56ff60bdbf

**Comment by petrolpark** [comment]
Someone or something has renamed `en_us.json` to `en_US.json`. Where did you download this version of Destroy from?

**Comment by Ielaypogi** [comment]
Curseforge but ill will try to download it from modrinth

**Comment by Ielaypogi** [comment]
still doesn't work when downloaded on modrinth

**Comment by Auseawesome** [comment]
Are you using tlauncher, you seem to have a jar file being loaded that appears to be to do with this launcher, we cannot offer support for that launcher
