### ISSUE TITLE
Crashes with only create, destroy and JEI

### ISSUE THREAD

**Issue by WackelPudding48** [petrolpark/Destroy#373]
**Describe the bug**

When hovering over the items in JEI the game instantly crashes, only happens when JEI is installed, REI/EMI work

**To Reproduce**

Newest versions of all three mods as of 12th of June 2024

go into creative mode (singleplayer world for me)

Hover with your mouse over an Item in the JEI menu

boom

**System Information**

 - Create [0.5.1f]
 - JEI 1.20.1 15.3.0.7

**Pastes**

crash report: https://paste.gg/p/anonymous/6ccfcc5958e0488b9bfe3710e326117d
log: https://paste.gg/p/anonymous/bbc6dfc0c7d64e26b13b194dd8bf64c1

**Minecraft Username**

WackelPudding48

**Comment by ByThePowerOfScience** [comment]
Seconded. Looks like the latest JEI update changed the method you mixed into.

@WackelPudding48 Downgrade your JEI version to the one before the latest and it should work fine.

**Comment by WackelPudding48** [comment]
ah thank you, that helps

**Comment by petrolpark** [comment]
I'll fix this in 1.0. For now I'll put a warning about this on the Modrinth and CurseForge pages.

**Comment by petrolpark** [comment]
Fixed in 1.0. To anyone reading this before 1.0 releases, you will have to downgrade to 15.3.0.5 or earlier for now, apologies.
