### ISSUE TITLE
Iodine items being made from literal thin air

### ISSUE THREAD

**Issue by Astrochicken-B** [petrolpark/Destroy#376]
Upon pumping in or extracting fluid a 3x1x1 vat produces iodine items despite the mixture within containing no iodine. The items are only produced as long as stuff gets pumped in or out, as soon as fluid input stops the item production stops too. In my setup the items are being extracted by a brass funnel momentarily in case that matters.

**To Reproduce**

1. Construct a 3x1x1 vat. Add a side input and output for fluids and an input funnel and an output brass funnel with a chute and chest below. Add a vent on top and lock it with redstone. Lock the output funnel.
2. add 1000 mB of distilled water (55.5M H2O)
3. input a single item of iodine
4. unlock the output funnel
5. start evacuating the vat. Iodine items are being produced and extracted from the output funnel.
6. Periodically flick the vent open to refill the air. As soon as the vent is closed again evacuation resumes, and so does iodine production.

**Expected Behavior**

Iodine precipitation is limited to 1 item. Iodine in its dissolved form shows up in the vat.

**Screenshots**

![2024-06-16_15 29 48](https://github.com/petrolpark/Destroy/assets/172961780/f11fdd28-c32d-4f54-b607-05b987b64868)
The data grabbed from the vat controller block.

Mods used:

- forge 47.2.0
- create 0.5.1f
- destroy 0.8
- JEI 15.3.0.4
- create deco 2.0.1
- create crafts and additions 1.2.2
- farmer's delight 1.2.4
- railcraft reborn 1.1.1
- the ducks mod 1.2.3 (don't ask)

**Comment by petrolpark** [comment]
Fixed in 1.0.
