### ISSUE TITLE
Replace Proton with Hydronium Ion

### ISSUE THREAD

**Issue by Astrochicken-B** [petrolpark/Destroy#378]
Right now acids dissociate (like ionic compounds) into the respective anion and a 'proton' species under the effect of water. This happens regardless of the amount of water added, so even 0.1 mole of H2O can dissociate an arbitrary amount of HCl into Cl- and H+. I suggest replacing H+ with H3O+ and replace the 'water-catalyzed heterolytic acid dissociation' HA -> H+ + A- with the more realistic HA + H2O -> H3O+ + A-. This would limit the amount of acid water could dissociate in a natural way.

**Comment by TheRedCrafter344** [comment]
This will be somewhat fixed in 1.0 as the dissociation reaction will be 1st order with respect to water (rn its 0th order).

**Comment by petrolpark** [comment]
I did consider this, but water isn't the only solvent in which acids are active. Everything has a pKa, but having isolated protons simplifies the process (as otherwise, we'd have to consider the reaction between every single possible acid and every single possible base). Still, I'm open to changing this.

**Comment by Astrochicken-B** [comment]
You are right, one would have to add a protonated version of every solvent-tagged molecule out there and define a bunch more equilibrium constants. I thought this case could be ignored because I considered using acids in non-water solvents a rare occasion, but I obviously forgot about all of organic chemistry..

To fix the unlimited dissociation issue one would have to define a special type of kinetic with r~[H+]/([all Solv]-[H+]), I guess, which would make it such a special snowflake of a reaction.

One last outlandish idea I can throw out here to fix the every acid x every base issue is - acids could still dissociate into H+ and A-, but with the equilibrium very far to the left. Meanwhile solvents and other bases would react with H+ but with the equilibrium very far to the right, so that in the end you get your normal acid-solvent pKs. The H+ would act as a unstable high energy proxy to transfer between acids and bases. But I assume having two reactions with extreme equilibria going over a super low concentration intermediate could mess things up in ways, or would at least be very slow. And again - protonated solvents.

**Comment by Astrochicken-B** [comment]
Also also, you would not necessarily have to define a Ka for every acid-base pairing. You could just define a standard chemical potential for every acid and base (with an arbitrary zero point) and compute the equilibrium constant on the fly from the respective difference.

**Comment by TheRedCrafter344** [comment]
I feel like implementing this

> Also also, you would not necessarily have to define a Ka for every acid-base pairing. You could just define a standard chemical potential for every acid and base (with an arbitrary zero point) and compute the equilibrium constant on the fly from the respective difference.

using groups and generic reactions would be best, as that would allow for novel molecules to act as acids/bases if needed

**Comment by petrolpark** [comment]
> Also also, you would not necessarily have to define a Ka for every acid-base pairing. You could just define a standard chemical potential for every acid and base (with an arbitrary zero point) and compute the equilibrium constant on the fly from the respective difference.

That's exactly what pKas do
