### ISSUE TITLE
Using Swiss Army Knife on Leaves has inconsitent item drops

### ISSUE THREAD

**Issue by Phanastrae** [petrolpark/Destroy#38]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

Depending on how fast you use the Swiss Army Knife, it can cause Leaves to drop different items.

Steps to reproduce:
1) Fill an area with leaves (for demonstration, /fill ~9 ~9 ~9 ~-9 ~-9 ~-9 minecraft:oak_leaves[persistent=true])
2) Mine leaf blocks one block at a time
Blocks consistently drop Oak Leaves (as if mined by shears)
3) Hold left click on leaf blocks to mine rapidly
Excluding the first couple blocks mined, leaves now primarily drop Sticks and Oak Saplings (as if mined by non-shears)

Holding shift (to potentially attempt to use a different tool) has no effect on this behavior.
Notably, this effect does not seem to be present for some other forms of instamining ie. mining diamond ore with high haste always drops diamonds.

May be related to https://github.com/petrolpark/Destroy/issues/37

**Comment by petrolpark** [comment]
Fixed in 0.3.
