### ISSUE TITLE
Azo dyes

### ISSUE THREAD

**Issue by Astrochicken-B** [petrolpark/Destroy#380]
I haven't looked into it in detail, but Destroy's theme of petrochemistry and the abundance of nitrated compounds lines up pretty well with the area of azo dyes.  Since Minecraft's dye items have been freed of the context of what this dye has been made of those would be a wonderfully environmentally un-friendly alternative for making dyes. Vanilla dye items could be made from pressing a sufficently concentared mixture in a basin, or perhaps one could dye dyeable items by directly reacting them with a dye mixture.

I am uninformed yet what specific azo dyes could be made easily, it could well be that making the relevant compounds would require implementing too many nieche intermediate products and hence be unfeasible, of course.

**Comment by petrolpark** [comment]
This is something which has been considered and is a popular suggestion. I have researched it before and you are right about the single-use intermediates I try to avoid, and another issue is that there isn't really a good use for a more complicated way of making dyes. Perhaps something to do with making coloured plastic? I'm a fan of the idea but for now it lacks a purpose. I'm of course very open to suggestions about that.

**Comment by Astrochicken-B** [comment]
Well at least we can make yellow dye from iodine :D
