### ISSUE TITLE
Vat doesn't export dirty water after chlorine gas production.

### ISSUE THREAD

**Issue by Penta0308** [petrolpark/Destroy#384]
**Describe the bug**

Trying to pump out Dirty water after chlorine gas production in Vat doesn't work.
(Pipes show particles, but no actual transportation.)

**To Reproduce**

XYZ 1x2x1 Vat, all copper-casing except one glass (low side) with UV lamp.
Pump out the air to -80kPa.
Pump 1B of the result of chlorine side of Brine electrolysis to the vat.
Reaction happens, and there is 0.9M each of HCl and HOCl gas.
Install extraction pump to under or low side of the vat.
See error. It doesn't work.

This is the remaining Dirty water.
![image](https://github.com/petrolpark/Destroy/assets/38977908/3e99af03-e09e-4150-af27-ea657e613409)

This is block data of the vat.
`{Vat: {WeakestBlock: {Name: "minecraft:glass"}, UpperCorner: {Y: 75, Z: -217, X: -369}, LowerCorner: {Y: 72, Z: -219, X: -371}, Conductance: 3215.0f}, z: -218, HeatingPower: 0.0f, x: -369, Temperature: 297.86017f, Tanks: [{TankContent: {Amount: 1000, FluidName: "destroy:mixture", Tag: {Mixture: {AtEquilibrium: 0b, Contents: [{Molecule: "destroy:water", Concentration: 55.493755f}, {Molecule: "destroy:hypochlorite", Concentration: 6.605229E-7f}, {Molecule: "destroy:hydroxide", Concentration: 1.3724528E-4f}, {Molecule: "destroy:proton", Concentration: 1.3790601E-4f}], Temperature: 297.86017f}}}, Level: {Target: 0.5f, Value: 0.5f, Speed: 0.25f}}, {TankContent: {Amount: 1000, FluidName: "destroy:mixture", Tag: {Mixture: {Temperature: 297.86017f, AtEquilibrium: 0b, Contents: [{Molecule: "destroy:oxygen", Concentration: 16.534027f}, {Molecule: "destroy:hydrochloric_acid", Concentration: 0.8999999f}, {Molecule: "destroy:nitrogen", Concentration: 61.417454f}, {Molecule: "destroy:hypochlorous_acid", Concentration: 0.8999999f}]}}}, Level: {Target: 0.5f, Value: 0.5f, Speed: 0.25f}}], Pressure: 96509.19f, Inventory: {Size: 9, Items: []}, UnderDeconstruction: 0b, ForgeCaps: {}, id: "destroy:vat_controller", y: 73, InventoryChanged: 0b, UVPower: 100.0f, Full: 0b}`

This is block data of the extraction pump.
`{z: -218, x: -369, Network: {Size: 3, Id: -100880192737209L, Stress: 128.0f, Capacity: 256.0f, AddedStress: 4.0f}, west: {Flow: {Amount: 1, FluidName: "destroy:mixture", In: 1b, Tag: {Mixture: {AtEquilibrium: 0b, Temperature: 297.86017f, Contents: [{Molecule: "destroy:water", Concentration: 55.49375f}, {Molecule: "destroy:hypochlorite", Concentration: 1.2010414E-6f}, {Molecule: "destroy:hydroxide", Concentration: 1.3697268E-4f}, {Molecule: "destroy:proton", Concentration: 1.3818048E-4f}]}}}, Pressure: [32.0f, 0.0f]}, y: 71, Owner: [I; 323026685, 39407447, -1524758471, -962403910], ForgeCaps: {}, id: "create:mechanical_pump", Speed: -32.0f, east: {Flow: {Progress: {Target: 0.0f, Value: 0.8203125f, Speed: 0.0f}, Amount: 1, FluidName: "destroy:mixture", In: 0b, Tag: {Mixture: {AtEquilibrium: 0b, Temperature: 297.86017f, Contents: [{Molecule: "destroy:water", Concentration: 55.49375f}, {Molecule: "destroy:hypochlorite", Concentration: 1.2007981E-6f}, {Molecule: "destroy:hydroxide", Concentration: 1.369728E-4f}, {Molecule: "destroy:proton", Concentration: 1.3818037E-4f}]}}}, Pressure: [0.0f, 32.0f]}, Source: {Y: 71, Z: -217, X: -369}}`

This is block data of the destination tank.
`{Size: 1, z: -218, TankContent: {Amount: 0, FluidName: "minecraft:empty"}, x: -368, LastKnownPos: {Y: 71, Z: -218, X: -368}, Window: 1b, Owner: [I; 323026685, 39407447, -1524758471, -962403910], Luminosity: 0, Boiler: {Update: 0b, Engines: 0, Supply: 0.0f, ActiveHeat: 0, PassiveHeat: 0b, Whistles: 0}, ForgeCaps: {}, id: "create:fluid_tank", y: 71, Height: 1}`

**Expected Behavior**

Dirty water should be moved to the external tank.

**Screenshots**

![image](https://github.com/petrolpark/Destroy/assets/38977908/e1ce06da-dfdc-43e9-96f0-8309e1b282a1)

**System Information**

Minecraft 1.20.1 Multiplay
Forge 47.2.32
Create 0.5.1f
Destroy 0.8

AlmostUnified 0.9.3
Architectury 9.2.14
Caleus API 3.2.0
Canary 0.3.3
CC:C Bridge 1.6.3
Cloth Config v10 API 11.1.118
CoFH Core 11.0.0
Collective 7.57
Create Applied Kinetics 1.3.2
Create Crafts & Additions 1.2.3
Create Diesel Generators 1.2h
Create Slice & Dice 3.2.0
Create: Central Kitchen 1.3.12
Create: Connected 0.7.4
Create: Power Loader 1.5.0
Create: Steam 'n' Rails 1.6.4
Create: Structures 0.1.1
Create: Things and misc 1.0.0
Curios API 1.0.0
Embeddium 0.3.19
Ferrite Core 6.0.1
ImmediatelyFast 1.2.14
Jade 11.9.2
JAPOCA 4.4.10.15
JEARGH 1.0.3
Liquid Burner 0.5
Mekanism 10.4.6
Mekanism: Additions 10.4.6
Mekanism: Generators 10.4.6
Mekanism: tools 10.4.6
MidnightLib 1.4.2
ModernFix 5.17.0
Noisium 2.0.3
Oculus 1.7.0
Productive Bees 12.5.1
Railcraft Reborn 1.1.1
Thermal Dynamics 11.0.0
Thermal Expansion 11.0.0
Thermal Foundation 11.0.2
Thermal Integration 11.0.0
and some.

**Additional context**

Other create's fluid tank IO works well.

**Minecraft Username**

Penta0308

**Comment by FlamingKetchup** [comment]
Did you try attaching the pump directly to the vat? This might be a dupe of #233 and #237

**Comment by Penta0308** [comment]
> Did you try attaching the pump directly to the vat? This might be a dupe of #233 and #237

Thanks for your comment. I tried putting pump directly to the vat.
This is my new setup based on your suggestion.
![image](https://github.com/petrolpark/Destroy/assets/38977908/a47efebb-cce9-4688-9435-bd63d62af7eb)

It still don't work. Pipe shows animation, but tank accept nothing.

Here's block data of the pipe, connected to powered pump.
`{z: -218, x: -369, west: {Flow: {Amount: 1, FluidName: "destroy:mixture", In: 1b, Tag: {Mixture: {AtEquilibrium: 0b, Temperature: 297.78516f, Contents: [{Molecule: "destroy:water", Concentration: 55.49373f}, {Molecule: "destroy:hypochlorite", Concentration: 1.0456787E-5f}, {Molecule: "destroy:hydroxide", Concentration: 1.3194392E-4f}, {Molecule: "destroy:proton", Concentration: 1.4326937E-4f}]}}}, Pressure: [256.0f, 0.0f]}, ForgeCaps: {}, id: "create:glass_fluid_pipe", y: 70, east: {Flow: {Amount: 1, FluidName: "destroy:mixture", In: 0b, Tag: {Mixture: {AtEquilibrium: 0b, Temperature: 297.78516f, Contents: [{Molecule: "destroy:water", Concentration: 55.49373f}, {Molecule: "destroy:hypochlorite", Concentration: 1.04564915E-5f}, {Molecule: "destroy:hydroxide", Concentration: 1.3194408E-4f}, {Molecule: "destroy:proton", Concentration: 1.432692E-4f}]}}}, Pressure: [0.0f, 256.0f]}}`

**Comment by Penta0308** [comment]
It works after restarting the server and reinstalling the tank few times.
I don't know the reason...
