### ISSUE TITLE
Graduated Cylinder

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#387]
When doing a synthesis, it would be very useful to have a graduated cylinder that works a lot like a test tube but can pick up an adjustable amount of fluid. There is currently no way to precisely control the amount of fluid pumped in a vat, and this would especially make dilute solutions much easier to make.

EDIT: Someone actually beat me to this idea. Great minds think alike, I guess? 

Minecraft Username:
InternetBagel

**Comment by ToastbrotExe** [comment]
Isn't this a dupe suggestion of #324 ?

**Comment by leglegab** [comment]
I guess I missed that. Nevermind then lol

**Comment by petrolpark** [comment]
Though it was a duplicate, you seemed to come up with the idea independently too so the Badge has been added to your username.
