### ISSUE TITLE
Chorus Wine works unexpectedly when changing dimensions

### ISSUE THREAD

**Issue by Phanastrae** [petrolpark/Destroy#39]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

Using Chorus Wine shortly after entering another dimension can successfully teleport you to your previous coordinates, without changing your dimension.
For example:
- Be in Overworld at 20,20
- Enter End, arrive at 100, 0
- Drink Chorus Wine
- Teleport to 20,20 in the End

Expected behaviour: Either teleport fails completely, or teleport also switches your dimension.

Steps to Reproduce:
1) Place an End Portal in the overworld close to world origin (0,0)
2) Wait at End Portal for 20 seconds
3) Enter End Portal
4) Drink Chorus Wine (within 20 seconds)
This will teleport you to the entrance End Portal's overworld coordinates, but in the End

This effect can also work in the nether, but seems less consistent (presumably due to the general lack of safe spaces in the nether causing Chorus Wine to fail more often compared to the center of the main end island).

I have been unable to reproduce for end -> overworld portal travel. (this may be due to the end's exit end portal doing weird things with player entities due to end poem stuff?)

**Comment by petrolpark** [comment]
Well noted. In 0.3, it now just won't work. Thanks for your help!
