### ISSUE TITLE
Rendering Screen Crash When Opening a Destroy Recipe with JEI

### ISSUE THREAD

**Issue by BakedBeanEnjoyer** [petrolpark/Destroy#390]
When using JEI to find a recipe or a usage for Destroy items that require special crafting using Destroy's mechanics, the game crashes. I am using NeoForge 1.20.1-47.1.106. Note, this only happens for items/materials crafted with Destroy's mechanics.

**To Reproduce**

With JEI 15.3.08 and Destroy 0.8, using the recipe or usage feature on a specially crafted destroyed items, (ex. coal beetroot) the game will crash after 1-3 seconds.

**System Information**

Create Version 0.5.1.f
Destroy 0.8
JEI 15.3.08

Neoforge 1.20.1-47.1.106

**Additional context**

[crash-2024-07-08_15.50.25-client.txt](https://paste.mozilla.org/PmvMv4SX)
[latest.log](https://paste.mozilla.org/rNOL2LJA)

**Minecraft Username**

BakedBeanEnjoyer

**Comment by FlamingKetchup** [comment]
Known issue #373. Downgrade your JEI to 15.3.0.5

**Comment by BakedBeanEnjoyer** [comment]
Ok, I will downgrade my JEI, sorry but I didn’t see the issue.
