### ISSUE TITLE
Game crashes when right-clicking a pee cauldron with a test tube

### ISSUE THREAD

**Issue by NthPhantom10** [petrolpark/Destroy#391]
**Describe the bug**

basically when you click a pee-cauldron with a test tube, it will crash the game.

**To Reproduce**
pee in a cauldron, right click on said cauldron

**Expected Behavior**

the entire game will crash

**Minecraft Username**
NthPhantom10

**Comment by FlamingKetchup** [comment]
Duplicate of #346, use a bottle for urine
