### ISSUE TITLE
Smart Centrifuge

### ISSUE THREAD

**Issue by NthPhantom10** [petrolpark/Destroy#393]
it is a smart centrifuge. what that means (in my head) is that it is still the same input/ output system, but there is a menu you can open on the centrifuge that allows you to configure what fluids / gases come out. and then it will have a button to start the centrifuge process. and for automation you can add like a little option that automatically presses the button when fluids/gases are inputted.

this would address an issue of endlessly sorting things out slowly using a normal centrifuge, as it usually takes around 10 to 15 test tubes for a larger mixture.

~ NthPhantom10

**Comment by petrolpark** [comment]
This sort-of goes against the as-of-yet undisclosed design philosophies of Destroy. A large proportion of real chemistry is separating things from each other, and this is something I wanted to capture in Destroy (in opposition to something like GregTech where you pump in pure chemicals and get out magically-separated pure chemicals). Various additions in 1.0 make automation easier.
