### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#395]
I have some chemistry experience, so I thought I would give my suggestions! Hopefully there aren't any duplicates here. My username is InternetBagel.

**More distinction between gas and liquids:** 
There could be glass pipes that only transfer gaseous molecules. Gasses would then flow from high pressure to low pressure (or diffuse across the same pressure), no fluid pumps required. New gas tanks could store a much larger amount of gas in a small space than a normal fluid tank can. Additionally, in many cases just having gas sitting on top of a solution isn't enough for a reaction to happen, so a new bubbler block could be added that would be able to react gasses with solutions (and probably add a lot of character to the lab).

**More uses for the added metals:** 
While I think that armor/tools from a lot of these metals would be pointless, at a certain rate it's just not worthwhile to aquire more nickel or platinum. Include these metals in more crafting recipies to keep them useful as more than just catalysts.

**Better world interaction:** 
Drop a high explosive powder item on the ground and light it with a flint and steel, and it just goes up in smoke. I was hoping for a boom. If you really felt like being funny you could make it so that some of them explode when they hit the ground. Also, while I feel like adding every chemical as a fluid that can be placed in the world would be way too much, maybe make at least a few of them able to be dumped on the ground to have interesting effects. Additionally, if you are careless about your gasses, (such as letting chlorine gas leak everywhere) you should be able to see the effected area.

**Wood chemistry:** 
Wood potash would be a good way of getting nitrates, carbonates and hydroxides, and would fit well with the wood automation already in create. I would go into the reaction pathways but there doesn't seem to be a lack of chemistry knowledge in these parts.

**Better distillations:** 
Usually fractional distillations (like the bubble caps try to implement) involve huge distillation towers. Think Create: TFMG. Smaller distillation setups usually involve glass water cooled condensers (which would be some glassware to get setups looking more laboratory looking). Small distillation setups could have each product come over at different tempuratures (better for small batches), and large (more expensive) distillation tower multiblocks can have many/all products each at a different level of the tower (better for industrial synthesis).  Another little nitpick that I have is that I would like to see my solution bubbling when the distillation is working.

**Make pollution local:**
A big thing I would say needs changing is that pollution is global. To be forward, this is a bad idea (in my humble opinion). One dingus could just dump chemicals into the air and now everyone on the server has to deal with the very punishing consequences. The dingus in question should feel the consequences, not everyone else. The solution should not be just to disable pollution because then a bunch of items are now useless. Just make pollution pollute the local area and everyone is happy (except for the dingus).

**Make more ways to curb pollution:**
There should be better ways for dealing with chemical waste. One good idea is a flarestack that can be used to burn hazardous waste into less hazardous gasses to float away. Solid salts will also help with this, as instead of having to pump waste into a large fluid tank, waste can be turned into salts and packed away neatly. I feel another important thing about this mechanic is that every form of pollution should have some kind of active way to reverse it (not just waiting for it to go away).

**More PPE:**
I think the PPE should be a bit more tiered. A pair of gloves, a labcoat, and goggles are enough to hold a test tube of acid. The hazmat suit is approriate for cyanide, but needs an upgrade for hydrazine. Adding proper ventilation (perhaps in the form of a fume hood or encased fan) could also reduce the hazards of a lot of chemicals. The fume hood could also be used for collecting gasses for use in reactions. For example, instead of having sulfur turn into SO2 the instant it goes into a vat with air in it, perhaps the sulfur needs to be blasted with a lava fan and the resulting SO2 that escapes can be captured with the fume hood (better world interaction too).

**More glassware:**
This one is rather vague, but I'd like to see more chemistry glassware wherever possible. There's a huge variety and a lot of it looks pretty interesting. Even as decoration, I still think it would be nice to have around the lab. More decoration in general (still within the whole steampunk aesthetic) would also be a neat addition.

**Small chemistry nitpicks**
In the production of a voltaic pile, I think each cell needs some kind of electrolyte between the two. I don't think just water would work. Also, it'd be nice to see more possible voltaic cells other than copper/zinc. One last thing is that most people know methylamine as that one chemical from Breaking Bad. I feel like it needs a spot somewhere in the baby blue synthesis.

That's all I have for now. I can specify things better if needed too, just ask! I'd also be happy to help code what I can. Excited for 1.0!

**Comment by FlamingKetchup** [comment]
**Gases:**
Having some differentiation would be interesting, but I feel like most of this is pretty irrelevant to the core of Destroy. It seems like  trying to make handling gases more realistic, but fluid handling in Create is already fairly unrealistic. Liquids already don't obey pressure, and already are able to be jammed into tanks at a 16 buckets to 1 block ratio, despite 1 bucket equaling 1 block.
**Distillation:**
Integration with TFMG distillation is planned. Larger scale generic distillation is intended to be performed with vats.
**PPE:**
Tiering is something that Create tries to avoid. Is needing to upgrade your stuff to protect against hydrazine part of some meaningful progression? Right now with how venting works, being extremely local to the vent and not long term, hazmat is already more aesthetic than useful. 
**Ventilation:**
Same goes for ventilation. It could be interesting if venting chemicals was more dangerous, but I think suggestions regarding this would need to be coupled to be meaningful.
**Electrochemistry:**
I *think* voltaic piles are temporary. There are plans for more complex electrochemistry.
**Methylamine:**
Methylamine does have a secret use already

**Comment by petrolpark** [comment]
Most of what @FlamingKetchup has said is true. 

**Gases**
Destroy currently doesn't follow rules about phases - everything is miscible, for instance, and this will probably not change. Something like a Bubbler is an idea I had, however (for instance, for making carbonated drinks). It won't be in 1.0 though.
Likelihood: 🔴 (Aspects are) unlikely

**More uses for metals**
Coming in 1.0
Likelihood: 🟢Already implemented

**More interaction for explosives**
High explosives almost by definition are difficult to explode. Contact explosives do already exist in the form of Touch Powder. A slightly better way of displaying dispersed gases is also planned, which would make the Hazmat Suit and PPE 
mentioned below more useful.
Likelihood: 🟠 Possible

**Wood chemistry**
This is a good suggestion. I will look into it.
Likelihood: 🟢 Likely

**Better Distillations**
What FlamingKetchup said is about right. Bubbling mixtures in Vats is also planned.

**Local Pollution**
I have been working on this today.
Likelihood: 🟢 Being implemented

**More ways to curb pollution**
This is planned, both through reducing initial pollution and removing pollution after the fact.
Likelihood: 🟢 Likely

**More PPE**
While what FlamingKetchup said is true, as they are not strict tiers this is still something I'm planning, and work has been done in 1.0 to facilitate this. 1.0 adds a bit more chemistry "merch" (including the glassware you suggest below) and as a continuation of that I am intending to add lab goggles and a lab coat (maybe another). If not in 1.0 then definitely at some point. As mentioned before, I do intend to make the protective equipment actually important.
Likelihood: 🟢 Likely

**More glassware**
Likelihood: 🟢 Definite

**Voltaic pile**
It is indeed temporary, as it doesn't have any real uses. I only added it in 0.0 because the Dynamo didn't really have anything to do and I needed something to put in the Ponder. Both the Dynamo and Voltaic Pile are in a tumultuous place.

**Comment by TheRedCrafter344** [comment]
There's a create addon in development that will afaik implement pressure mechanics for fluid pipes, so integration with that could be doable when (if) it releases.

**Comment by leglegab** [comment]
@petrolpark 
I think PPE should be about alternatives and not just flat tiers. Here's more what I had in mind. Take any good ideas you find.

**Labcoat/Goggles**
Cheap to make as mosty wool coat along with potentially just using the standard create goggles instead of new chemistry ones. New chemistry goggles would also work fine though as long as their cheap. Should be enough not to get poisoning from most common chemicals. Both won't take damage unless you get hit while wearing them.

**Hazmat Suit**
When it comes to very toxic gasses and very hazardous substances, this is the place for the hazmat suit. The gas mask would slowly take damage while it protects you, and the gas mask will leave a slight border around your HUD (like pumpkins do except wayyy less dramatic). A gas mask curio would also be a good addition for protection against just toxic gasses.

**SCAPE (Self Contained Atmospheric Protective Ensemble) Suit**
An alternative the the hazmat suit in many cases, but could be required for the nastiest chemicals in the mod such as hydrazine. Instead of losing durability, the suit would instead consume compressed air from a backtank over time. The suit would also not protect against gasses unless the whole suit is worn. This suit would also be significantly more expensive than the standard hazmat suit and would be extremley cumbersome to wear, giving slowness to the user.

**Comment by petrolpark** [comment]
A lot of the things in the original suggestion have now been implemented (except wood chemistry; make a new issue if you're super keen. Also put one suggestion per post in future, thank you!).
