### ISSUE TITLE
Compatibility issues with JEI 15.3.0.8 and Integrated Terminals

### ISSUE THREAD

**Issue by PTALTS-LK** [petrolpark/Destroy#396]
**Before submitting a bug report, ensure you are familiar with the [rules](https://github.com/petrolpark/destroy/issues/1).** Do not include this line in the bug report.

**Describe the bug**

```
❯ ls
CommonCapabilities-1.20.1-2.9.1.jar  IntegratedDynamics-1.20.1-1.22.1.jar
create-1.20.1-0.5.1.f.jar            IntegratedTerminals-1.20.1-1.4.15.jar
CyclopsCore-1.20.1-1.19.2.jar        IntegratedTunnels-1.20.1-1.8.28.jar
destroy-1.20.1-0.8.jar               jei-1.20.1-forge-15.3.0.8.jar
IntegratedCrafting-1.20.1-1.1.7.jar
```

When using mods from the list of mods above, opening the storage terminal in Integrated Terminals and then moving the cursor to the right panel of JEI will cause the game to crash

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Install Minecraft 1.20.1 with NeoForge 47.1.106
2. Install the mods from the above list
3. Launch the game, create a new world and enter
4. Build a structure as shown in the screenshot below (chest, Storage Terminal, Logic Cable, Item Interface)
![2024-07-11_15 26 35](https://github.com/petrolpark/Destroy/assets/62936489/e65f27dc-b82c-4ed2-a403-477772be50db)
5.Open the storage terminal and move the mouse to the right side of the JEI item list

**Expected Behavior**

Does not crash the game

**Screenshots**

NONE

**System Information**

You should only report issues on the latest version of Destroy. No others are supported. Include the following information:

 - See list above

**Additional context**

I first reported this issue to the issue tracker on jei, and then troubleshooting found that it was a Destory issue
https://github.com/mezz/JustEnoughItems/issues/3569

**Minecraft Username**

NONE

**Comment by petrolpark** [comment]
Can you attach the debug.log and crash report please?
Also, JEI 15.3.0.8 is not supported until 1.0. You will have to downgrade to 15.3.0.5.

**Comment by PTALTS-LK** [comment]
> Can you attach the debug.log and crash report please? Also, JEI 15.3.0.8 is not supported until 1.0. You will have to downgrade to 15.3.0.5.

[debug.log](https://github.com/user-attachments/files/16203168/debug.log)
[latest.log](https://github.com/user-attachments/files/16203167/latest.log)
[crash-2024-07-14_02.11.48-client.txt](https://github.com/user-attachments/files/16203169/crash-2024-07-14_02.11.48-client.txt)

**Comment by petrolpark** [comment]
Yes, this is due to you using a version of JEI which is not supported. You will unfortunately have to downgrade to JEI 15.3.0.5 until Destroy 1.0 releases.

**Comment by mezz** [comment]
@petrolpark please change your mixin to fail gracefully when JEI's code changes, I receive a lot of reports like this one.

You can set this inject to `require = 0` so that it will just stop working instead of crashing the game.
https://github.com/petrolpark/Destroy/blob/1.20.1/src/main/java/com/petrolpark/destroy/mixin/TooltipRendererMixin.java
Ideally you can make a log if there's a problem, so people can report the issue to you.
