### ISSUE TITLE
Threshold Compatibility With Vats

### ISSUE THREAD

**Issue by stanlabs** [petrolpark/Destroy#398]
**Description**
The Create Mod Threshold switch should be incorporated to work with the vats. This should allow users to set the upper and lower limits of a target pressure or temperature, which would activate redstone signals similar to how a threshold switch works with storage capacity. This would allow users to set up systems to maintain and regulate temperature/pressure, which can allow for greater automation.

**Problem This Addresses**
This enables greater ability to automate certain chemical processes.

**Minecraft Username**
Stanlabs

**Comment by petrolpark** [comment]
This functionality for temperature and pressure has been added just by making thermometers and barometers give a redstone signal. I will probably look into the threshold switching giving a signal based on the fullness of the Vat.

**Comment by stanlabs** [comment]
@petrolpark How does it work? Does it output a certain power for different ranges of temperature and pressure?
