### ISSUE TITLE
Looking at other mods for explosive tools and entertainment

### ISSUE THREAD

**Issue by Barerock** [petrolpark/Destroy#401]
**Description**
I suggest adding a number of different explosives that scale with the ability to mass produce and the need for large area clearing, and for PvP related things if people want that. A set of tool based area clearing explosives would be amazing to have, and in the case of mass obliteration, it'd be useful or at least entertaining to have access to extreme area annihilation explosives. These can use your chemistry system, but for unrealistic yields with few consequences, some can use Refined Radiance or nether stars. You get the idea.

Looking to the old school ballistic mods like ICBM could help with some ideas, but staying away from the red matter and black hole stuff is very much desired for this suggestion. Sticking with the spirit of this mod is paramount.

**Problem This Addresses**
The explosives marked for removal are neat and all, but MC is sorely lacking good explosives mods. OppenMiner is really the only real contender right now and it's nigh perfect for what many people want, except it's not really an MC mod but rather a war conversion? Simply put, MC doesn't have enough mass destruction capable tools or mods that fit into generic modded minecraft. Mekanism has one, but what about Create?

This is certainly on the list already, but hopefully this offered some places to look for inspiration.

**Comment by petrolpark** [comment]
Explosives have been redone in 0.1.0, hopefully helping with whatever it is you want. As this is a very vague suggestion I'm going to close it.
