### ISSUE TITLE
Villager Trade

### ISSUE THREAD

**Issue by ExpertFaun11492** [petrolpark/Destroy#402]
**Description**
Right now some chemical ingredients are uncraftable. if it even became craftable, it is so complex and blow my mind.
If there is some kind of villager(i ll call this job "Chemist") to sell some catalysts(etc:AIBN) or items like explosives or stimulants it ll be a lil bit easier for those who not good at chemicals to play this mod.

Job:Chemist
Occupation Block:Vat Controller(or something better)(maybe BubbleCap? suggestion by renegade4339)
What They Trades:Emerald and test tubes to catalysts、Emeralds to explosives, Materials to emeralds

**Problem This Addresses**
to make chemical synthesis a bit easier for beginners

**Minecraft Username**
ExpertFaun11492

**Comment by petrolpark** [comment]
If this were to be implemented, it would be in a way that requires you to have synthesized the chemical yourself first. The complexity of crafting certain materials is the entire core of the mod.
