### ISSUE TITLE
Village: Guidebooks and a laboratory structure

### ISSUE THREAD

**Issue by Renegade4339** [petrolpark/Destroy#403]
**Description**

There should be a (small) laboratory structure in the village and very rarely it in itself alone (large) anywhere in the overworld housing bubble caps and/or vats, both of different sizes. Both the lab variants should also be a guide for beginners on Destroy, containing different loot from the mod, and housing the elusive guidebooks to Destroy. As for the book itself, it should have multiple book items tacking different aspects of destroy, which should encourage on exploration. Adding to #402, labs should also house chemist villagers.

**Problem This Addresses**

This should tackle the problems of actually using the mod itself especially for non-chemists and some little exploring 

**Minecraft Username**
BenitezClance4

**Comment by petrolpark** [comment]
The tutorial will not be done with a mere book. A lab structure is probably going to come, but not in the way you think.
