### ISSUE TITLE
Adding Destroy To Custom Modpack causes game to crash after loading world

### ISSUE THREAD

**Issue by EvilDarkSoul** [petrolpark/Destroy#404]
**Describe the bug**
Once mod is added to custom modpack game crashes 30-60 seconds of loading into a world.

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Unknown

**Expected Behavior**

Game to not crash when destroy is in modlist

**Screenshots**

**System Information**

 - Minecraft 1.20.1
 - Forge 47.3.0

![Screenshot from 2024-08-05 17-11-51](https://github.com/user-attachments/assets/16021c7b-d2d6-4c6b-9efb-96d5ce5e0117)
![Screenshot from 2024-08-05 17-12-01](https://github.com/user-attachments/assets/d26db3a1-a1f3-422d-9342-e5a70d878cab)
![Screenshot from 2024-08-05 17-12-11](https://github.com/user-attachments/assets/ebb4302e-b5d0-4372-ae4b-e64d779b206d)
![Screenshot from 2024-08-05 17-12-15](https://github.com/user-attachments/assets/52a7ebcf-cb7a-41fa-8e13-55e96339931e)

**Additional context**

https://paste.gg/p/anonymous/673b432ad8484d088b36ba8adbce95b7

**Comment by metalmint** [comment]
There is an incompatibility with the latest version of JEI (15.3.0.8), downgrading to 15.3.0.5 should clear everything up
