### ISSUE TITLE
Centrifuge speed

### ISSUE THREAD

**Issue by Astrochicken-B** [petrolpark/Destroy#406]
Is it intentional that the centrifuge takes exactly 5 seconds to process a recipe (and for milk 25 s), regardless of RPM? A RPM speed scaling like with vanilla Create machines would make sense in my oppinion. Alternatively, if constant speed is intentional, I would suggest a minimum speed requirenment, like with the mixer. (Or why not have both?)

**Comment by petrolpark** [comment]
Fixed in 0.1.0 snapshot 9.
