### ISSUE TITLE
Crash when opening the vent on a vat, and general shenanigans with vacuums

### ISSUE THREAD

**Issue by coolbot100s** [petrolpark/Destroy#41]
Apologies if this should be two issues as this seems to be an unrelated bug that led to the crash.  
In any case, here are the steps to recreate.

Step one: Create a vat and pump all air out of it, creating a perfect vacuum.  
![javaw_Ba9v0JIVTa](https://github.com/petrolpark/Destroy/assets/76798835/e6318f48-41b9-49af-a819-1550a0e35778)

Step two: 
Pump in an unknowable amount of Ethelyne.  Unknowable because once some was pumped in, the vat was unsure of how many moles it contained, and the liquid container info was also inconsistent, bouncing between the four frames shown below.   
In this state, no more chemicals or fluid can be added or removed via mechanical pump.
![javaw_QBMJBCpSCH](https://github.com/petrolpark/Destroy/assets/76798835/88228090-d4f7-47fd-9ae3-51754cfe404c)
![javaw_KWqotCkcm8](https://github.com/petrolpark/Destroy/assets/76798835/8155364d-ac39-48bc-bfe1-099a7a6f72b9)
![javaw_1bwfSNtb4q](https://github.com/petrolpark/Destroy/assets/76798835/784853b5-8505-48c2-b098-b9587d2a03cc)
![javaw_EoTIFKiAtP](https://github.com/petrolpark/Destroy/assets/76798835/ee6806fa-4ee6-4f00-8b35-e7ba01d8e5cd)

Step three: 
Use a mechanical wrench on the top of the vat to create a vent, this immediately crashes the game.  
crash report:  https://mclo.gs/vAjmJEv

**Comment by petrolpark** [comment]
This will be looked into and fixed in 0.3. As you've been very helpful with submitting lots of fleshed-out bug reports, if you want message me on discord (`petrolpark`) and I'll give you the **Beta Tester** Badge.

**Comment by petrolpark** [comment]
Fixed in 0.3.
