### ISSUE TITLE
Chlorine and Hydrofluoric Acid Densities Incorrect

### ISSUE THREAD

**Issue by Mo1eculeMan** [petrolpark/Destroy#415]
**Describe the bug**

Diatomic chlorine (Cl<sub>2</sub>) and hydrogen fluoride (HF) have incorrect liquid densities (3.2 g/B and 1.1g/B respectively). These are their densities at STP, where both of these exist as gases. Because of this, condensing Cl<sub>2</sub> or HF in a vat often causes the vat to explode due to a rapid increase in incompressible liquid volume.

**To Reproduce**

See above. Viewable in JEI.

**Expected Behavior**

Cl<sub>2</sub>'s liquid density should be at or around 1562.5 g/B and HF's liquid density should be at or around 990 g/B.

**Minecraft Username**

Mo1eculeMan

**Comment by petrolpark** [comment]
Fixed in 0.1.0. It was also true of Carbon Dioxide and R-22.
