### ISSUE TITLE
Exothermic Reaction Description Typo

### ISSUE THREAD

**Issue by Mo1eculeMan** [petrolpark/Destroy#417]
**Describe the bug**

JEI mouse-over description of exothermic reactions is incorrect.

Description reads: **Exothermic reactions produce heat. They are the opposite of exothermic reactions.**

Second sentence should have "endothermic", not exothermic.

**Screenshots**

![exothermic](https://github.com/user-attachments/assets/383adc2e-599a-4f80-b175-4190bf66cf35)

**System Information**

 - Create version 0.5.1.f

**Comment by Auseawesome** [comment]
This has been fixed on the github in commit 24f0924891545dc43b0f0da6c25744d55602fa70 as I've just been working with the lang files. This change must not be available in builds on curse/modrinth yet.
