### ISSUE TITLE
Vats can not be moved by contraptions

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#419]
If you extend a mechanical piston (with plenty of extension poles) into a vat it will just punch a hole straight through the vat. However, the vat will not disassemble unless you break the block(s) pushed by the piston. 

Doing this glitch its actually possible to make a vatless vat where all the vat solution just stays behind after you push all the vat blocks elsewhere. You can also use this glitch to go inside the vat which is also pretty funny.

The vat should probably work the same way a fluid tank does, where it all moves as one unit when pushed for easy transport and etc.

**Comment by petrolpark** [comment]
Fixed in 0.1.0.
