### ISSUE TITLE
Crash when closing the vent on a vat

### ISSUE THREAD

**Issue by coolbot100s** [petrolpark/Destroy#42]
Crash Report: https://mclo.gs/kuBjTC4  

I created a 1x1 glass vat, similar to the one below, and placed a dried kelp in the vat from above with a brass funnel, I then removed the funnel to open a vent on the top of the vat and pumped ethanol in from the side, once full I realized I could no longer see my kelp so I went to close the vent, causing a crash.  
Weirdly, after reloading my world I had to destroy and replace not only the vat controller, which now read as invalid, but each wall of the vat as well.  Before replacing the vat the mechanical pump still reached inside the glass on the back as if it was still a part of a valid multiblock.
![image](https://github.com/petrolpark/Destroy/assets/76798835/8f39f546-91d0-468a-887f-f5b74ee57367)

**Comment by petrolpark** [comment]
Fixed in 0.3. If you want that Beta Tester Badge, be sure to DM me on Discord (`petrolpark`)!
