### ISSUE TITLE
Large coaxial cogwheel

### ISSUE THREAD

**Issue by SCsupercraft** [petrolpark/Destroy#420]
This bug report is for [Petrol's Parts](https://modrinth.com/mod/petrols-parts) but since there is no place for me to report bugs for Petrol's Parts I am reporting it here. (The report issues button on the mods page either links to a private or non-existent repository)

**Describe the bug**

The large coaxial cogwheels shaft appears even when there is not a shaft.

**Expected Behavior**

The shaft should not show until one has been placed through the large coaxial cogwheel

**Screenshots**

![image](https://github.com/user-attachments/assets/f5075bd1-a0b9-4dae-8b11-ad5465aaad46)

**System Information**

 - Create version 0.5.1f
 - Petrolpark's Library version 1.0.1
 - Petrol's Parts version 1.0.0

**Minecraft Username**

SCsupercraft

**Comment by petrolpark** [comment]
Fixed in 1.0.1. I had also forgotten to make the Petrol's Parts GitHub public; that's been rectified now.
