### ISSUE TITLE
Double cardan shaft

### ISSUE THREAD

**Issue by SCsupercraft** [petrolpark/Destroy#421]
This bug report is for [Petrol's Parts](https://modrinth.com/mod/petrols-parts) but since there is no place for me to report bugs for Petrol's Parts I am reporting it here. (The report issues button on the mods page either links to a private or non-existent repository)

**Describe the bug**

The game consistently crashes when placing a double cardan shaft

**Screenshots**

![image](https://github.com/user-attachments/assets/62d987c1-973f-4032-9145-80fe2e857f27)

**Additional context**

[crash-2024-08-28_13.01.24-client.txt](https://github.com/user-attachments/files/16783097/crash-2024-08-28_13.01.24-client.txt)
[debug.log](https://github.com/user-attachments/files/16783120/debug.log)

**System Information**

Create version 0.5.1f
Petrolpark's Library version 1.0.1
Petrol's Parts version 1.0.0

**Minecraft Username**

SCsupercraft

**Comment by SCsupercraft** [comment]
After further testing the same happens with the planetary gearset, as for the differential it doesn't just crash you the once, but every time you go near a differential causing you to lose your world if you can't edit your player data to move you away from it.

**Comment by petrolpark** [comment]
Fixed in Petrol's Parts 1.0.1.
