### ISSUE TITLE
Colossal Cogwheel Ponder broken

### ISSUE THREAD

**Issue by rmart1n-dev** [petrolpark/Destroy#422]
This bug report is for Petrol's Parts, as the "report issues" button on Modrinth leads to a 404 on Github.

The ponder for the Colossal Cogwheel is broken. Although the other cogwheels and effects appear, the colossal cogwheel itself does not.

![Screenshot 2024-08-28 at 5 00 37 PM](https://github.com/user-attachments/assets/dc648a5e-cab8-45e2-b54e-2660edc4826f)
![Screenshot 2024-08-28 at 5 00 32 PM](https://github.com/user-attachments/assets/95b00fef-a7f0-4b04-a4ff-58a5516410ba)

Running only Create, Petrol's Parts, and Petrolpark's Library.

**Minecraft Username**

RDawgNYC

**Comment by petrolpark** [comment]
Fixed in Petrol's Parts 1.0.1.
