### ISSUE TITLE
Colossal Cogwheel Interior Cogs

### ISSUE THREAD

**Issue by rmart1n-dev** [petrolpark/Destroy#423]
This is a bug report for Petrol's Parts, as the Modrinth "report issues" buttons leads to a Github 404.

Placing a small cogwheel, vertically oriented, in the center of a Colossal Cogwheel makes the small cogwheel spin. This is most likely a bug, unless I'm mistaken.

https://github.com/user-attachments/assets/b5b0cd78-963d-4836-85eb-2f4830eab82b

**Minecraft Username**

RDawgNYC

**Comment by petrolpark** [comment]
Fixed in Petrol's Parts 1.0.1.
