### ISSUE TITLE
Vat causes game crash

### ISSUE THREAD

**Issue by TheArinav** [petrolpark/Destroy#424]
**Describe the bug**

Game crashes after attempting a chemical reaction in the vat. It seems like that for some reason, the vat attempted to explode itself, instead resulting in a game crash.

**To Reproduce**

- Create a vat.
- Pump in some ammonia
- Insert rhodium powder via a funnel
- continue pumping in ammonia until the game crashes. 

**Expected Behavior**

According to the log, it seems that the vat was supposed to explode for some reason, but the explosion source was null.

**Screenshots**

![2024-08-29_13 00 08](https://github.com/user-attachments/assets/1317ae11-7d9e-4382-94a1-9f1787b82b93)

![2024-08-29_13 00 19](https://github.com/user-attachments/assets/7c024d11-d3b3-4d4c-8129-61058460a437)

![2024-08-29_13 00 25](https://github.com/user-attachments/assets/2636699d-4d01-420c-81a5-57c01bebaf02)

**System Information**

 - Create version 1.20.1-0.5.1.f
 // This happened in a fairly large modpack, Below are all of the mod files installed
Apotheosis-1.20.1-7.4.2.jar
'Apothic Amendments - Enchanting - 0.1.4.jar'
'Apothic Supplementaries - Enchanting - 0.1.2a.jar'
ApothicAttributes-1.20.1-1.3.7.jar
ApothicCombat-1.20.1-1.1.0.jar
'Armor of the Ages-forge-1.20.1-1.2.1.jar'
BiomesOPlenty-1.20.1-18.0.0.592.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
Botania-1.20.1-446-FORGE.jar
Chipped-forge-1.20.1-3.0.6.jar
Clumps-forge-1.20.1-12.0.0.4.jar
CodeChickenLib-1.20.1-4.4.0.512-universal.jar
Corgilib-Forge-1.20.1-4.0.3.0.jar
Crystal-Clear-2.1-Beta-forge.jar
DarkUtilities-Forge-1.20.1-17.0.3.jar
DungeonsArise-1.20.x-2.1.58-release.jar
EnchantingInfuser-v8.0.3-1.20.1-Forge.jar
EnderStorage-1.20.1-2.11.0.188-universal.jar
Enhanced_Celestials-forge-1.20.1-5.0.0.4.jar
Estrogen-4.2.10+1.20.1-forge.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
FarmersDelight-1.20.1-1.2.4.jar
FluxNetworks-1.20.1-7.2.1.15.jar
Icarus-NeoForge-2.9.2.jar
Incendium_1.20.x_v5.3.5.jar
InsaneLib-1.13.5-mc1.20.1.jar
L_Enders_Cataclysm-1.99.6-1.20.1.jar
MobsOfSins-v0.2.jar
MutantMonsters-v8.0.7-1.20.1-Forge.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
OctoLib-FORGE-0.4.2+1.20.1.jar
Oh-The-Biomes-Weve-Gone-Forge-1.1.2-Beta.jar
Oh-The-Trees-Youll-Grow-forge-1.20.1-1.3.0.jar
Patchouli-1.20.1-84-FORGE.jar
PigPen-Forge-1.20.1-15.0.2.jar
Placebo-1.20.1-8.6.2.jar
ProgressiveBosses-3.9.7-mc1.20.1.jar
PuzzlesLib-v8.1.21-1.20.1-Forge.jar
Runelic-Forge-1.20.1-18.0.2.jar
StorageDrawers-1.20.1-12.5.2.jar
Structory_1.20.x_v1.3.5.jar
Structory_Towers_1.20.x_v1.0.7.jar
'TATOS 1.0.1_stable.jar'
TerraBlender-forge-1.20.1-3.0.1.7.jar
YungsApi-1.20-Forge-4.0.5.jar
ad_astra-forge-1.20.1-1.15.5.jar
adastraextra-forge-1.20.1-1.2.3.jar
aether-1.20.1-1.4.2-neoforge.jar
aether_delight_1.0.0_forge_1.20.1.jar
alexscaves-1.1.5.jar
alexsmobs-1.22.8.jar
amendments-1.20-1.2.8.jar
another_furniture-forge-1.20.1-3.0.1.jar
apothic_mutant_heads-0.1.0.jar
aquamirae-6.API15.jar
architectury-9.2.14-forge.jar
ars_elemental-1.20.1-0.6.5.0.1.jar
ars_nouveau-1.20.1-4.12.4-all.jar
artifacts-forge-9.5.11.jar
astemirlib-1.20.1-1.25.jar
athena-forge-1.20.1-3.1.2.jar
autumnity-1.20.1-5.0.1.jar
balm-forge-1.20.1-7.3.9-all.jar
betterarcheology-1.2.0-1.20.1.jar
bettercombat-forge-1.8.6+1.20.1.jar
bettervillage-forge-1.20.1-3.2.0.jar
blueprint-1.20.1-7.1.0.jar
botarium-forge-1.20.1-2.3.4.jar
buzzier_bees-1.20.1-6.0.0.jar
caelus-forge-3.2.0+1.20.1.jar
chunkloaders-1.2.8a-forge-mc1.20.1.jar
citadel-2.6.0-1.20.1.jar
cloth-config-11.1.118-forge.jar
comforts-forge-6.4.0+1.20.1.jar
common-networking-forge-1.0.5-1.20.1.jar
connectivity-1.20.1-5.6.jar
constructionwand-1.20.1-2.11.jar
copycats-2.1.2+mc.1.20.1-forge.jar
cosmeticarmorreworked-1.20.1-v1a.jar
create-1.20.1-0.5.1.f.jar
create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.12.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d.jar
createaddition-1.20.1-1.2.4d.jar
createbigcannons-5.5.1-mc.1.20.1-forge.jar
createdeco-2.0.2-1.20.1-forge.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.9.1+1.20.1.jar
destroy-1.20.1-0.8.jar
domesticationinnovation-1.7.1-1.20.1.jar
dummmmmmy-1.20-1.8.19.jar
easy-villagers-forge-1.20.1-1.1.17.jar
ender_dragon_loot_-1.7.4.jar
endrem_forge-5.3.3-R-1.20.1.jar
farmersrespite-1.20.1-2.1.2.jar
forbidden_arcanus-1.20.1-2.2.6.jar
ftb-library-forge-2001.2.4.jar
ftb-ultimine-forge-2001.1.5.jar
geckolib-forge-1.20.1-4.4.7.jar
gelato_galore-1.0-1.20.1.jar
iceandfire-2.1.13-1.20.1-beta-5.jar
immersive_aircraft-1.0.1+1.20.1-forge.jar
immersive_weathering-1.20.1-2.0.1-forge.jar
ironchest-1.20.1-14.4.4.jar
jei-1.20.1-forge-15.12.2.51.jar
kotlinforforge-4.11.0-all.jar
letsdo-API-forge-1.2.15-forge.jar
letsdo-vinery-forge-1.4.28.jar
libraryferret-forge-1.20.1-4.0.0.jar
lionfishapi-1.9.jar
lootr-forge-1.20-0.7.34.89.jar
moonlight-1.20-2.12.16-forge.jar
obscure_api-15.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polymorph-forge-0.49.5+1.20.1.jar
raccompat-1.20.1-0.1.3.jar
ramcompat-1.20.1-0.1.4.jar
relics-1.20.1-0.8.0.6.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.28.jar
sapience-1.20.1-1.0.0.jar
simplyswords-forge-1.56.0-1.20.1.jar
sliceanddice-forge-3.2.1.jar
sons-of-sins-1.20.1-2.1.6.jar
sophisticatedbackpacks-1.20.1-3.20.6.1064.jar
sophisticatedcore-1.20.1-0.6.25.632.jar
stitched_sins-1.1.1.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
supplementaries-1.20-2.8.17.jar
tfmg-0.9.1b-1.20.1.jar
thedawnera-1.20.1-0.58.94.jar.disabled
tlc_forge-1.0.3-R-1.20.X.jar
toms_storage-1.20-1.6.8.jar
twilightforest-1.20.1-4.3.2508-universal.jar
upgrade_aquatic-1.20.1-6.0.1.jar
valhelsia_core-forge-1.20.1-1.1.2.jar
waystones-forge-1.20-14.1.4.jar

**Additional context**

[crash-2024-08-29_13.00.45-server.txt](https://github.com/user-attachments/files/16797409/crash-2024-08-29_13.00.45-server.txt)

[latest.log](https://github.com/user-attachments/files/16797420/latest.log)

**Minecraft Username**

The_arinav

**Comment by petrolpark** [comment]
Fixed on Immersive Aircraft's end.
