### ISSUE TITLE
vat becomes unusable

### ISSUE THREAD

**Issue by Jakub-Kowalski-137** [petrolpark/Destroy#426]
**Describe the bug**

after filling the vat with brine fully and heating it, it bugs out and shows as almost empty or empty. no longer possible to put in or pull out any fluids/gasses

**To Reproduce**
1. build vat
2. pump in brine fully
3. heat up vat
4. when the vat becomes full it suddenly becomes empty/almost empty and becomes unusable

**Expected Behavior**

vat should fill with brine and process it with the heat provided, or at least stop producing. the vat becomes unusable after the bug
**System Information**

- create version: 0.5.1.f
- destroy version: 0.8
- jei version: 15.3.0.5
- forge: 47.3.0

video demonstration: 
https://youtu.be/Wcs81JHyPR4

**Comment by petrolpark** [comment]
Vats are no longer able to be completely filled with liquid (snapshot 8).
