### ISSUE TITLE
crash on start up with create 0.5.1g-h

### ISSUE THREAD

**Issue by xg787** [petrolpark/Destroy#427]
**Describe the bug**
crash on start up

**To Reproduce**
1. load destroy with create 0.5.1g-h
2. crash

**Expected Behavior**
load

**System Information**
 - Create version 0.5.1g-h

**Additional context**
[latest.log](https://github.com/user-attachments/files/16856549/latest.log)
[crash-2024-09-03_17.29.40-client.txt](https://github.com/user-attachments/files/16856559/crash-2024-09-03_17.29.40-client.txt)

**Comment by Explode007** [comment]
Same here, It's probably due to some new patches they released.

![image](https://github.com/user-attachments/assets/8cd9e970-6193-4145-9b36-bcf9d627abca)

**Comment by Keeper545** [comment]
Decided to try reverting back to Create 0.5.1 e, seems to work so far but since it's reverting I wouldn't count on current worlds being unscathed.

**Comment by rmart1n-dev** [comment]
Just a note here, Create seems to work with destroy up to 0.5.1f. In case there's any bugs that 0.5.1f fixes, you can upgrade to that version. Of course, 0.5.1G and 0.5.1H don't work.

**Comment by petrolpark** [comment]
Yes, downgrade for now. It's annoying but Destroy 0.1.0 (which is of course compatible again) is coming soon.
