### ISSUE TITLE
Innkeeper Trades give too little Villager XP

### ISSUE THREAD

**Issue by Phanastrae** [petrolpark/Destroy#43]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2

The Innkeeper's trades seem to give too little Villager XP, when compared to vanilla villagers.
This leads to them sometimes taking unusually long to level up.
Comparing Vanilla's values (https://minecraft.wiki/w/Trading#Java_Edition_offers) vs Destroy's Innkeeper's values (https://github.com/petrolpark/Destroy/blob/1.20.1/src/main/java/com/petrolpark/destroy/world/village/DestroyTrades.java)

Innkeeper XP:
Novice: 1
Apprentice: 1 or 3
Journeyman: 1 or 5
Expert: 12
Master: 15, 20, or 30

Vanilla XP:
Novice: 1 (buy) or 2 (sell)
Apprentice: 5 (buy) or 10* (sell)
Journeyman: 10* (buy) or 20 (sell)
Expert: 15 (buy) or 30 (sell)
Master: 30* (buy) or 30 (sell)
(*): with one exception
Where (buy) means you give them emeralds, and (sell) means they give you emeralds.

Notably Apprentice and Journeyman in particular are unusually low.

**Comment by petrolpark** [comment]
I'll tweak this in 0.3. You've submitted a lot of very useful bug reports, so if you want message me on discord (`petrolpark`) and I'll give you the **Beta Tester** Badge.

**Comment by petrolpark** [comment]
Innkeeper Trade XP now reflects Vanilla villagers in 0.3.
