### ISSUE TITLE
Game Crashes when booting with mod.

### ISSUE THREAD

**Issue by donovan-maker** [petrolpark/Destroy#432]
**The Bug**

When I boot up the game it crashes and gives this crash error message:
`org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError`

**To Reproduce**

1. In Curseforge make an instance for Minecraft forge version 1.20.1, 47.3.0.
2. Add the following mods:
2.1. Create 0.5.1h
2.2. Destroy 0.8
3. Open the launcher and run the game
4. Then it crashes and gives that error message once you left click to disable the narrator.

**Expected Behavior**

The expected behavior is that it should start and not crash when I left click.

**Minecraft Username**

If you are interested in the **Beta Tester** [Badge](https://patreon.com/petrolpark/about), include your Minecraft username here (case-sensitive). _This is from the template_
donovanMan1234

**Comment by FlamingKetchup** [comment]
Downgrade Create to 0.5.1f

**Comment by donovan-maker** [comment]
Works! I wonder how that fixes it. Do you know what is changed between those versions?

**Comment by petrolpark** [comment]
Fixed in 0.1.0. Downgrade for now.

**Comment by donovan-maker** [comment]
Ok
