### ISSUE TITLE
Dynamo doesn't perform charging or electrolysis recipes

### ISSUE THREAD

**Issue by UnderscoreKilburn** [petrolpark/Destroy#436]
**Describe the bug**

What the title says.

**To Reproduce**

Place a depot, toss a regular torch on it, then place a dynamo on top and power it with a creative motor at 256 RPM.

**Expected Behavior**

The torch should turn into a redstone torch.

**Screenshots**

![2024-09-26_15 03 41](https://github.com/user-attachments/assets/19cf23ed-e626-4c2f-8760-f26eb2a8cc7d)

**System Information**

 - Create 0.5.1h
 - JEI 15.19.5.99
 - Jade 11.11.1

**Additional context**

This also affects fluid electrolysis (i.e. brine and mercury). Arc furnace recipes work as expected however.
It is worth noting that if the dynamo is placed first and the depot second, placing a valid item on the depot will trigger the dynamo's zapping animation but no sound will play and the item will still not be transformed.

**Minecraft Username**

_Kilburn

**Comment by petrolpark** [comment]
Fixed in snapshot 4.
