### ISSUE TITLE
Mixed explosive does not detonate

### ISSUE THREAD

**Issue by flynnvali** [petrolpark/Destroy#437]
![image](https://github.com/user-attachments/assets/45fbd39f-a4a9-4b47-a691-9c96c99f3b24)
self explanatory, snapshot 3

FlynnGuy

**Comment by flynnvali** [comment]
Oop forgot to include that only with nitrocellulose. I'm in a rush lol

**Comment by Penta0308** [comment]
Check the sensitivity of your setup.

**Comment by petrolpark** [comment]
If the only thing in there is nitrocellulose, it won't be sensitive enough to detonate.
