### ISSUE TITLE
Keypunch punches the wrong hole if the depot holding the circuit mask is rotated 90 degrees

### ISSUE THREAD

**Issue by UnderscoreKilburn** [petrolpark/Destroy#438]
**Describe the bug**

When punching a hole through a circuit mask that has been rotated 90 degrees using a mechanical bearing, the hole appears on the opposite side from where it should be. This only seems to affect upright masks (flipped masks are punched correctly), and doesn't happen if the keypunch itself is rotated instead of the depot.

**To Reproduce**

Place a mechanical bearing facing up, attach a crank to the bottom, then a depot on top of it and a keypunch over the depot. Toss a circuit mask onto the depot, click on the crank to rotate the depot 90 degrees clockwise then power the keypunch. A hole should be punched in the north-east corner.

**Expected Behavior**

The hole should be punched in the south-west corner.

**Screenshots**

![2024-09-26_17 25 43](https://github.com/user-attachments/assets/8689ceaa-ab6a-4d5c-90a1-58476f3abb94)

**System Information**

 - Create 0.5.1h
 - JEI 15.19.5.99
 - Jade 11.11.1

**Minecraft Username**

_Kilburn

**Comment by petrolpark** [comment]
Fixed in snapshot 4.
