### ISSUE TITLE
Molecules do not have names in recipes with EMI

### ISSUE THREAD

**Issue by f-raZ0R** [petrolpark/Destroy#443]
**Describe the bug**

Molecules do not show their names with EMI installed, even if JEI is also installed

**To Reproduce**
have emi and the latest destroy snapshot installed, look at any destroy recipe involving chemicals

**Expected Behavior**
The molecules would show their name

**Screenshots**

![2024-09-26_10 11 24](https://github.com/user-attachments/assets/2d8edfe7-96bd-4238-aa12-2c4fbd1928ef)

**System Information**
N/A

**Additional context**

N/A

**Minecraft Username**

tildeAthebyne

**Comment by Daxturus** [comment]
I am also experiencing this issue. 
I can still search for molecules, and they do show the proper recipes when left/right clicked; however, it appears their names are not being shown in EMI.

**Comment by petrolpark** [comment]
This is due to a bug on EMI's end, which [I have reported](https://github.com/emilyploszaj/emi/issues/719).

**Comment by f-raZ0R** [comment]
Fixed in latest EMI version
