### ISSUE TITLE
Unable To Pump Fluids Into Sophisticated Backpack Fluid Tanks. Some of the time

### ISSUE THREAD

**Issue by EvilDarkSoul** [petrolpark/Destroy#448]
**Describe the bug**
Was able to pump mercury into a Sophisticated Backpack(SB) however after pumping it out am no longer able to pump back into back 

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Create Mercury from molten cinnabar
2. Pump Mercuy from bubble cap into SB Iron backpack. 
3. Pickup Backpack and move to a new location
4. Pump Mercury into create fluid tank.
5. Reverse pump and nothing happens.

**Expected Behavior**

It should pump the fluid back into the backpack.

**System Information**

 - Destroy 0.0.8
 - Create version 0.5.1f
 - Sophisticated Backpacks 3.20.5.1044
 - Sophisticated Core 0.6.22.611

**Comment by petrolpark** [comment]
Mixtures can't really go in other mods' Fluid Tanks, as indicated in the Vat ponder.
