### ISSUE TITLE
Vat Pressure gauge breaks with negative pressure.

### ISSUE THREAD

**Issue by coolbot100s** [petrolpark/Destroy#45]
If the vat has a negative pressure value, the gauge needle spins backward, eventually completely off the bounds of the gauge.
![javaw_zTwmrPDN2e](https://github.com/petrolpark/Destroy/assets/76798835/692b5f66-c79e-4cc8-9db1-43cfae7da5ac)

**Comment by petrolpark** [comment]
Fixed in 0.4.
