### ISSUE TITLE
Minecraft crashes when creating a new world

### ISSUE THREAD

**Issue by albertosaurio65** [petrolpark/Destroy#450]
Within the single player menu you click on create a new world and Minecraft closes.
![image](https://github.com/user-attachments/assets/b1ff4fea-4828-4814-bcb6-fef0a3da8b64)

destroy-1.20.1-0.1.0-snapshot-5.jar 

[crash-2024-09-28_17.38.57-client.txt](https://github.com/user-attachments/files/17174953/crash-2024-09-28_17.38.57-client.txt)

**Comment by petrolpark** [comment]
Uninstall Molten Metallurgy. It looks like its mixin is causing this, but because that mod is closed source I can't make it compatible.
