### ISSUE TITLE
test tubes do not work on fluid tanks and do not fill up when right clicking compatible containers in creative mode.

### ISSUE THREAD

**Issue by NthPhantom10** [petrolpark/Destroy#453]
it will not allow the user to right-click test tubes onto fluid tanks, and in creative mode, if you right click any fluid container, it will drain the container but will not fill the test tube

go in creative, grab test tube, grab fluid tank, add chemical of choice to tank and right click with empty test tube, right click on something like a basin with a empty test tube in creative and it will drain the basin but not the test tube.
 

~NthPhantom10

**Comment by petrolpark** [comment]
You left click to fill test tubes.

**Comment by NthPhantom10** [comment]
oh. lol whoops.
