### ISSUE TITLE
Hovering over a mixed explosive that has things inside it in creative crashes the game

### ISSUE THREAD

**Issue by ZenithEnfys** [petrolpark/Destroy#455]
**Describe the bug**

Hovering over a mixed explosive filled with items crashes the game

**To Reproduce**

In creative
Fill a mixed explosive
Pick block the filled mixed explosive
Hover over it in your inventory

**Expected Behavior**

After much deliberation i have come to the conclusion hovering over a filled mixed explosive in your inventory should not crash the game

**Screenshots**

Not sure how i could get any

**System Information**

Does not happen in latest full release for obvious reasons

 - Create version 0.5.1h
 - Jei version 15.19.5.99
 - Mouse Tweaks version 2.25.1-forge
 - Petrolpark's Library version 1.0.5

**Additional context**

https://mclo.gs/SXZGenh
https://mclo.gs/zCiyKkF

**Minecraft Username**

Zigonicle

**Comment by petrolpark** [comment]
Fixed in snapshot 7.
