### ISSUE TITLE
Ponder crash

### ISSUE THREAD

**Issue by albertosaurio65** [petrolpark/Destroy#457]
![image](https://github.com/user-attachments/assets/30dca5d7-6678-4353-b4d6-9beb20bf4472)
[crash-2024-09-29_16.21.34-client.txt](https://github.com/user-attachments/files/17179558/crash-2024-09-29_16.21.34-client.txt)
[debug.log](https://github.com/user-attachments/files/17179559/debug.log)
[latest.log](https://github.com/user-attachments/files/17179560/latest.log)

https://github.com/user-attachments/assets/5d91abf6-a4cd-4cd5-9843-9de75d800aef

**Comment by TheRedCrafter344** [comment]
fixed by #456
