### ISSUE TITLE
crash then vat controller is placed with colorimetr

### ISSUE THREAD

**Issue by Gfortes985** [petrolpark/Destroy#458]
https://github.com/user-attachments/assets/b7af0870-6cb5-4b9f-889e-03d407606668

my mods

![image](https://github.com/user-attachments/assets/54f6eb0e-22e4-4d0b-8a03-a1ea1c1ca208)

**Comment by Gfortes985** [comment]
Correction, it will be crash even without colorimetr

**Comment by TheRedCrafter344** [comment]
most likely fixed by #456
