### ISSUE TITLE
crash when breaking vat with thermometer

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#459]
breaking the controller of a vat with a thermometer attached causes the game to crash. destroying the vat by breaking any other block does not cause a crash.

Note that this crash was detected on snapshot 5, as snapshot 6 won't even load into the world without crashing.

Modlist:
Destroy 0.1.0-snapshot5
Petrolpark Library 1.0.6
Create 0.5.1h
JEI 15.19.5.99

Crash report: https://pastebin.com/5kNijhyy

**Comment by Drigonis** [comment]
also occurs when breaking with pressure meter.

**Comment by Penta0308** [comment]
Probably will be fixed by https://github.com/petrolpark/Destroy/pull/456
