### ISSUE TITLE
Crash on using custom JSON create:filling recipe with "mixtureFluidWithMolecule": "destroy:mixture" 

### ISSUE THREAD

**Issue by drhaber** [petrolpark/Destroy#46]
I am running `destroy-1.20.1-0.2` 
and just found [this issue ](https://github.com/petrolpark/Destroy/issues/31)

### **I do not know if this issue is related but I will post an update if it continues in 0.3**

I have attempted to create the following recipe using Craft Tweaker 
```
<recipetype:create:filling>.addJsonRecipe("destroy_hydrochloric_acid_conversion", {
    "type": "create:filling",
    "ingredients": [
      {
        "item": "minecraft:bucket"
      },
      {
        "mixtureFluidWithMolecule": "destroy:mixture",
        "amount": 1000,
        "molecule": "destroy:hydrochloric_acid",
        "concentration": 1.0
      }
    ],
    "results": [
      {
        "item": "kubejs:hydrochloric_acid_bucket"
      }
    ]
  }); 
```
I based this recipe format on [picric_acid.json recipe](https://github.com/petrolpark/Destroy/blob/1.20.1/src/main/resources/data/destroy/recipes/filling/picric_acid.json)

The recipe registers in game without error and shows in JEI 
![image](https://github.com/petrolpark/Destroy/assets/56454522/55d85fd7-af3f-4ed0-af34-45e4d5590f26)
![image](https://github.com/petrolpark/Destroy/assets/56454522/9501b0e7-0631-4ab7-9e96-6c1ad31b9ee7)

However when the recipe is attempted in game it crashes
![image](https://github.com/petrolpark/Destroy/assets/56454522/d7eaaadd-06df-4548-b163-08d992f97748)
```t TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.logistics.depot.DepotBlock.m_5548_(DepotBlock.java:93)```
[Full Log](https://mclo.gs/02q9L0i)

**Comment by petrolpark** [comment]
I think you're right, this is the same bug as #31. I'll close this issue and address that one instead.

**Comment by drhaber** [comment]
It appears this issue is not resolved 
[log](https://mclo.gs/m9Farkg)
```
mixin apply failed create_enchantment_industry.mixins.json:FillingBySpoutMixin -> com.simibubi.create.content.fluids.spout.FillingBySpout: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on com/simibubi/create/content/fluids/spout/FillingBySpout::canItemBeMended with priority 1000 cannot inject into com/simibubi/create/content/fluids/spout/FillingBySpout::canItemBeFilled(Lnet/minecraft/world/level/Level;Lnet/minecraft/world/item/ItemStack;)Z merged by net.chauvedev.woodencog.mixin.recipes.MixinFillingBySpout with priority 1000 [PREINJECT Applicator Phase -> create_enchantment_industry.mixins.json:FillingBySpoutMixin -> Prepare Injections ->  -> handler$dlj000$canItemBeMended(Lnet/minecraft/world/level/Level;Lnet/minecraft/world/item/ItemStack;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
```

Upon the removal of [Create Enchantment Industry](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry) the issue went away
