### ISSUE TITLE
Crash when creating a vat of any size 

### ISSUE THREAD

**Issue by flynnvali** [petrolpark/Destroy#461]
Every time I create a vat of any size, it instantly crashes the game. Reloading and the vat is there and formed. It is interactable, however it crashes upon its insides receiving any change.

Crash Report:
https://pastebin.com/EQvFdUNe

Modlist:
JEI 15.19.5.99
Create 0.5.1h
Petrolpark Lib 1.0.5
Destroy 0.1.0 snapshot 6 

Minecraft Name:
FlynnGuy

**Comment by TheRedCrafter344** [comment]
Fixed by #456
