### ISSUE TITLE
Infinite heating and water transmutes into mercury

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#462]
A vat with an open vent and any amount of any liquid inside it will heat up at approximately 0.4c/second, even without reactions happening. The heating will continue until the liquid boils.

Creating a vat with open vent, putting mercury in it, waiting until it heats up on its own to above 100c, and then adding a test tube of water will cause the temperature to immediately fall to 100c exactly (not a bug, but might want to change it, where is all that heat going?), the water will start boiling, and extra mercury will magically appear in the vat such that the volume of the liquid remains constant even with the water leaving. After all the water boils, the temperature begins rising again.

Bug happens on both snapshot 5, and snapshot 6 with #456 compiled.

**Comment by TheRedCrafter344** [comment]
The same thing happens when the mercury itself gets hot enough to boil; Gaseous mercury is being produced, but the amount of liquid mercury does not get reduced.

**Comment by Penta0308** [comment]
Happens with pure water + air too.
Putting them with No-vent-vat increases temperature. Creating Open-vent-vat doesn't stop.
Removing the vent or closing the vent with redstone stops increasing.
