### ISSUE TITLE
Discrepancies in item production between vat and basin reactions

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#464]
Polymerising 200mb of pure isoprene in a vat produces 552 polyisoprene items, as is expected. (which is an absurdly high amount, pls balance)

Polymerising 200mb of pure isoprene in a basin (irregardless of mixer rpm) produces 2 polyisoprene items, which, after careful analysis, was determined to be less than the expected 552.

Similar results were obtained when testing sodium precipitation from mercury.

**Comment by petrolpark** [comment]
Fixed in snapshot 7.
