### ISSUE TITLE
Crash when Borax solution exists in a reaction vessel

### ISSUE THREAD

**Issue by flynnvali** [petrolpark/Destroy#469]
Whenever the Borax solution obtained from boiling water in a dry biome exists in either a mechanical mixer or in a basin with an active mechanical mixer, the game will instantly crash.

Crash report:
https://pastebin.com/GNaVeyQW

Modlist:
Petrolpark Lib 1.0.6
Destroy 0.1.0 snapshot 7
JEI 15.20.0.101
Create 0.5.1h

Minecraft name:
FlynnGuy

**Comment by petrolpark** [comment]
Fixed in snapshot 8.
