### ISSUE TITLE
Adding a stack of items at a time to a vat causes a crash if the vat contains a gas.

### ISSUE THREAD

**Issue by coolbot100s** [petrolpark/Destroy#47]
crash report: https://mclo.gs/0HK4vQW

In this case, I attempted to throw a stack of dried kelp into a vat containing ethanol via a brass funnel attached to the top of the vat, which caused the crash.  
The crash does not occur if items are added one at a time, or if the vat does not contain a liquid.

**Comment by petrolpark** [comment]
Fixed in 0.3.
