### ISSUE TITLE
Missing word in vat controller ponder [snapshot 7]

### ISSUE THREAD

**Issue by Teiz3** [petrolpark/Destroy#470]
**Describe the bug**

The vat ponder has a missing "not".
In the second ponder screen of the vat controller it states: "Edges and corners do allow access to the Vat", this should be "Edges and corners do not allow access to the Vat".

**To Reproduce**

1. Open the vat controller ponder
2. Go to the first part of the second ponder screen

**Expected Behavior**

It should state: "Edges and corners do not allow access to the Vat"

**Screenshots**

![PonderBug](https://github.com/user-attachments/assets/83f198c9-530b-4fa4-bec2-ba99ec9177f4)

**System Information**

You should only report issues on the latest update of Destroy, or on the latest snapshot (if it is for an unreleased update). For snapshots, it would be useful if you also checked if the bug exists in the latest full update. No other versions are supported. Include the following information:
 
 - Create version 0.5.1h
 - JEI version 1.20.1 Forge
 - Destroy snapshot 7
 - Petrolpark lib version 1.0.6

**Additional context**

None

**Minecraft Username**

If you are interested in the **Beta Tester** [Badge](https://patreon.com/petrolpark/about), include your Minecraft username here (case-sensitive).

**Comment by petrolpark** [comment]
Fixed in shapshot 9
