### ISSUE TITLE
Heating is too slow (or doesn't work at all)

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#476]
Blaze burners and refrigerstraytors, by default, are so slow that they cannot heat even small amounts of liquid. They need to be made about 100 times stronger. Similarly, vats dissipate heat to their environments far too slowly. (slowly in this case means that they don't dissipate at all, since vats won't heat the mixtures inside them if the temperature difference that would be produced isnt large enough).

Making blaze burners that much stronger would probably make heating gases *too* quick however. That could be fixed by seperating vat casing temperature and mixture temperature, and gases would then simply transfer heat from and to the casing at a slower rate.

(Also, would be cool for vat materials to have a max temperature they can handle, for modpack balancing reasons if nothing else)

**Comment by petrolpark** [comment]
The heating powers were another thing forgotten when a lot of values changed by a factor of 1000 in 0.1.0. They should be back to their 0.0.8 relative powers in snapshot 9.

**Comment by TheRedCrafter344** [comment]
be aware that ill make a new issue complaining about gases heating up too quickly now >:)

**Comment by Penta0308** [comment]
The vat block themselves should have heat capacity.
