### ISSUE TITLE
Game freezes while exiting world (singleplayer)

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#477]
Last console line is "Saving worlds"
No relevant logs

Mods:
Create 0.5.1h
Destroy 0.1.0-snapshot-8
e4mc 5.2.1
JEI 15.20.0.101
Petrolpark's Library 1.0.6

**Comment by petrolpark** [comment]
What's in the world? I'm presuming its due to a Vat, in which case what's in the Vat?

**Comment by TheRedCrafter344** [comment]
there were 2 vats, one with mercury, sodium, air, and open vent, and one with air, chlorine solution, and closed vent. will test them separately later if neccesary.

**Comment by TheRedCrafter344** [comment]
It appears that the bug is caused whenever there exists an open vent vat in the world, irregardless of contents.
