### ISSUE TITLE
Agar blocks cause perpetual acceleration 

### ISSUE THREAD

**Issue by coolbot100s** [petrolpark/Destroy#48]
WARNING: the video linked contains flashing images and high-speed spinning. 
The strip of agar featured is 100 blocks long, and as you can see entities will reach the end before I can even teleport there.  
Importantly, when in the boat I am not holding down any buttons, I gently tap w once to move forward, and gently tap d once to initiate the ***Infinispin***, please don't nerf these blocks too much the ice physics is fun lol.
https://www.youtube.com/watch?v=ZRO-O0Yoa58

**Comment by petrolpark** [comment]
Fixed in 0.3. Thanks for your help!
