### ISSUE TITLE
Skin clipping through gas mask

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#485]
![image](https://github.com/user-attachments/assets/eb2b0fd3-01a5-44dc-a65f-ae69babffe3f)

My skin clips through the gas mask when it probably shouldn't.

**Comment by petrolpark** [comment]
I think I fixed this in a previous version but forgot to add it to the changelog. I've checked the model and the mask should be slightly bigger than the skin now, but let me know if the issue persists.
