### ISSUE TITLE
Nanodiamonds recipe still shows old nitrocellulose block

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#487]
Yep.

**Comment by CDWimmer** [comment]
Noted this in discord last week but ye, in JEI:
![image](https://github.com/user-attachments/assets/c78cb0f9-d3f2-438e-afbf-92f1e691d799)
![image](https://github.com/user-attachments/assets/b3b074ed-7267-49d9-bd17-9f546379391c)

Tab's icon is correctly showing the Mixed Explosive, however. :)

**Comment by petrolpark** [comment]
Fixed in snapshot 10.
