### ISSUE TITLE
Container contents not copied

### ISSUE THREAD

**Issue by RapunzelE** [petrolpark/Destroy#488]
**Before submitting a bug report, ensure you are familiar with the [rules](https://github.com/petrolpark/destroy/issues/1).** Do not include this line in the bug report.

**Describe the bug**

Items in containers are not copied when using CTRL+Middle-click or schematics

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Fill a container, like a barrel, with items
2. CTRL+Middle-click it
3. Place down the item you got from the previous step
4. The container you placed down should now be empty

**OR**

1. Fill a container with items
2. Create a schematic with the container in it
3. Paste the schematic back into the world
4. The container placed by the schematic should now be empty

**Expected Behavior**

The `Items` NBT Tag should be copied when doing CTRL+Middle-click

**Screenshots**

![Screenshot_20241002_215038](https://github.com/user-attachments/assets/f3b4f019-f10e-43ab-9cf9-368dd97ddb63)

**System Information**

- Minecraft **1.20.1**
- Forge **47.3.0**
- Create **0.5.1.h**
- Create: Pattern Schematics **1.1.15+forge-1.20.1**
- Just Enough Items **15.20.0.101**
- Petrolpark's Library **1.0.6**
- Destroy **0.1.0-snapshot-9**

**Additional context**

Seems to also be reproducible in Snapshot 7 _(didn't verify)_

**Minecraft Username**

ThatWeirdCoder

**Comment by petrolpark** [comment]
Fixed in snapshot 10.
