### ISSUE TITLE
Make sodium ingots explode in water too

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#489]
IRL, throwing sodium in water makes an explosion that sends flaming sodium flying in all different directions. When I throw my minecraft sodium brick into my minecraft water is just oxidizes and I get sad. I don't think the explosion should be super big, but something like a firework would be cool.

Problem this solves: something something chemical accuracy (it would be cool)

**Comment by petrolpark** [comment]
I did think of this, but decided that sodium would just oxidize (maybe I'll add some fizzing particles). The lower alkali metals, if and when they are added, will explode.
