### ISSUE TITLE
Crash breaking bubble tower

### ISSUE THREAD

**Issue by haus-jackl** [petrolpark/Destroy#49]
Broke the bottom block of the bubble tower which contained brine while I had water pumping into it and replaced the block. Got this error: "The game crashed whilst ticking block entity
Error: java.lang.IllegalStateException: Provided BlockState is for a different block." attatched will be the full crash log.
[crash-2024-01-06_00.07.51-server.txt](https://github.com/petrolpark/Destroy/files/13848841/crash-2024-01-06_00.07.51-server.txt)

**Comment by petrolpark** [comment]
Fixed in 0.3.
