### ISSUE TITLE
Throwing sodium hydride in water bug

### ISSUE THREAD

**Issue by leglegab** [petrolpark/Destroy#490]
In the latest snapshot, when sodium hydride is thrown into water it (or you walk into water with it in your inventory) it never stops exploding. Though sometimes it will disappear when you throw it out of your inventory. No actual block damage or anything like that happens either (if that's unintended).

Bonus bug: sodium hydride is not in JEI

To recreate: throw sodium hydride in water

**Comment by petrolpark** [comment]
Fixed in snapshot 10.
