### ISSUE TITLE
Molecule Display isn't showing up in creative/JEI

### ISSUE THREAD

**Issue by CDWimmer** [petrolpark/Destroy#491]
**Describe the bug**

1. Molecule Display isn't showing up in creative inventory or JEI. It's a cool item, it should totally be there!
2. It doesn't have a translation. I shall attempt to remedy that in a moment. 

**To Reproduce**

Search by any means for "molecule_display" / "item.destroy.molecule_display" and fail to obtain item. 

Do `/give @s destroy:molecule_display` - receive item

**Expected Behavior**

The cool item to be obtainable, at least in creative if not survival. 

**Screenshots**

![image](https://github.com/user-attachments/assets/93ae58e0-d38b-4f2d-b9cc-e251bb1147c5)

![image](https://github.com/user-attachments/assets/0d94805a-b480-4dc8-8582-07ad489346c7)

**System Information**

Destroy snapshot 9

**Minecraft Username**

[gogglebot](https://mcuuid.net/?q=gogglebot)

**Comment by CDWimmer** [comment]
name issue resolved by #493

**Comment by petrolpark** [comment]
It's a dummy item, not meant to be in an inventory

**Comment by CDWimmer** [comment]
> It's a dummy item, not meant to be in an inventory

Okay I feel like you're missing the part where it would be really fun and cool tho :( 

decoratives always go hard esp given the placeable beakers and such. Makes me want to do an Education Edition style classroom/lab
