### ISSUE TITLE
Crash on emptying Aging Barrel during aging process with beaker in Snapshot 9

### ISSUE THREAD

**Issue by flynnvali** [petrolpark/Destroy#496]
Fill an aging barrel w/ moonshine via the recipe, right click w/ empty beaker twice, game crashes.
 
Crash Report: 
https://pastebin.com/KN8ZAVk3

Mods present: 
JEI 15.20.0.102
Create 0.5.1h
Petrolpark lib 1.0.6
Destroy 0.1.0 snapshot 9

Minecraft username:
FlynnGuy

**Comment by petrolpark** [comment]
Fixed in snapshot 10.
