### ISSUE TITLE
Paper pulp recipe is an absolute pain to accomplish

### ISSUE THREAD

**Issue by flynnvali** [petrolpark/Destroy#497]
You require over 6 stacks of oxidized sodium ingots for the 500mb of 5M Sodium Hydroxide just for two measly paper pulp. I would suggest either lowering the concentration required significantly or lowering the amount to only 50mb to produce more bang for your buck

**Comment by petrolpark** [comment]
Required amounts of mixtures have been reduced in snapshot 10 for lots of recipes
