### ISSUE TITLE
Mixin crash on startup between destroy 0.1.0 v10 and Dave's Potioneering

### ISSUE THREAD

**Issue by border999** [petrolpark/Destroy#498]
**Describe the bug**
See title.

**To Reproduce**
Unsure of precise conditions.

**System Information**
 - Create version v0.5.1h
 - Dave's Potioneering-forge-1.20.1-12
 - destroy 0.1.0 snapshot 10

**Additional context**
https://gist.github.com/border999/91d265bd6b2352fdac519afec9f04846 latest.log
https://gist.github.com/border999/4331ad863f06375e815b5446d64cd2a9 debug.log

**Minecraft Username**
Pheonixarcher

**Comment by border999** [comment]
reporting on both mods github issue pages for good measure

**Comment by Explode007** [comment]
I Also have this issue, It's a collision in mixin priority (1000) that prevents them from loading. I don't know if It will break anything but reducing priority or have it auto-assigned could possibly fix things.

**Comment by border999** [comment]
any update on this?

**Comment by border999** [comment]
It's been a couple of weeks with no updates. Just curious what's happening in the background.

**Comment by leglegab** [comment]
@border999 according to the discord I think petrolpark is back at university so he's been busy with school. It sucks, but I'm sure he'll get around to it at some point.

**Comment by petrolpark** [comment]
Fixed in 0.1.0 snapshot 11
