### ISSUE TITLE
Molten Inox and Molten Borosilicate do not work in water

### ISSUE THREAD

**Issue by TanCY1** [petrolpark/Destroy#506]
**Describe the bug**

When Molten Inox or Molten Borosilicate is placed in water, the fluid disappears.

**To Reproduce**

1. Use a water bucket to place a block of water
2. Use either a Molten Inox Bucket or Molten Borosilicate Glass Bucket in running water

**Expected Behaviour**

The fluid will solidify into its respective block, similar to obsidian

**System Information**

Create 0.5.1h

**Minecraft Username**

TanCY1

https://github.com/user-attachments/assets/99575f3e-2172-4a29-8c6a-3290b1e7605c

**Comment by Penta0308** [comment]
Being fixed by https://github.com/petrolpark/Destroy/pull/526
