### ISSUE TITLE
Mixin incompatibility with apoli (origins)

### ISSUE THREAD

**Issue by tlitookilakin** [petrolpark/Destroy#511]
**Describe the bug**

Crash on startup when installed alongside apoli.

**To Reproduce**

1. Install Destroy, Create, and Petrolpark lib
2. Install Origins and caelus api
3. Launch the game

**Expected Behavior**

Should make it to the main menu without crashing.

**System Information**

- Destroy 0.1.0-Snapshot-10
- Create 0.5.1h
- Origins 1.10.0.9
- Petrolpark lib 1.0.6
- Caelus 3.2.0
- neoforged 47.1.100

**Additional context**

[Crash Log](https://mclo.gs/MjJkGsU)

**Minecraft Username**

tlitookilakin

**Comment by Explode007** [comment]
Yeah this is the same issue currently with Dave's Potioneering; Mixins are using priority of 1000 which collide with destroy.

**Comment by petrolpark** [comment]
Fixed in snapshot 11. It's actually due to me using an overwrite mixin, which is bad practice and has been fixed.
