### ISSUE TITLE
[CREATIVE] When you right click with a test tube on the standard create fluid tanks it reduces the amount in the tank

### ISSUE THREAD

**Issue by semenishchev** [petrolpark/Destroy#512]
**Describe the bug**
Title

**To Reproduce**

1. Make a random mixture
2. Pump this mixture into a create fluid tank
3. Right click with a test tube in creative mode

**Expected Behavior**

Nothing should happen

**Screenshots**

https://github.com/user-attachments/assets/4b22fe88-7876-4360-b0b0-dc4f736abe1b

**System Information**
Create, Destroy, TFMG on Windows 11 all latest version

**Comment by SiffrinSuffrin** [comment]
You're filling the test tube with the liquid in the tank, then putting it back again

**Comment by SiffrinSuffrin** [comment]
I believe this was added by request?

**Comment by petrolpark** [comment]
Intended behaviour
