### ISSUE TITLE
Game crashing on start

### ISSUE THREAD

**Issue by MoonDark0** [petrolpark/Destroy#517]
**System Information**

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/petrolpark/registrate/PetrolparkRegistrate

**Comment by MoonDark0** [comment]
create 0.5.1.i

**Comment by MoonDark0** [comment]
Error likely due to this line 

import com.petrolpark.registrate.PetrolparkRegistrate; (51 in file src/main/java/com/petrolpark/destroy/Destroy.java)

while path com src/main/java/com/petrolpark not containing src/main/java/com/petrolpark registrate

**Comment by petrolpark** [comment]
Do you have the Petrolpark library installed?

**Comment by petrolpark** [comment]
Closed due to lack of response.
