### ISSUE TITLE
When running Destroy Mod (version: 1.20.1-0.1.0-Snapshot-10) on the Mohist server, an error occurs. 

### ISSUE THREAD

**Issue by MC-Nirvana** [petrolpark/Destroy#537]
**Describe the bug**

When running Destroy Mod (version: 1.20.1-0.1.0-Snapshot-10) on the Mohist server, an error occurs. 

**To Reproduce**

Steps to reproduce the behavior. For example:

1. Download mod
2. Load it into the mods folder of the mohist server.
3. Started the server, and found an error

For issues related to the chemistry system, include the full contents of the Mixture(s) that are causing issues. You can get this information by running the command `/data get block` on the Centrifuge, Vat Controller, bottom Bubble Cap, etc.

**Expected Behavior**

No error messages

**Screenshots**

**System Information**

You should only report issues on the latest update of Destroy, or on the latest snapshot (if it is for an unreleased update). For snapshots, it would be useful if you also checked if the bug exists in the latest full update. No other versions are supported. Include the following information:

 - create-0.5.1.j
 - destroy-1.20.1-0.1.0-snapshot-10
 - jei-1.20.1-forge-15.20.0.105
 - petrolpark-1.20.1-1.0.6

**Additional context**

log: https://mclo.gs/nzPsw5z

**Minecraft Username**
MC_Nirvana

**Comment by Penta0308** [comment]
Being fixed by https://github.com/petrolpark/Destroy/pull/538
