### ISSUE TITLE
Destroy 0.1.0-snaptshot-10 creates a visual bug with distant horizons 2.2.1-a

### ISSUE THREAD

**Issue by ionutsoran** [petrolpark/Destroy#539]
I am currently playing on my modded minecraft 1.20.1 forge version 47.3.0
When adding the latest version of destroy it somehow overrides the color of the grass blocks in distant horizon making everything pale including the water. Must be something destroy overrides in the biome tint or something I believe.

It happens both on client and server and only affects distant horizon logic.
In the older version of destroy before the alpha it used to work.

I also tested with just petrolpark's library and it doesn't recreate the visual bug.

Here is a screenshot
![Screenshot 2024-12-07 004840](https://github.com/user-attachments/assets/1ae5edc3-a85a-4b47-a8e8-1de311892155)

Mod versions 
 Destroy 0.1.0-snaptshot-10
 Petrolpark's Library 1.0.6
 Distant Horizons 2.2.1-a

**Comment by petrolpark** [comment]
Hopefully fixed by #504.
