### ISSUE TITLE
LPG makes the game crash when introduced with pipes into a Vat

### ISSUE THREAD

**Issue by Pory21** [petrolpark/Destroy#54]
I've tried this with other create addons and without them so I'm sure this is caused by destroy.
The game crashes the moment the LPG is connected to the Vat.

**Comment by MineKingTop** [comment]
Can confirm this problem, here's my crashlog if it helps
[crash-2024-01-06_12.19.29-server.txt](https://github.com/petrolpark/Destroy/files/13849405/crash-2024-01-06_12.19.29-server.txt)

**Comment by petrolpark** [comment]
Fixed in 0.3.
