### ISSUE TITLE
server redstone programmer

### ISSUE THREAD

**Issue by dark-enigma** [petrolpark/Destroy#543]
**Describe the bug**

when right clicking on the redstone programmer nothing happens and error in logs occurs

**To Reproduce**

place redstone programmer
right click
check logs

**Expected Behavior**

for it to open the gui

**System Information**

 - Create version 0.5.1h
 -JEI 1.20.1
 - neoforge

**Additional context**

logs of errors that occur on right click
[latest (1).log](https://github.com/user-attachments/files/18222069/latest.1.log)

**Minecraft Username**

If you are interested in the **Beta Tester** [Badge](https://patreon.com/petrolpark/about), include your Minecraft username here (case-sensitive).
Dark__Enigma

**Comment by petrolpark** [comment]
Fixed for snapshot 11.
