### ISSUE TITLE
Suggestion: Integration with other petrol adding mods

### ISSUE THREAD

**Issue by LucioMagno** [petrolpark/Destroy#56]
Would be nice to see more integration with other mods that add petrol or even other chemicals, like the create diesel engine mod, or the create factory must grow mod! If another mod adds pumpjacks you could disable the ones from this mod to reduce clutter <3

**Comment by petrolpark** [comment]
Destroy now uses the tag `forge:crude_oil`, meaning it is compatible with any other mod which correctly tags its fluids (at the moment, that does not include TFMG, but that is a problem on their end). There will never be compatibility with other mods which add chemicals as fluids, as they operate on entirely different systems.
