### ISSUE TITLE
Mixtures duplicate in JEI pin list when being removed

### ISSUE THREAD

**Issue by uploading1111000** [petrolpark/Destroy#59]
Compatibility issue with JEI
When a mixture (such as found in the recipe for sodium via electrolysis) is pinned in JEI it cannot be removed, and will instead be duplicated when one attempts to remove the pin.

To reproduce:
Install JEI
View recipe for sodium.
Pin (press A) the recipe for mercury (or sodium chloride) 
Attempt to unpin (press A) the newly made "Water"

**Comment by petrolpark** [comment]
Fixed in 0.3.
