### ISSUE TITLE
Vats accept non-Mixture fluids in their internal buffers

### ISSUE THREAD

**Issue by ammieeee** [petrolpark/Destroy#65]
I'm completely unable to insert fluids into vats. This issue occurs even with only Create and Destroy enabled on Forge v47.2.17. Below are some images of an example setup, although it has occurred with every configuration I've tried:

![2024-01-06_21 22 29](https://github.com/petrolpark/Destroy/assets/122175572/479386e2-49c6-42b5-89b1-fd3578d98b5a)![2024-01-06_21 22 36](https://github.com/petrolpark/Destroy/assets/122175572/17174c4b-3f99-41a0-98dc-cd08dd8a5028)
![2024-01-06_21 23 33](https://github.com/petrolpark/Destroy/assets/122175572/f70e1134-0b23-498d-8690-fb9c0a248aef)

1 bucket of fluid exactly is inserted into the vat wall block, and according to /data, the fluid transferred remains in the interface block's internal buffer. Fluid continues to flow visually through the pipes without transferring anything.

So far, I have tried:
- Speeding up/slowing down the pump
- Pumping air out of the vat
- Inputting from different sides
- Applying redstone signals [I was getting desperate lol]
- Using different casing materials

Item I/O seems to function correctly [as far as I could see]

[latest.log](https://github.com/petrolpark/Destroy/files/13851445/latest.log)

**Comment by haus-jackl** [comment]
If it was water I had the same issue. You need to distill the water using bubble chambers before the cat will let you insert it

**Comment by ammieeee** [comment]
> If it was water I had the same issue. You need to distill the water using bubble chambers before the cat will let you insert it

Ah okay, I just kinda presumed regular water would be permitted as I didn't think distilled would be necessary for everything water-related.

I can't do it now but I'll see if distilled water works next time I play.

**Comment by petrolpark** [comment]
Yes, the Vat can only hold Mixtures (fluids with the ID `destroy:mixture`). The ponder will probably be updated to reflect this, and if tutorials are implemented (#60) this will definitely be something mentioned.
There side of the Vat accepting water in its internal buffer is definitely a bug though, and that will get fixed in 0.3.

**Comment by ammieeee** [comment]
Ah, I never noticed that, thanks for the help in any case

**Comment by petrolpark** [comment]
Fixed in 0.3.

**Comment by Auseawesome** [comment]
I still appear to be having this exact same issue in 0.5

**Comment by Auseawesome** [comment]
![2024-01-22_19 58 13](https://github.com/petrolpark/Destroy/assets/70506988/074dc8c1-a821-4d9c-a5c0-01a8a9af846e)
![2024-01-22_19 58 17](https://github.com/petrolpark/Destroy/assets/70506988/c6184cb3-46ef-4f56-b1b3-7e5936dc9644)
![2024-01-22_19 58 20](https://github.com/petrolpark/Destroy/assets/70506988/fc53c49c-f3b9-418f-aaf4-f2002a769753)
![2024-01-22_19 58 22](https://github.com/petrolpark/Destroy/assets/70506988/8db7de1f-b58c-451b-bc5f-85929d9adf6a)
![2024-01-22_19 58 25](https://github.com/petrolpark/Destroy/assets/70506988/435b7dbf-7e92-4c30-b230-401c631330eb)

Screenshots in order showing the process I did to confirm it was still accepting water.

Pumped it into vat, broke vat, remade vat, 1000mb gone
