### ISSUE TITLE
Mod attempting to load client side only code on to a server.

### ISSUE THREAD

**Issue by hippity-cs** [petrolpark/Destroy#66]
I'm not sure if you can do anything about this but we are trying to use a server hosting platform to play your mod with a pack, the support team responded with this.

"The Destroy mod is attempting to load client side only code on your server. This could be a client side only mod, or an indication that the mod author made a mistake in the code of their mod. You will need to remove this mod from your server."

**Comment by petrolpark** [comment]
Fixed in 0.3.
