### ISSUE TITLE
Crash with differential output stress

### ISSUE THREAD

**Issue by Kokoloa** [petrolpark/Destroy#72]
When the large gear of the  Differential  experiences output stress (such as when connected to  Mechanical press), it will immediately fail. This bug can be consistently triggered when only "create" and "destroy" are installed.
The crash report when the game fails is as follows:
[[220722] [Server threadERROR] Encou.txt](https://github.com/petrolpark/Destroy/files/13853809/220722.Server.threadERROR.Encou.txt)
（The dialogue is translated by GPT）

**Comment by Kokoloa** [comment]
If a stress gauge is connected, only the stress from a single source will be displayed on the gauge.

**Comment by petrolpark** [comment]
Fixed in 0.3.

With regards to your second comment, this is intentional. As explained in its Ponder, the Differential only propagates stress from a single source (the powered side). This will not change as it is due to the limitations of Create's rotation system.
