### ISSUE TITLE
Cannot heat bubble columns (distillation chambers, don't remember the name) to any temperature not 27/127/327 C.

### ISSUE THREAD

**Issue by TheRedCrafter344** [petrolpark/Destroy#75]
Bubble columns are immediately heated to their target temperature, and since the only heating options for them are +100C/+300C, it is impossible for them to be in any temperature that isn't these 3 temperatures. I don't know if this is a problem for any practical purposes at the moment, since I encountered it when trying to extract methanol from water solution for experimental purposes.

**Comment by petrolpark** [comment]
This is intentional, as Bubble Caps do not simulate thermodynamics like the Vat. For finer control with distillation, use a Vat. Thanks for the feedback anyway :)
