### ISSUE TITLE
Add Coordination Chemistry

### ISSUE THREAD

**Issue by gamerGodlyTv** [petrolpark/Destroy#79]
Since you'll be adding more of the inorganic chemistry towards the release, I'd suggest implementing complex chemistry too with it's pH/temperature requirements since it might make the mod a bit more tedious and reactions harder to upkeep. At the same time,  this would allow reagents such as the Tollen's reagent [Ag(NH3)2]OH  to exist within reason (and not just as the Ag2O) and could also expand into Analitical chemistry into the future as there are many pH sensitive reactions:
KCl + Na3[Co(NO2)6] = Na2K[Co(NO2)6] + NaCl in pH-s 3-7
KOH + Na3[Co(NO2)6] = Co(OH)3 + KNO2 + NaNO2 in basic conditions.

**Comment by petrolpark** [comment]
All the chemistry is already dependent on pH and temperature. There are currently no plans for any products based on complexes, so the complexes themselves probably will not become a part of base Destroy. They can still very easily be added with an add-on, however.
