### ISSUE TITLE
Add integration with GTCEu Modern

### ISSUE THREAD

**Issue by ghost** [petrolpark/Destroy#80]
Both mods have chemistry so why not integrate them.

**Comment by ThatBigDerp** [comment]
Btw thats what I've been trying to do before parku closed the repo, now that its open I maybe will finish the project

**Comment by ghost** [comment]
Yippeeeeeeeeee

**Comment by petrolpark** [comment]
Attempts to do this are supported, but it will not be a native feature of Destroy. The chemistry systems are quite different.
