### ISSUE TITLE
tnt entity spawned incorrectly

### ISSUE THREAD

**Issue by Hophenby** [petrolpark/Destroy#81]
modded tnt spawns an entity.minecraft.tnt entity when activated by another explosion, while a modded tnt entity is expected.
![7f6cde0a14125bbe](https://github.com/petrolpark/Destroy/assets/66473090/31969f53-5714-4ee6-9a47-f11c2a862a0d)
picric acid tnt blocks being tested
![-60721fa14c7bfb46](https://github.com/petrolpark/Destroy/assets/66473090/aee33aaf-8994-4d68-9643-0b8181cfebca)
vanilla tnt entities spawned
![-440fa7e90d1d6b8b](https://github.com/petrolpark/Destroy/assets/66473090/b19eeb7a-9cfe-40eb-91a8-8fccce0abd7b)
the rest of tnp blocks failed to be activated because vanilla tnt explosion works bad underwater

**Comment by BytinYarota** [comment]
It seems that the same bug has been submitted in [issue25](https://github.com/petrolpark/Destroy/issues/25), and has been solved already
