### ISSUE TITLE
agar block has same forge id with fluorite block

### ISSUE THREAD

**Issue by YuriMontana** [petrolpark/Destroy#82]
![image](https://github.com/petrolpark/Destroy/assets/111141988/7de37c00-0ec0-48cc-9773-e87719085353)
![image](https://github.com/petrolpark/Destroy/assets/111141988/019bd535-b377-4516-aa50-3e3b6edeab54)

the agar block has the same ID of forge:storage_blocks/fluorite

**Comment by petrolpark** [comment]
Duplicate of #19. Fixed in 0.3.
