### ISSUE TITLE
Bug: Crash when Printing Schematics with Bubble Caps

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#85]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.2
Bubble caps in schematics seems to prevent the whole structure from being wholly printed when using the "Print" tool of a schematic in Creative Mode, and leads to game crash when printed by a Schematicannon.
I noticed this bug when saving a distillation tower schematic. It was saved successfully. However when printed, only the first layer was printed incompletely while the other part dissappeared entirely.
I did some experiments and it seems the bubble cap is to be blame.
The following image shows the result of printing a schematic of a stone cuboid with a bubble cap inside. The printing progress seemed to be interrupted by the bubble cap block.
<img width="306" alt="failed printing" src="https://github.com/petrolpark/Destroy/assets/45122555/abec9d87-4ff6-4544-80f6-e589c5ed88e3">
And when printed by a Schematicannon, the game crashes when the bubble cap block is printed. Trying to reenter the world leads to another crash. (Somehow I failed to upload the log, but I guess it's OK since this is easy to recreate.)
Haven't found any block with similar behaviors yet.
My first time to submit an issue, hope not bothering.

**Comment by petrolpark** [comment]
Not bothering at all, this is all very useful. This has now been fixed in 0.3. Thanks for the help.
