### ISSUE TITLE
Crash on server creation

### ISSUE THREAD

**Issue by Explode007** [petrolpark/Destroy#86]
I am making a modpack thats filled with the latest and greatest and barely any mods that have been around since forever. 

Anyways, when trying to launch a server, destroy is incapable and crashes the server every time it is attempted to be loaded. I tried to launch a server with only create and destroy.

The error im getting is something to do with BlockEntityWithoutLevelRenderer, Meaning that possibly something is relying solely on a client side class that isn't loaded when creating a server.

Forge versions tried: 40.2.19 & 40.2.0

Crash:
[crash-2024-01-08_10.05.33-fml.txt](https://github.com/petrolpark/Destroy/files/13862841/crash-2024-01-08_10.05.33-fml.txt)

**Comment by Explode007** [comment]
Update: Seems that the client side only handlers are not working properly for items such as seismometer, I imagine the same follows for others. I am attempting to work on a fix.

**Comment by petrolpark** [comment]
Fixed in 0.3.

**Comment by Explode007** [comment]
Oh, ok. "_" Any EST on 0.3?

**Comment by petrolpark** [comment]
Now! https://modrinth.com/mod/destroy/version/jZ0T34nW
