### ISSUE TITLE
Crash when vat 1x1x2 and 1x1x3 is overpressurised when vat explosions are disabled

### ISSUE THREAD

**Issue by Szeregowy147** [petrolpark/Destroy#87]
Forge 47.2.0, Create Version 0.5.1.f, Destroy version 0.2 Vats explode at high pressure disabled

When vats, that have either 1x1x2 or 1x1x3 (when tested with vats 1x1x4, 2x2x2, 3x2x1 etc. there is no crash) empty space inside are overpressurised with disabled vats explosions game crashes. When tested with vats 1x1x4, 2x2x2, 3x2x1 etc. there is no crash. After restarting game vat controller shows that valid vats cannot be formed. To fix it every block of the former vat must be destroyed. Also only vats made from copper casing and iron block have this issue.
Screenshots of my setup. 
![2024-01-08_22 47 06](https://github.com/petrolpark/Destroy/assets/76481233/0ff949cf-e2af-4030-a220-c95b48dec0dd)
![2024-01-08_22 57 39](https://github.com/petrolpark/Destroy/assets/76481233/c6e98f5e-9baf-4a04-a421-cd2165ce12f3)

My crash reports
[crash-2024-01-08_22.26.22-server.txt](https://github.com/petrolpark/Destroy/files/13866526/crash-2024-01-08_22.26.22-server.txt)
[crash-2024-01-08_22.31.24-server.txt](https://github.com/petrolpark/Destroy/files/13866527/crash-2024-01-08_22.31.24-server.txt)
[crash-2024-01-08_22.43.36-server.txt](https://github.com/petrolpark/Destroy/files/13866528/crash-2024-01-08_22.43.36-server.txt)

**Comment by petrolpark** [comment]
Fixed in 0.3.
