### ISSUE TITLE
It will cause online failure

### ISSUE THREAD

**Issue by Xuezhi-Yang** [petrolpark/Destroy#88]
I can enter the game normally, but when my friend connects to my server, an error message "ecoderException: java.lang.NullPointerException: Cannot invoke Internal Exception: io.netty.handler.codec.[ geRegistry.getvalue(int) because "registry" is null net.minecraftforge.registries.Fo" appears.
After we removed this module, we could go online normally.

**Comment by Xuezhi-Yang** [comment]
My friend is sleeping,so I can't give you the log.

**Comment by petrolpark** [comment]
Duplicate of #64.
