### ISSUE TITLE
Bug: Textures of Vat Blocks Incorrectly Shown in the Interface of Attaching Display Links

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#89]
Forge 47.2.19, Create 0.5.1.f, Destroy 0.3
<img width="608" alt="abnormal texture" src="https://github.com/petrolpark/Destroy/assets/45122555/fb143834-c0ac-4a25-826f-f0e05950570b">
As shown above, the original texture of the vat block(which should be a copper casing) was replaced with that of a barrier.
This bug exists on all vat materials except the controller(as it would not be recognized as a vat block).

**Comment by petrolpark** [comment]
Fixed in 0.4. As you've submitted numerous high-quality bug reports, if you want I'll give you the **Beta Tester** Badge. DM me on Discord (`petrolpark`).
