### ISSUE TITLE
[Bug] Gas Mask clips with hat layer

### ISSUE THREAD

**Issue by Facest4b** [petrolpark/Destroy#9]
The gas mask model is sized too closely to the hat layer of minecraft skins so it z-fights/clips with it.

![image](https://github.com/petrolpark/Destroy/assets/67114230/11ff51b4-50f1-4835-b3ac-210bd58e25a4)

You can see the effect with the hair on my skin with the gas mask.

Just needs to be increased in size a little to match the vanilla helmets is all.

**Comment by petrolpark** [comment]
Fixed in 0.2.

**Comment by rosellle** [comment]
Hair is still clipping through the gas mask as of 0.2.

![image](https://github.com/petrolpark/Destroy/assets/113427740/93b37730-da57-4bb1-ba34-5dfa4b167d30)
