### ISSUE TITLE
Bug: Differential Lacks Placing Preview

### ISSUE THREAD

**Issue by BytinYarota** [petrolpark/Destroy#93]
<img width="265" alt="planetary gear set placing preview" src="https://github.com/petrolpark/Destroy/assets/45122555/fb48e631-8545-49e6-9ea1-fbe0a64714ad">
<img width="614" alt="differential without preview" src="https://github.com/petrolpark/Destroy/assets/45122555/6d155ba6-e35d-4561-80cc-429c61695bde">

The placing preview of differentials seems to be missing(whether placing by a large cogwheel or a cogwheel), while planetary gearsets and coaxial cogwheels got theirs. Its placing is normal though.

**Comment by petrolpark** [comment]
Fixed in 0.4.
