### ISSUE TITLE
Server Crash due to ClassNotFoundException: com.ibm.icu.text.DateFormat

### ISSUE THREAD

**Issue by ChronowireStudios** [petrolpark/Destroy#94]
Heya! I'm trying to load Destroy 0.3, but my Server is crashing. I've uploading the [Pastebin](https://pastebin.com/3bkuEpuR). I tried removing all of my mods aswell, except for Create and Destroy.

**Comment by Explode007** [comment]
Same issue here

**Comment by phunnyguy** [comment]
Same issue for me as well.

**Comment by petrolpark** [comment]
Fixed in 0.4.
