### ISSUE TITLE
Bug: Buble Vat incorrectly performing recipies

### ISSUE THREAD

**Issue by Typerim** [petrolpark/Destroy#98]
destroy 0.3
when pumping liquid into the reboiler, it can take up to 1000mb (1b) of liquid.
When performing a recipy that requires at most 500mb of liquid, such as the urine distilling or oil refining (at 100mb), it only produces one recipy worth of product, yet takes as many recipies worth of liquid.

In case of urine in takes a full bucket, yet only produces 500mb of ammonia solution, where 1b of solution is expected.
In case of oil, it can take a full bucket, but only produces 1b of lpg, which is the limit one buble vat block can take.

(username:'Kubusje02')

**Comment by Typerim** [comment]
In the case of urine, the product expected should be 1:1mb at 500 increments, yet always provides 500mb no matter if it consumes 500 or 1000mb

In the case of oil, it should never take more than 100mb at a time, as it produces 1000mb of lpg, which is the most a bubble vat section can buffer.

**Comment by Typerim** [comment]
After further testing, it seems that buble vats consume any liquid equal to more of a liquid for a recipy, so for urine it takes 500mb or more, but produces as if it took only 500mb.

**Comment by petrolpark** [comment]
Fixed in 0.4.
