### ISSUE TITLE
Bug: Bubble Vat only allows one connection per block

### ISSUE THREAD

**Issue by Typerim** [petrolpark/Destroy#99]
destroy 0.3
Placing pipes and pumps next to a bubble vat, it (at least visually) only connects to the first pipe/pump pointing at the block, and can switch to another when the block it's connecting to is removed. However, contrary to create's tanks, bubble vat's only allow one connection per block, as said in the title. Not sure if this is intended behaviour or an oversight.

(username:'Kubusje02')

**Comment by petrolpark** [comment]
Intended behaviour.
